apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: aetherius

resources:
- statefulset.yaml
- service.yaml

labels:
- pairs:
    app.kubernetes.io/name: neo4j
    app.kubernetes.io/component: graph-db
    app.kubernetes.io/part-of: aetherius

# Secret will be created in overlays
