// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/kart-io/k8s-agent/cmd/agent-manager/app/options"
	"github.com/kart-io/k8s-agent/internal/agent-manager/initializers"
	pkginitializers "github.com/kart-io/k8s-agent/pkg/initializers"
)

// Injectors from wire.go:

// InitializeAgentManagerComponents automatically injects all components using Wire.
func InitializeAgentManagerComponents(opts *options.ServerOptions) (*AgentManagerComponents, error) {
	logger, err := ProvideLogger(opts)
	if err != nil {
		return nil, err
	}
	databaseInitializer := initializers.NewDatabaseInitializer(opts, logger)
	redisInitializer := initializers.NewRedisInitializer(opts, logger)
	registryInitializer := initializers.NewRegistryInitializer(opts, logger, databaseInitializer, redisInitializer)
	natsInitializer := initializers.NewNATSInitializer(opts, logger, registryInitializer, databaseInitializer, redisInitializer)
	dispatcherInitializer := initializers.NewDispatcherInitializer(opts, logger, databaseInitializer, redisInitializer, registryInitializer, natsInitializer)
	httpServerInitializer := initializers.NewHTTPServerInitializer(opts, logger, registryInitializer, dispatcherInitializer, databaseInitializer, redisInitializer, natsInitializer)
	healthOptions := opts.Health
	healthCheckInitializer := pkginitializers.NewHealthCheckInitializer(healthOptions, logger)
	agentManagerComponents := NewAgentManagerComponents(databaseInitializer, redisInitializer, registryInitializer, natsInitializer, dispatcherInitializer, httpServerInitializer, healthCheckInitializer)
	return agentManagerComponents, nil
}

