// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/google/wire"
	"github.com/kart-io/k8s-agent/internal/agent-manager/initializers"
	"github.com/kart-io/k8s-agent/pkg/app"
	initializers2 "github.com/kart-io/k8s-agent/pkg/initializers"
)

// Injectors from wire.go:

// InitializeAgentManagerContainer automatically injects all components using Wire.
func InitializeAgentManagerContainer(opts *app.StandardOptions) (*AgentManagerContainer, error) {
	logger, err := ProvideLogger(opts)
	if err != nil {
		return nil, err
	}
	databaseInitializer := initializers.NewDatabaseInitializer(opts, logger)
	redisInitializer := initializers.NewRedisInitializer(opts, logger)
	serviceInitializer := initializers.NewServiceInitializer(opts, logger, databaseInitializer, redisInitializer)
	registryInitializer := initializers.NewRegistryInitializer(opts, logger, serviceInitializer)
	natsInitializer := initializers.NewNATSInitializer(opts, logger, serviceInitializer)
	dispatcherInitializer := initializers.NewDispatcherInitializer(opts, logger, serviceInitializer, natsInitializer)
	httpServerInitializer := initializers.NewHTTPServerInitializer(opts, logger, serviceInitializer, databaseInitializer, redisInitializer)
	grpcServerInitializer := initializers.NewGRPCServerInitializer(opts, logger, serviceInitializer, databaseInitializer)
	healthOptions := opts.Health
	healthCheckInitializer := initializers2.NewHealthCheckInitializer(healthOptions, logger)
	agentManagerContainer := NewAgentManagerContainer(databaseInitializer, redisInitializer, serviceInitializer, registryInitializer, natsInitializer, dispatcherInitializer, httpServerInitializer, grpcServerInitializer, healthCheckInitializer)
	return agentManagerContainer, nil
}

// wire.go:

// InitializerSet Wire dependency set for all initializers.
var InitializerSet = wire.NewSet(
	ProvideLogger, initializers.NewDatabaseInitializer, initializers.NewRedisInitializer, initializers.NewServiceInitializer, initializers.NewRegistryInitializer, initializers.NewNATSInitializer, initializers.NewDispatcherInitializer, initializers.NewHTTPServerInitializer, initializers.NewGRPCServerInitializer,
)

// HealthInitializerSet Wire dependency set for health check.
var HealthInitializerSet = wire.NewSet(initializers2.NewHealthCheckInitializer, wire.FieldsOf(new(*app.StandardOptions), "Health"))
