apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: aetherius-dev

resources:
- namespace.yaml
- postgres
- redis
- neo4j
- nats

labels:
- pairs:
    environment: development
    managed-by: kustomize
