// agent/command.proto
// 命令调度 API 定义

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: agent/v1/command.proto

package agentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 命令类型
type Command_Type int32

const (
	Command_TYPE_UNSPECIFIED Command_Type = 0
	Command_KUBECTL          Command_Type = 1 // kubectl 命令
	Command_DIAGNOSTIC       Command_Type = 2 // 诊断命令
	Command_REMEDIATION      Command_Type = 3 // 修复命令
	Command_CUSTOM           Command_Type = 4 // 自定义命令
)

// Enum value maps for Command_Type.
var (
	Command_Type_name = map[int32]string{
		0: "TYPE_UNSPECIFIED",
		1: "KUBECTL",
		2: "DIAGNOSTIC",
		3: "REMEDIATION",
		4: "CUSTOM",
	}
	Command_Type_value = map[string]int32{
		"TYPE_UNSPECIFIED": 0,
		"KUBECTL":          1,
		"DIAGNOSTIC":       2,
		"REMEDIATION":      3,
		"CUSTOM":           4,
	}
)

func (x Command_Type) Enum() *Command_Type {
	p := new(Command_Type)
	*p = x
	return p
}

func (x Command_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Command_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_v1_command_proto_enumTypes[0].Descriptor()
}

func (Command_Type) Type() protoreflect.EnumType {
	return &file_agent_v1_command_proto_enumTypes[0]
}

func (x Command_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Command_Type.Descriptor instead.
func (Command_Type) EnumDescriptor() ([]byte, []int) {
	return file_agent_v1_command_proto_rawDescGZIP(), []int{0, 0}
}

// 命令状态
type Command_Status int32

const (
	Command_STATUS_UNSPECIFIED Command_Status = 0
	Command_PENDING            Command_Status = 1 // 待执行
	Command_RUNNING            Command_Status = 2 // 执行中
	Command_SUCCESS            Command_Status = 3 // 成功
	Command_FAILED             Command_Status = 4 // 失败
	Command_TIMEOUT            Command_Status = 5 // 超时
	Command_CANCELLED          Command_Status = 6 // 已取消
)

// Enum value maps for Command_Status.
var (
	Command_Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "PENDING",
		2: "RUNNING",
		3: "SUCCESS",
		4: "FAILED",
		5: "TIMEOUT",
		6: "CANCELLED",
	}
	Command_Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"PENDING":            1,
		"RUNNING":            2,
		"SUCCESS":            3,
		"FAILED":             4,
		"TIMEOUT":            5,
		"CANCELLED":          6,
	}
)

func (x Command_Status) Enum() *Command_Status {
	p := new(Command_Status)
	*p = x
	return p
}

func (x Command_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Command_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_v1_command_proto_enumTypes[1].Descriptor()
}

func (Command_Status) Type() protoreflect.EnumType {
	return &file_agent_v1_command_proto_enumTypes[1]
}

func (x Command_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Command_Status.Descriptor instead.
func (Command_Status) EnumDescriptor() ([]byte, []int) {
	return file_agent_v1_command_proto_rawDescGZIP(), []int{0, 1}
}

// 命令定义
type Command struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 命令 ID
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Agent ID
	AgentId string       `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Type    Command_Type `protobuf:"varint,3,opt,name=type,proto3,enum=agent.v1.Command_Type" json:"type,omitempty"`
	// 命令内容
	Content string `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	// 命令参数
	Params map[string]string `protobuf:"bytes,5,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Status Command_Status    `protobuf:"varint,6,opt,name=status,proto3,enum=agent.v1.Command_Status" json:"status,omitempty"`
	// 命令结果
	Result string `protobuf:"bytes,7,opt,name=result,proto3" json:"result,omitempty"`
	// 错误信息
	Error string `protobuf:"bytes,8,opt,name=error,proto3" json:"error,omitempty"`
	// 创建时间
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// 开始执行时间
	StartedAt *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	// 完成时间
	CompletedAt *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	// 超时设置（秒）
	Timeout       int32 `protobuf:"varint,12,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_agent_v1_command_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_command_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_agent_v1_command_proto_rawDescGZIP(), []int{0}
}

func (x *Command) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Command) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *Command) GetType() Command_Type {
	if x != nil {
		return x.Type
	}
	return Command_TYPE_UNSPECIFIED
}

func (x *Command) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Command) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *Command) GetStatus() Command_Status {
	if x != nil {
		return x.Status
	}
	return Command_STATUS_UNSPECIFIED
}

func (x *Command) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *Command) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *Command) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Command) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *Command) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

func (x *Command) GetTimeout() int32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

// 执行命令请求
type ExecuteCommandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Type          Command_Type           `protobuf:"varint,2,opt,name=type,proto3,enum=agent.v1.Command_Type" json:"type,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Params        map[string]string      `protobuf:"bytes,4,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Timeout       int32                  `protobuf:"varint,5,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteCommandRequest) Reset() {
	*x = ExecuteCommandRequest{}
	mi := &file_agent_v1_command_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteCommandRequest) ProtoMessage() {}

func (x *ExecuteCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_command_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteCommandRequest.ProtoReflect.Descriptor instead.
func (*ExecuteCommandRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_command_proto_rawDescGZIP(), []int{1}
}

func (x *ExecuteCommandRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ExecuteCommandRequest) GetType() Command_Type {
	if x != nil {
		return x.Type
	}
	return Command_TYPE_UNSPECIFIED
}

func (x *ExecuteCommandRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ExecuteCommandRequest) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *ExecuteCommandRequest) GetTimeout() int32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

// 执行命令响应
type ExecuteCommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       *Command               `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteCommandResponse) Reset() {
	*x = ExecuteCommandResponse{}
	mi := &file_agent_v1_command_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteCommandResponse) ProtoMessage() {}

func (x *ExecuteCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_command_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteCommandResponse.ProtoReflect.Descriptor instead.
func (*ExecuteCommandResponse) Descriptor() ([]byte, []int) {
	return file_agent_v1_command_proto_rawDescGZIP(), []int{2}
}

func (x *ExecuteCommandResponse) GetCommand() *Command {
	if x != nil {
		return x.Command
	}
	return nil
}

// 获取命令状态请求
type GetCommandStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommandStatusRequest) Reset() {
	*x = GetCommandStatusRequest{}
	mi := &file_agent_v1_command_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommandStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommandStatusRequest) ProtoMessage() {}

func (x *GetCommandStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_command_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommandStatusRequest.ProtoReflect.Descriptor instead.
func (*GetCommandStatusRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_command_proto_rawDescGZIP(), []int{3}
}

func (x *GetCommandStatusRequest) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

// 获取命令状态响应
type GetCommandStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       *Command               `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommandStatusResponse) Reset() {
	*x = GetCommandStatusResponse{}
	mi := &file_agent_v1_command_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommandStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommandStatusResponse) ProtoMessage() {}

func (x *GetCommandStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_command_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommandStatusResponse.ProtoReflect.Descriptor instead.
func (*GetCommandStatusResponse) Descriptor() ([]byte, []int) {
	return file_agent_v1_command_proto_rawDescGZIP(), []int{4}
}

func (x *GetCommandStatusResponse) GetCommand() *Command {
	if x != nil {
		return x.Command
	}
	return nil
}

// 取消命令请求
type CancelCommandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelCommandRequest) Reset() {
	*x = CancelCommandRequest{}
	mi := &file_agent_v1_command_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelCommandRequest) ProtoMessage() {}

func (x *CancelCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_command_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelCommandRequest.ProtoReflect.Descriptor instead.
func (*CancelCommandRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_command_proto_rawDescGZIP(), []int{5}
}

func (x *CancelCommandRequest) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

// 取消命令响应
type CancelCommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelCommandResponse) Reset() {
	*x = CancelCommandResponse{}
	mi := &file_agent_v1_command_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelCommandResponse) ProtoMessage() {}

func (x *CancelCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_command_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelCommandResponse.ProtoReflect.Descriptor instead.
func (*CancelCommandResponse) Descriptor() ([]byte, []int) {
	return file_agent_v1_command_proto_rawDescGZIP(), []int{6}
}

func (x *CancelCommandResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_agent_v1_command_proto protoreflect.FileDescriptor

const file_agent_v1_command_proto_rawDesc = "" +
	"\n" +
	"\x16agent/v1/command.proto\x12\bagent.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe4\x05\n" +
	"\aCommand\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12*\n" +
	"\x04type\x18\x03 \x01(\x0e2\x16.agent.v1.Command.TypeR\x04type\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x125\n" +
	"\x06params\x18\x05 \x03(\v2\x1d.agent.v1.Command.ParamsEntryR\x06params\x120\n" +
	"\x06status\x18\x06 \x01(\x0e2\x18.agent.v1.Command.StatusR\x06status\x12\x16\n" +
	"\x06result\x18\a \x01(\tR\x06result\x12\x14\n" +
	"\x05error\x18\b \x01(\tR\x05error\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"started_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12=\n" +
	"\fcompleted_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\x12\x18\n" +
	"\atimeout\x18\f \x01(\x05R\atimeout\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"V\n" +
	"\x04Type\x12\x14\n" +
	"\x10TYPE_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aKUBECTL\x10\x01\x12\x0e\n" +
	"\n" +
	"DIAGNOSTIC\x10\x02\x12\x0f\n" +
	"\vREMEDIATION\x10\x03\x12\n" +
	"\n" +
	"\x06CUSTOM\x10\x04\"o\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aPENDING\x10\x01\x12\v\n" +
	"\aRUNNING\x10\x02\x12\v\n" +
	"\aSUCCESS\x10\x03\x12\n" +
	"\n" +
	"\x06FAILED\x10\x04\x12\v\n" +
	"\aTIMEOUT\x10\x05\x12\r\n" +
	"\tCANCELLED\x10\x06\"\x92\x02\n" +
	"\x15ExecuteCommandRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12*\n" +
	"\x04type\x18\x02 \x01(\x0e2\x16.agent.v1.Command.TypeR\x04type\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12C\n" +
	"\x06params\x18\x04 \x03(\v2+.agent.v1.ExecuteCommandRequest.ParamsEntryR\x06params\x12\x18\n" +
	"\atimeout\x18\x05 \x01(\x05R\atimeout\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"E\n" +
	"\x16ExecuteCommandResponse\x12+\n" +
	"\acommand\x18\x01 \x01(\v2\x11.agent.v1.CommandR\acommand\"8\n" +
	"\x17GetCommandStatusRequest\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\"G\n" +
	"\x18GetCommandStatusResponse\x12+\n" +
	"\acommand\x18\x01 \x01(\v2\x11.agent.v1.CommandR\acommand\"5\n" +
	"\x14CancelCommandRequest\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\"1\n" +
	"\x15CancelCommandResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\x92\x02\n" +
	"\x0eCommandService\x12S\n" +
	"\x0eExecuteCommand\x12\x1f.agent.v1.ExecuteCommandRequest\x1a .agent.v1.ExecuteCommandResponse\x12Y\n" +
	"\x10GetCommandStatus\x12!.agent.v1.GetCommandStatusRequest\x1a\".agent.v1.GetCommandStatusResponse\x12P\n" +
	"\rCancelCommand\x12\x1e.agent.v1.CancelCommandRequest\x1a\x1f.agent.v1.CancelCommandResponseB\x94\x01\n" +
	"\fcom.agent.v1B\fCommandProtoP\x01Z5github.com/kart-io/k8s-agent/pkg/api/agent/v1;agentv1\xa2\x02\x03AXX\xaa\x02\bAgent.V1\xca\x02\bAgent\\V1\xe2\x02\x14Agent\\V1\\GPBMetadata\xea\x02\tAgent::V1b\x06proto3"

var (
	file_agent_v1_command_proto_rawDescOnce sync.Once
	file_agent_v1_command_proto_rawDescData []byte
)

func file_agent_v1_command_proto_rawDescGZIP() []byte {
	file_agent_v1_command_proto_rawDescOnce.Do(func() {
		file_agent_v1_command_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_v1_command_proto_rawDesc), len(file_agent_v1_command_proto_rawDesc)))
	})
	return file_agent_v1_command_proto_rawDescData
}

var file_agent_v1_command_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_agent_v1_command_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_agent_v1_command_proto_goTypes = []any{
	(Command_Type)(0),                // 0: agent.v1.Command.Type
	(Command_Status)(0),              // 1: agent.v1.Command.Status
	(*Command)(nil),                  // 2: agent.v1.Command
	(*ExecuteCommandRequest)(nil),    // 3: agent.v1.ExecuteCommandRequest
	(*ExecuteCommandResponse)(nil),   // 4: agent.v1.ExecuteCommandResponse
	(*GetCommandStatusRequest)(nil),  // 5: agent.v1.GetCommandStatusRequest
	(*GetCommandStatusResponse)(nil), // 6: agent.v1.GetCommandStatusResponse
	(*CancelCommandRequest)(nil),     // 7: agent.v1.CancelCommandRequest
	(*CancelCommandResponse)(nil),    // 8: agent.v1.CancelCommandResponse
	nil,                              // 9: agent.v1.Command.ParamsEntry
	nil,                              // 10: agent.v1.ExecuteCommandRequest.ParamsEntry
	(*timestamppb.Timestamp)(nil),    // 11: google.protobuf.Timestamp
}
var file_agent_v1_command_proto_depIdxs = []int32{
	0,  // 0: agent.v1.Command.type:type_name -> agent.v1.Command.Type
	9,  // 1: agent.v1.Command.params:type_name -> agent.v1.Command.ParamsEntry
	1,  // 2: agent.v1.Command.status:type_name -> agent.v1.Command.Status
	11, // 3: agent.v1.Command.created_at:type_name -> google.protobuf.Timestamp
	11, // 4: agent.v1.Command.started_at:type_name -> google.protobuf.Timestamp
	11, // 5: agent.v1.Command.completed_at:type_name -> google.protobuf.Timestamp
	0,  // 6: agent.v1.ExecuteCommandRequest.type:type_name -> agent.v1.Command.Type
	10, // 7: agent.v1.ExecuteCommandRequest.params:type_name -> agent.v1.ExecuteCommandRequest.ParamsEntry
	2,  // 8: agent.v1.ExecuteCommandResponse.command:type_name -> agent.v1.Command
	2,  // 9: agent.v1.GetCommandStatusResponse.command:type_name -> agent.v1.Command
	3,  // 10: agent.v1.CommandService.ExecuteCommand:input_type -> agent.v1.ExecuteCommandRequest
	5,  // 11: agent.v1.CommandService.GetCommandStatus:input_type -> agent.v1.GetCommandStatusRequest
	7,  // 12: agent.v1.CommandService.CancelCommand:input_type -> agent.v1.CancelCommandRequest
	4,  // 13: agent.v1.CommandService.ExecuteCommand:output_type -> agent.v1.ExecuteCommandResponse
	6,  // 14: agent.v1.CommandService.GetCommandStatus:output_type -> agent.v1.GetCommandStatusResponse
	8,  // 15: agent.v1.CommandService.CancelCommand:output_type -> agent.v1.CancelCommandResponse
	13, // [13:16] is the sub-list for method output_type
	10, // [10:13] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_agent_v1_command_proto_init() }
func file_agent_v1_command_proto_init() {
	if File_agent_v1_command_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_v1_command_proto_rawDesc), len(file_agent_v1_command_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_v1_command_proto_goTypes,
		DependencyIndexes: file_agent_v1_command_proto_depIdxs,
		EnumInfos:         file_agent_v1_command_proto_enumTypes,
		MessageInfos:      file_agent_v1_command_proto_msgTypes,
	}.Build()
	File_agent_v1_command_proto = out.File
	file_agent_v1_command_proto_goTypes = nil
	file_agent_v1_command_proto_depIdxs = nil
}
