// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/kart-io/k8s-agent/cmd/auth/app/options"
	"github.com/kart-io/k8s-agent/internal/auth/initializers"
	pkginitializers "github.com/kart-io/k8s-agent/pkg/initializers"
)

// Injectors from wire.go:

// InitializeAuthComponents automatically injects all components using Wire.
func InitializeAuthComponents(opts *options.ServerOptions) (*AuthComponents, error) {
	logger, err := ProvideLogger(opts)
	if err != nil {
		return nil, err
	}
	databaseInitializer := initializers.NewDatabaseInitializer(opts, logger)
	redisInitializer := initializers.NewRedisInitializer(opts, logger)
	sessionServiceInitializer := initializers.NewSessionServiceInitializer(opts, logger, databaseInitializer, redisInitializer)
	emailClientInitializer := initializers.NewEmailClientInitializer(opts, logger)
	auditServiceInitializer := initializers.NewAuditServiceInitializer(opts, logger, databaseInitializer)
	notificationServiceInitializer := initializers.NewNotificationServiceInitializer(opts, logger, databaseInitializer, emailClientInitializer)
	forcedLogoutServiceInitializer := initializers.NewForcedLogoutServiceInitializer(opts, logger, sessionServiceInitializer, auditServiceInitializer, notificationServiceInitializer)
	httpServerInitializer := initializers.NewHTTPServerInitializer(opts, logger, databaseInitializer, redisInitializer, sessionServiceInitializer, auditServiceInitializer, notificationServiceInitializer, forcedLogoutServiceInitializer, emailClientInitializer)
	healthOptions := opts.Health
	healthCheckInitializer := pkginitializers.NewHealthCheckInitializer(healthOptions, logger)
	authComponents := NewAuthComponents(databaseInitializer, redisInitializer, sessionServiceInitializer, emailClientInitializer, auditServiceInitializer, notificationServiceInitializer, forcedLogoutServiceInitializer, httpServerInitializer, healthCheckInitializer)
	return authComponents, nil
}

