// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/google/wire"
	"github.com/kart-io/k8s-agent/internal/auth/initializers"
	"github.com/kart-io/k8s-agent/pkg/app"
	initializers2 "github.com/kart-io/k8s-agent/pkg/initializers"
)

// Injectors from wire.go:

// InitializeAuthComponents automatically injects all components using Wire.
func InitializeAuthComponents(opts *app.StandardOptions) (*AuthComponents, error) {
	logger, err := ProvideLogger(opts)
	if err != nil {
		return nil, err
	}
	databaseInitializer := initializers.NewDatabaseInitializer(opts, logger)
	redisInitializer := initializers.NewRedisInitializer(opts, logger)
	sessionServiceInitializer := initializers.NewSessionServiceInitializer(opts, logger, databaseInitializer, redisInitializer)
	emailClientInitializer := initializers.NewEmailClientInitializer(opts, logger)
	auditServiceInitializer := initializers.NewAuditServiceInitializer(opts, logger, databaseInitializer)
	notificationServiceInitializer := initializers.NewNotificationServiceInitializer(opts, logger, databaseInitializer, emailClientInitializer)
	forcedLogoutServiceInitializer := initializers.NewForcedLogoutServiceInitializer(opts, logger, sessionServiceInitializer, auditServiceInitializer, notificationServiceInitializer)
	grpcServerInitializer := initializers.NewGRPCServerInitializer(opts, logger, databaseInitializer, redisInitializer, sessionServiceInitializer)
	httpServerInitializer := initializers.NewHTTPServerInitializer(opts, logger, databaseInitializer, redisInitializer, sessionServiceInitializer, auditServiceInitializer, notificationServiceInitializer, forcedLogoutServiceInitializer, emailClientInitializer, grpcServerInitializer)
	healthOptions := opts.Health
	healthCheckInitializer := initializers2.NewHealthCheckInitializer(healthOptions, logger)
	authComponents := NewAuthComponents(databaseInitializer, redisInitializer, sessionServiceInitializer, emailClientInitializer, auditServiceInitializer, notificationServiceInitializer, forcedLogoutServiceInitializer, grpcServerInitializer, httpServerInitializer, healthCheckInitializer)
	return authComponents, nil
}

// wire.go:

// BaseProviderSet Wire dependency set for base infrastructure.
var BaseProviderSet = wire.NewSet(
	ProvideLogger, initializers.NewDatabaseInitializer, initializers.NewRedisInitializer,
)

// ServiceProviderSet Wire dependency set for business services.
var ServiceProviderSet = wire.NewSet(
	BaseProviderSet, initializers.NewSessionServiceInitializer, initializers.NewEmailClientInitializer, initializers.NewAuditServiceInitializer, initializers.NewNotificationServiceInitializer, initializers.NewForcedLogoutServiceInitializer,
)

// ServerProviderSet Wire dependency set for servers (gRPC and HTTP).
var ServerProviderSet = wire.NewSet(
	ServiceProviderSet, initializers.NewGRPCServerInitializer, initializers.NewHTTPServerInitializer,
)

// HealthProviderSet Wire dependency set for health check.
var HealthProviderSet = wire.NewSet(initializers2.NewHealthCheckInitializer, wire.FieldsOf(new(*app.StandardOptions), "Health"))
