package forcedlogout

import (
	"context"
	"fmt"
	"time"

	"github.com/kart-io/k8s-agent/internal/auth/forced-logout/audit"
	"github.com/kart-io/k8s-agent/internal/auth/forced-logout/notification"
	"github.com/kart-io/k8s-agent/internal/auth/forced-logout/session"
	"github.com/kart-io/k8s-agent/internal/auth/types"
)

// Service provides core forced logout operations
// It orchestrates session revocation, audit logging, and user notifications
type Service struct {
	sessionService      *session.Service
	auditService        *audit.Service
	notificationService *notification.Service
	loginURL            string // Base URL for login page
}

// NewService creates a new forced logout service
func NewService(
	sessionService *session.Service,
	auditService *audit.Service,
	notificationService *notification.Service,
	loginURL string,
) *Service {
	return &Service{
		sessionService:      sessionService,
		auditService:        auditService,
		notificationService: notificationService,
		loginURL:            loginURL,
	}
}

// ForceLogoutSessionParams contains parameters for single session logout
type ForceLogoutSessionParams struct {
	JTI            string
	UserID         string
	ActorID        string
	ActorUsername  string
	ActorIPAddress string
	Reason         string
	TriggeredBy    string // manual, policy, security_incident
	CorrelationID  string
}

// ForceLogoutUserParams contains parameters for all user sessions logout
type ForceLogoutUserParams struct {
	UserID         string
	ActorID        string
	ActorUsername  string
	ActorIPAddress string
	Reason         string
	TriggeredBy    string
	CorrelationID  string
}

// BulkForceLogoutParams contains parameters for bulk session logout
type BulkForceLogoutParams struct {
	JTIs           []string
	ActorID        string
	ActorUsername  string
	ActorIPAddress string
	Reason         string
	TriggeredBy    string
	CorrelationID  string
}

// ForceLogoutResult represents the result of a forced logout operation
type ForceLogoutResult struct {
	EventID          string    `json:"event_id"`
	SessionCount     int       `json:"session_count"`
	AuditRecorded    bool      `json:"audit_recorded"`
	NotificationSent bool      `json:"notification_sent"`
	Timestamp        time.Time `json:"timestamp"`
}

// ForceLogoutSession terminates a single session by JTI
func (s *Service) ForceLogoutSession(ctx context.Context, params ForceLogoutSessionParams) (*ForceLogoutResult, error) {
	// Validate parameters
	if err := s.validateSessionParams(params); err != nil {
		return nil, fmt.Errorf("validate params: %w", err)
	}

	// Get session info before termination (for audit and notification)
	sessionInfo, err := s.sessionService.GetSession(ctx, params.JTI)
	if err != nil {
		return nil, fmt.Errorf("get session: %w", err)
	}

	// Verify session belongs to specified user
	if sessionInfo.UserID != params.UserID {
		return nil, fmt.Errorf("session does not belong to specified user")
	}

	// Terminate the session
	if err := s.sessionService.TerminateSession(
		ctx,
		params.JTI,
		params.UserID,
		params.ActorID,
		params.Reason,
		"", // eventID will be generated by audit service
	); err != nil {
		return nil, fmt.Errorf("terminate session: %w", err)
	}

	// Record audit event
	sessionMetadata := types.SessionMetadata{
		{
			JTI:        sessionInfo.JTI,
			IPAddress:  sessionInfo.IPAddress,
			DeviceName: sessionInfo.DeviceName,
			LoginAt:    sessionInfo.LoginAt,
		},
	}

	eventID, err := s.auditService.RecordEvent(ctx, audit.RecordEventParams{
		ActorType:       "admin",
		ActorID:         &params.ActorID,
		ActorUsername:   &params.ActorUsername,
		ActorIPAddress:  &params.ActorIPAddress,
		TargetUserID:    params.UserID,
		TargetUsername:  sessionInfo.Username,
		SessionJTI:      &params.JTI,
		SessionCount:    1,
		SessionMetadata: sessionMetadata,
		Reason:          &params.Reason,
		LogoutType:      "single",
		TriggeredBy:     params.TriggeredBy,
		CorrelationID:   &params.CorrelationID,
	})
	if err != nil {
		return nil, fmt.Errorf("record audit event: %w", err)
	}

	// Send notification asynchronously
	notificationErr := s.notificationService.NotifyUser(ctx, notification.NotifyUserParams{
		EventID:      eventID,
		UserID:       params.UserID,
		EmailAddress: sessionInfo.Email, // Assume Email field exists in SessionInfo
		Username:     sessionInfo.Username,
		Timestamp:    time.Now(),
		Reason:       params.Reason,
		DeviceInfo:   sessionInfo.DeviceName,
		Location:     sessionInfo.Location,
		ActorName:    params.ActorUsername,
		LoginURL:     s.loginURL,
	})

	return &ForceLogoutResult{
		EventID:          eventID,
		SessionCount:     1,
		AuditRecorded:    true,
		NotificationSent: notificationErr == nil,
		Timestamp:        time.Now(),
	}, nil
}

// ForceLogoutUser terminates all sessions for a user
func (s *Service) ForceLogoutUser(ctx context.Context, params ForceLogoutUserParams) (*ForceLogoutResult, error) {
	// Validate parameters
	if err := s.validateUserParams(params); err != nil {
		return nil, fmt.Errorf("validate params: %w", err)
	}

	// Get all user sessions before termination
	sessionList, err := s.sessionService.GetUserSessions(ctx, params.UserID, 1000, 0)
	if err != nil {
		return nil, fmt.Errorf("get user sessions: %w", err)
	}

	if len(sessionList.Sessions) == 0 {
		return &ForceLogoutResult{
			EventID:          "",
			SessionCount:     0,
			AuditRecorded:    false,
			NotificationSent: false,
			Timestamp:        time.Now(),
		}, nil
	}

	// Build session metadata for audit
	sessionMetadata := make(types.SessionMetadata, len(sessionList.Sessions))
	for i, sess := range sessionList.Sessions {
		sessionMetadata[i] = types.SessionDetail{
			JTI:        sess.JTI,
			IPAddress:  sess.IPAddress,
			DeviceName: sess.DeviceName,
			LoginAt:    sess.LoginAt,
		}
	}

	// Record audit event first (to get eventID)
	eventID, err := s.auditService.RecordEvent(ctx, audit.RecordEventParams{
		ActorType:       "admin",
		ActorID:         &params.ActorID,
		ActorUsername:   &params.ActorUsername,
		ActorIPAddress:  &params.ActorIPAddress,
		TargetUserID:    params.UserID,
		TargetUsername:  sessionList.Username,
		SessionJTI:      nil, // No single JTI for "all" logout
		SessionCount:    len(sessionList.Sessions),
		SessionMetadata: sessionMetadata,
		Reason:          &params.Reason,
		LogoutType:      "all",
		TriggeredBy:     params.TriggeredBy,
		CorrelationID:   &params.CorrelationID,
	})
	if err != nil {
		return nil, fmt.Errorf("record audit event: %w", err)
	}

	// Terminate all user sessions
	terminatedCount, err := s.sessionService.TerminateUserSessions(
		ctx,
		params.UserID,
		params.ActorID,
		params.Reason,
		eventID,
	)
	if err != nil {
		return nil, fmt.Errorf("terminate user sessions: %w", err)
	}

	// Send notification asynchronously (use first session for device info)
	var location, email string
	if len(sessionList.Sessions) > 0 {
		location = sessionList.Sessions[0].Location
		email = sessionList.Sessions[0].Email
	}

	notificationErr := s.notificationService.NotifyUser(ctx, notification.NotifyUserParams{
		EventID:      eventID,
		UserID:       params.UserID,
		EmailAddress: email,
		Username:     sessionList.Username,
		Timestamp:    time.Now(),
		Reason:       params.Reason,
		DeviceInfo:   fmt.Sprintf("%d sessions", terminatedCount),
		Location:     location,
		ActorName:    params.ActorUsername,
		LoginURL:     s.loginURL,
	})

	return &ForceLogoutResult{
		EventID:          eventID,
		SessionCount:     terminatedCount,
		AuditRecorded:    true,
		NotificationSent: notificationErr == nil,
		Timestamp:        time.Now(),
	}, nil
}

// BulkForceLogout terminates multiple specified sessions
func (s *Service) BulkForceLogout(ctx context.Context, params BulkForceLogoutParams) (*BulkForceLogoutResult, error) {
	// Validate parameters
	if err := s.validateBulkParams(params); err != nil {
		return nil, fmt.Errorf("validate params: %w", err)
	}

	results := make([]types.SessionLogoutResult, len(params.JTIs))
	sessionMetadata := make(types.SessionMetadata, 0, len(params.JTIs))
	successCount := 0
	var targetUserID, targetUsername string

	// Process each JTI
	for i, jti := range params.JTIs {
		// Get session info
		sessionInfo, err := s.sessionService.GetSession(ctx, jti)
		if err != nil {
			results[i] = types.SessionLogoutResult{
				JTI:     jti,
				Success: false,
				Error:   err.Error(),
			}
			continue
		}

		// Store target user info from first session
		if targetUserID == "" {
			targetUserID = sessionInfo.UserID
			targetUsername = sessionInfo.Username
		}

		// Terminate session
		if err := s.sessionService.TerminateSession(
			ctx,
			jti,
			sessionInfo.UserID,
			params.ActorID,
			params.Reason,
			"", // eventID will be set later
		); err != nil {
			results[i] = types.SessionLogoutResult{
				JTI:     jti,
				Success: false,
				Error:   err.Error(),
			}
			continue
		}

		results[i] = types.SessionLogoutResult{
			JTI:     jti,
			Success: true,
		}
		successCount++

		// Add to session metadata
		sessionMetadata = append(sessionMetadata, types.SessionDetail{
			JTI:        sessionInfo.JTI,
			IPAddress:  sessionInfo.IPAddress,
			DeviceName: sessionInfo.DeviceName,
			LoginAt:    sessionInfo.LoginAt,
		})
	}

	// Record audit event if at least one session was terminated
	var eventID string
	if successCount > 0 {
		eventID, _ = s.auditService.RecordEvent(ctx, audit.RecordEventParams{
			ActorType:       "admin",
			ActorID:         &params.ActorID,
			ActorUsername:   &params.ActorUsername,
			ActorIPAddress:  &params.ActorIPAddress,
			TargetUserID:    targetUserID,
			TargetUsername:  targetUsername,
			SessionJTI:      nil,
			SessionCount:    successCount,
			SessionMetadata: sessionMetadata,
			Reason:          &params.Reason,
			LogoutType:      "bulk",
			TriggeredBy:     params.TriggeredBy,
			CorrelationID:   &params.CorrelationID,
		})
	}

	return &BulkForceLogoutResult{
		EventID:      eventID,
		TotalCount:   len(params.JTIs),
		SuccessCount: successCount,
		FailedCount:  len(params.JTIs) - successCount,
		Results:      results,
		Timestamp:    time.Now(),
	}, nil
}

// BulkForceLogoutResult represents the result of bulk logout operation
type BulkForceLogoutResult struct {
	EventID      string                      `json:"event_id"`
	TotalCount   int                         `json:"total_count"`
	SuccessCount int                         `json:"success_count"`
	FailedCount  int                         `json:"failed_count"`
	Results      []types.SessionLogoutResult `json:"results"`
	Timestamp    time.Time                   `json:"timestamp"`
}

// validateSessionParams validates single session logout parameters
func (s *Service) validateSessionParams(params ForceLogoutSessionParams) error {
	if params.JTI == "" {
		return fmt.Errorf("jti is required")
	}
	if params.UserID == "" {
		return fmt.Errorf("user_id is required")
	}
	if params.ActorID == "" {
		return fmt.Errorf("actor_id is required")
	}
	if params.ActorUsername == "" {
		return fmt.Errorf("actor_username is required")
	}
	if params.TriggeredBy == "" {
		return fmt.Errorf("triggered_by is required")
	}
	return nil
}

// validateUserParams validates user logout parameters
func (s *Service) validateUserParams(params ForceLogoutUserParams) error {
	if params.UserID == "" {
		return fmt.Errorf("user_id is required")
	}
	if params.ActorID == "" {
		return fmt.Errorf("actor_id is required")
	}
	if params.ActorUsername == "" {
		return fmt.Errorf("actor_username is required")
	}
	if params.TriggeredBy == "" {
		return fmt.Errorf("triggered_by is required")
	}
	return nil
}

// validateBulkParams validates bulk logout parameters
func (s *Service) validateBulkParams(params BulkForceLogoutParams) error {
	if len(params.JTIs) == 0 {
		return fmt.Errorf("at least one JTI is required")
	}
	if len(params.JTIs) > 100 {
		return fmt.Errorf("maximum 100 JTIs allowed per bulk operation")
	}
	if params.ActorID == "" {
		return fmt.Errorf("actor_id is required")
	}
	if params.ActorUsername == "" {
		return fmt.Errorf("actor_username is required")
	}
	if params.TriggeredBy == "" {
		return fmt.Errorf("triggered_by is required")
	}
	return nil
}
