// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/google/wire"
	"github.com/kart-io/k8s-agent/internal/monitor/initializers"
	"github.com/kart-io/k8s-agent/pkg/app"
	initializers2 "github.com/kart-io/k8s-agent/pkg/initializers"
)

// Injectors from wire.go:

// InitializeMonitorComponents automatically injects all components using Wire.
func InitializeMonitorComponents(opts *app.StandardOptions) (*MonitorComponents, error) {
	logger, err := ProvideLogger(opts)
	if err != nil {
		return nil, err
	}
	databaseInitializer := initializers.NewDatabaseInitializer(opts, logger)
	redisInitializer := initializers.NewRedisInitializer(opts, logger)
	httpServerInitializer := initializers.NewHTTPServerInitializer(opts, logger, databaseInitializer, redisInitializer)
	grpcServerInitializer := initializers.NewGRPCServerInitializer(opts, logger, databaseInitializer, redisInitializer)
	healthOptions := opts.Health
	healthCheckInitializer := initializers2.NewHealthCheckInitializer(healthOptions, logger)
	monitorComponents := NewMonitorComponents(databaseInitializer, redisInitializer, httpServerInitializer, grpcServerInitializer, healthCheckInitializer)
	return monitorComponents, nil
}

// wire.go:

// InitializerSet Wire dependency set for all initializers.
var InitializerSet = wire.NewSet(
	ProvideLogger, initializers.NewDatabaseInitializer, initializers.NewRedisInitializer, initializers.NewHTTPServerInitializer, initializers.NewGRPCServerInitializer,
)

// HealthInitializerSet Wire dependency set for health check.
var HealthInitializerSet = wire.NewSet(initializers2.NewHealthCheckInitializer, wire.FieldsOf(new(*app.StandardOptions), "Health"))
