// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/kart-io/k8s-agent/internal/monitor/initializers"
	"github.com/kart-io/k8s-agent/pkg/app"
	initializers2 "github.com/kart-io/k8s-agent/pkg/initializers"
)

// Injectors from wire.go:

// InitializeMonitorContainer automatically injects all components using Wire.
// Simplified: flat provider list without nested sets.
func InitializeMonitorContainer(opts *app.StandardOptions) (*MonitorContainer, error) {
	logger, err := ProvideLogger(opts)
	if err != nil {
		return nil, err
	}
	databaseInitializer := initializers.NewDatabaseInitializer(opts, logger)
	redisInitializer := initializers.NewRedisInitializer(opts, logger)
	httpServerInitializer := initializers.NewHTTPServerInitializer(opts, logger, databaseInitializer, redisInitializer)
	grpcServerInitializer := initializers.NewGRPCServerInitializer(opts, logger, databaseInitializer, redisInitializer)
	healthOptions := opts.Health
	healthCheckInitializer := initializers2.NewHealthCheckInitializer(healthOptions, logger)
	monitorContainer := NewMonitorContainer(databaseInitializer, redisInitializer, httpServerInitializer, grpcServerInitializer, healthCheckInitializer)
	return monitorContainer, nil
}
