// reasoning/analysis.proto
// Reasoning Service AI 分析 API 定义

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: reasoning/v1/analysis.proto

package reasoningv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 分析深度
type AnalysisOptions_Depth int32

const (
	AnalysisOptions_DEPTH_UNSPECIFIED AnalysisOptions_Depth = 0
	AnalysisOptions_SHALLOW           AnalysisOptions_Depth = 1 // 浅层分析
	AnalysisOptions_MEDIUM            AnalysisOptions_Depth = 2 // 中等深度
	AnalysisOptions_DEEP              AnalysisOptions_Depth = 3 // 深度分析
)

// Enum value maps for AnalysisOptions_Depth.
var (
	AnalysisOptions_Depth_name = map[int32]string{
		0: "DEPTH_UNSPECIFIED",
		1: "SHALLOW",
		2: "MEDIUM",
		3: "DEEP",
	}
	AnalysisOptions_Depth_value = map[string]int32{
		"DEPTH_UNSPECIFIED": 0,
		"SHALLOW":           1,
		"MEDIUM":            2,
		"DEEP":              3,
	}
)

func (x AnalysisOptions_Depth) Enum() *AnalysisOptions_Depth {
	p := new(AnalysisOptions_Depth)
	*p = x
	return p
}

func (x AnalysisOptions_Depth) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AnalysisOptions_Depth) Descriptor() protoreflect.EnumDescriptor {
	return file_reasoning_v1_analysis_proto_enumTypes[0].Descriptor()
}

func (AnalysisOptions_Depth) Type() protoreflect.EnumType {
	return &file_reasoning_v1_analysis_proto_enumTypes[0]
}

func (x AnalysisOptions_Depth) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AnalysisOptions_Depth.Descriptor instead.
func (AnalysisOptions_Depth) EnumDescriptor() ([]byte, []int) {
	return file_reasoning_v1_analysis_proto_rawDescGZIP(), []int{2, 0}
}

// 根因类型
type RootCause_Type int32

const (
	RootCause_TYPE_UNSPECIFIED    RootCause_Type = 0
	RootCause_RESOURCE_EXHAUSTION RootCause_Type = 1  // 资源耗尽
	RootCause_CONFIGURATION_ERROR RootCause_Type = 2  // 配置错误
	RootCause_NETWORK_ISSUE       RootCause_Type = 3  // 网络问题
	RootCause_PERMISSION_DENIED   RootCause_Type = 4  // 权限问题
	RootCause_IMAGE_PULL_ERROR    RootCause_Type = 5  // 镜像拉取错误
	RootCause_CRASH_LOOP          RootCause_Type = 6  // 崩溃循环
	RootCause_DEPENDENCY_FAILURE  RootCause_Type = 7  // 依赖失败
	RootCause_UNKNOWN             RootCause_Type = 99 // 未知
)

// Enum value maps for RootCause_Type.
var (
	RootCause_Type_name = map[int32]string{
		0:  "TYPE_UNSPECIFIED",
		1:  "RESOURCE_EXHAUSTION",
		2:  "CONFIGURATION_ERROR",
		3:  "NETWORK_ISSUE",
		4:  "PERMISSION_DENIED",
		5:  "IMAGE_PULL_ERROR",
		6:  "CRASH_LOOP",
		7:  "DEPENDENCY_FAILURE",
		99: "UNKNOWN",
	}
	RootCause_Type_value = map[string]int32{
		"TYPE_UNSPECIFIED":    0,
		"RESOURCE_EXHAUSTION": 1,
		"CONFIGURATION_ERROR": 2,
		"NETWORK_ISSUE":       3,
		"PERMISSION_DENIED":   4,
		"IMAGE_PULL_ERROR":    5,
		"CRASH_LOOP":          6,
		"DEPENDENCY_FAILURE":  7,
		"UNKNOWN":             99,
	}
)

func (x RootCause_Type) Enum() *RootCause_Type {
	p := new(RootCause_Type)
	*p = x
	return p
}

func (x RootCause_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RootCause_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_reasoning_v1_analysis_proto_enumTypes[1].Descriptor()
}

func (RootCause_Type) Type() protoreflect.EnumType {
	return &file_reasoning_v1_analysis_proto_enumTypes[1]
}

func (x RootCause_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RootCause_Type.Descriptor instead.
func (RootCause_Type) EnumDescriptor() ([]byte, []int) {
	return file_reasoning_v1_analysis_proto_rawDescGZIP(), []int{4, 0}
}

// 证据类型
type Evidence_Type int32

const (
	Evidence_TYPE_UNSPECIFIED Evidence_Type = 0
	Evidence_EVENT            Evidence_Type = 1 // 事件
	Evidence_LOG              Evidence_Type = 2 // 日志
	Evidence_METRIC           Evidence_Type = 3 // 指标
	Evidence_RESOURCE_STATE   Evidence_Type = 4 // 资源状态
)

// Enum value maps for Evidence_Type.
var (
	Evidence_Type_name = map[int32]string{
		0: "TYPE_UNSPECIFIED",
		1: "EVENT",
		2: "LOG",
		3: "METRIC",
		4: "RESOURCE_STATE",
	}
	Evidence_Type_value = map[string]int32{
		"TYPE_UNSPECIFIED": 0,
		"EVENT":            1,
		"LOG":              2,
		"METRIC":           3,
		"RESOURCE_STATE":   4,
	}
)

func (x Evidence_Type) Enum() *Evidence_Type {
	p := new(Evidence_Type)
	*p = x
	return p
}

func (x Evidence_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Evidence_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_reasoning_v1_analysis_proto_enumTypes[2].Descriptor()
}

func (Evidence_Type) Type() protoreflect.EnumType {
	return &file_reasoning_v1_analysis_proto_enumTypes[2]
}

func (x Evidence_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Evidence_Type.Descriptor instead.
func (Evidence_Type) EnumDescriptor() ([]byte, []int) {
	return file_reasoning_v1_analysis_proto_rawDescGZIP(), []int{5, 0}
}

// 建议类型
type Recommendation_Type int32

const (
	Recommendation_TYPE_UNSPECIFIED Recommendation_Type = 0
	Recommendation_MANUAL           Recommendation_Type = 1 // 手动修复
	Recommendation_AUTOMATED        Recommendation_Type = 2 // 自动修复
	Recommendation_PREVENTIVE       Recommendation_Type = 3 // 预防性措施
)

// Enum value maps for Recommendation_Type.
var (
	Recommendation_Type_name = map[int32]string{
		0: "TYPE_UNSPECIFIED",
		1: "MANUAL",
		2: "AUTOMATED",
		3: "PREVENTIVE",
	}
	Recommendation_Type_value = map[string]int32{
		"TYPE_UNSPECIFIED": 0,
		"MANUAL":           1,
		"AUTOMATED":        2,
		"PREVENTIVE":       3,
	}
)

func (x Recommendation_Type) Enum() *Recommendation_Type {
	p := new(Recommendation_Type)
	*p = x
	return p
}

func (x Recommendation_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Recommendation_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_reasoning_v1_analysis_proto_enumTypes[3].Descriptor()
}

func (Recommendation_Type) Type() protoreflect.EnumType {
	return &file_reasoning_v1_analysis_proto_enumTypes[3]
}

func (x Recommendation_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Recommendation_Type.Descriptor instead.
func (Recommendation_Type) EnumDescriptor() ([]byte, []int) {
	return file_reasoning_v1_analysis_proto_rawDescGZIP(), []int{6, 0}
}

// 解决结果
type SaveCaseRequest_Result int32

const (
	SaveCaseRequest_RESULT_UNSPECIFIED   SaveCaseRequest_Result = 0
	SaveCaseRequest_SUCCESSFUL           SaveCaseRequest_Result = 1 // 成功
	SaveCaseRequest_PARTIALLY_SUCCESSFUL SaveCaseRequest_Result = 2 // 部分成功
	SaveCaseRequest_FAILED               SaveCaseRequest_Result = 3 // 失败
)

// Enum value maps for SaveCaseRequest_Result.
var (
	SaveCaseRequest_Result_name = map[int32]string{
		0: "RESULT_UNSPECIFIED",
		1: "SUCCESSFUL",
		2: "PARTIALLY_SUCCESSFUL",
		3: "FAILED",
	}
	SaveCaseRequest_Result_value = map[string]int32{
		"RESULT_UNSPECIFIED":   0,
		"SUCCESSFUL":           1,
		"PARTIALLY_SUCCESSFUL": 2,
		"FAILED":               3,
	}
)

func (x SaveCaseRequest_Result) Enum() *SaveCaseRequest_Result {
	p := new(SaveCaseRequest_Result)
	*p = x
	return p
}

func (x SaveCaseRequest_Result) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SaveCaseRequest_Result) Descriptor() protoreflect.EnumDescriptor {
	return file_reasoning_v1_analysis_proto_enumTypes[4].Descriptor()
}

func (SaveCaseRequest_Result) Type() protoreflect.EnumType {
	return &file_reasoning_v1_analysis_proto_enumTypes[4]
}

func (x SaveCaseRequest_Result) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SaveCaseRequest_Result.Descriptor instead.
func (SaveCaseRequest_Result) EnumDescriptor() ([]byte, []int) {
	return file_reasoning_v1_analysis_proto_rawDescGZIP(), []int{8, 0}
}

// 根因分析请求
type RootCauseAnalysisRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 事件 ID
	EventId string `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	// 事件描述
	EventDescription string `protobuf:"bytes,2,opt,name=event_description,json=eventDescription,proto3" json:"event_description,omitempty"`
	// 事件上下文（事件、日志、指标等）
	Context *AnalysisContext `protobuf:"bytes,3,opt,name=context,proto3" json:"context,omitempty"`
	// 分析选项
	Options       *AnalysisOptions `protobuf:"bytes,4,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RootCauseAnalysisRequest) Reset() {
	*x = RootCauseAnalysisRequest{}
	mi := &file_reasoning_v1_analysis_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RootCauseAnalysisRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RootCauseAnalysisRequest) ProtoMessage() {}

func (x *RootCauseAnalysisRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reasoning_v1_analysis_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RootCauseAnalysisRequest.ProtoReflect.Descriptor instead.
func (*RootCauseAnalysisRequest) Descriptor() ([]byte, []int) {
	return file_reasoning_v1_analysis_proto_rawDescGZIP(), []int{0}
}

func (x *RootCauseAnalysisRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *RootCauseAnalysisRequest) GetEventDescription() string {
	if x != nil {
		return x.EventDescription
	}
	return ""
}

func (x *RootCauseAnalysisRequest) GetContext() *AnalysisContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *RootCauseAnalysisRequest) GetOptions() *AnalysisOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

// 分析上下文
type AnalysisContext struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// K8s 事件列表
	Events []string `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	// 日志数据
	Logs []string `protobuf:"bytes,2,rep,name=logs,proto3" json:"logs,omitempty"`
	// 指标数据（JSON 格式）
	Metrics *structpb.Struct `protobuf:"bytes,3,opt,name=metrics,proto3" json:"metrics,omitempty"`
	// 资源状态（JSON 格式）
	Resources *structpb.Struct `protobuf:"bytes,4,opt,name=resources,proto3" json:"resources,omitempty"`
	// 历史案例 ID
	RelatedCases  []string `protobuf:"bytes,5,rep,name=related_cases,json=relatedCases,proto3" json:"related_cases,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalysisContext) Reset() {
	*x = AnalysisContext{}
	mi := &file_reasoning_v1_analysis_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalysisContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalysisContext) ProtoMessage() {}

func (x *AnalysisContext) ProtoReflect() protoreflect.Message {
	mi := &file_reasoning_v1_analysis_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalysisContext.ProtoReflect.Descriptor instead.
func (*AnalysisContext) Descriptor() ([]byte, []int) {
	return file_reasoning_v1_analysis_proto_rawDescGZIP(), []int{1}
}

func (x *AnalysisContext) GetEvents() []string {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *AnalysisContext) GetLogs() []string {
	if x != nil {
		return x.Logs
	}
	return nil
}

func (x *AnalysisContext) GetMetrics() *structpb.Struct {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *AnalysisContext) GetResources() *structpb.Struct {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *AnalysisContext) GetRelatedCases() []string {
	if x != nil {
		return x.RelatedCases
	}
	return nil
}

// 分析选项
type AnalysisOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 是否使用知识图谱
	UseKnowledgeGraph bool `protobuf:"varint,1,opt,name=use_knowledge_graph,json=useKnowledgeGraph,proto3" json:"use_knowledge_graph,omitempty"`
	// 是否包含历史案例
	IncludeHistoricalCases bool `protobuf:"varint,2,opt,name=include_historical_cases,json=includeHistoricalCases,proto3" json:"include_historical_cases,omitempty"`
	// AI 模型选择
	Model string                `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	Depth AnalysisOptions_Depth `protobuf:"varint,4,opt,name=depth,proto3,enum=reasoning.v1.AnalysisOptions_Depth" json:"depth,omitempty"`
	// 超时设置（秒）
	Timeout       int32 `protobuf:"varint,5,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalysisOptions) Reset() {
	*x = AnalysisOptions{}
	mi := &file_reasoning_v1_analysis_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalysisOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalysisOptions) ProtoMessage() {}

func (x *AnalysisOptions) ProtoReflect() protoreflect.Message {
	mi := &file_reasoning_v1_analysis_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalysisOptions.ProtoReflect.Descriptor instead.
func (*AnalysisOptions) Descriptor() ([]byte, []int) {
	return file_reasoning_v1_analysis_proto_rawDescGZIP(), []int{2}
}

func (x *AnalysisOptions) GetUseKnowledgeGraph() bool {
	if x != nil {
		return x.UseKnowledgeGraph
	}
	return false
}

func (x *AnalysisOptions) GetIncludeHistoricalCases() bool {
	if x != nil {
		return x.IncludeHistoricalCases
	}
	return false
}

func (x *AnalysisOptions) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *AnalysisOptions) GetDepth() AnalysisOptions_Depth {
	if x != nil {
		return x.Depth
	}
	return AnalysisOptions_DEPTH_UNSPECIFIED
}

func (x *AnalysisOptions) GetTimeout() int32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

// 根因分析响应
type RootCauseAnalysisResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 分析 ID
	AnalysisId string `protobuf:"bytes,1,opt,name=analysis_id,json=analysisId,proto3" json:"analysis_id,omitempty"`
	// 根因分析结果
	RootCause *RootCause `protobuf:"bytes,2,opt,name=root_cause,json=rootCause,proto3" json:"root_cause,omitempty"`
	// 修复建议
	Recommendations []*Recommendation `protobuf:"bytes,3,rep,name=recommendations,proto3" json:"recommendations,omitempty"`
	// 相似历史案例
	SimilarCases []*HistoricalCase `protobuf:"bytes,4,rep,name=similar_cases,json=similarCases,proto3" json:"similar_cases,omitempty"`
	// 分析置信度（0-1）
	Confidence float32 `protobuf:"fixed32,5,opt,name=confidence,proto3" json:"confidence,omitempty"`
	// 分析时长（毫秒）
	DurationMs    int64 `protobuf:"varint,6,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RootCauseAnalysisResponse) Reset() {
	*x = RootCauseAnalysisResponse{}
	mi := &file_reasoning_v1_analysis_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RootCauseAnalysisResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RootCauseAnalysisResponse) ProtoMessage() {}

func (x *RootCauseAnalysisResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reasoning_v1_analysis_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RootCauseAnalysisResponse.ProtoReflect.Descriptor instead.
func (*RootCauseAnalysisResponse) Descriptor() ([]byte, []int) {
	return file_reasoning_v1_analysis_proto_rawDescGZIP(), []int{3}
}

func (x *RootCauseAnalysisResponse) GetAnalysisId() string {
	if x != nil {
		return x.AnalysisId
	}
	return ""
}

func (x *RootCauseAnalysisResponse) GetRootCause() *RootCause {
	if x != nil {
		return x.RootCause
	}
	return nil
}

func (x *RootCauseAnalysisResponse) GetRecommendations() []*Recommendation {
	if x != nil {
		return x.Recommendations
	}
	return nil
}

func (x *RootCauseAnalysisResponse) GetSimilarCases() []*HistoricalCase {
	if x != nil {
		return x.SimilarCases
	}
	return nil
}

func (x *RootCauseAnalysisResponse) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *RootCauseAnalysisResponse) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

// 根因
type RootCause struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  RootCause_Type         `protobuf:"varint,1,opt,name=type,proto3,enum=reasoning.v1.RootCause_Type" json:"type,omitempty"`
	// 根因描述
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// 影响范围
	Impact string `protobuf:"bytes,3,opt,name=impact,proto3" json:"impact,omitempty"`
	// 根因证据
	Evidences []*Evidence `protobuf:"bytes,4,rep,name=evidences,proto3" json:"evidences,omitempty"`
	// 置信度（0-1）
	Confidence    float32 `protobuf:"fixed32,5,opt,name=confidence,proto3" json:"confidence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RootCause) Reset() {
	*x = RootCause{}
	mi := &file_reasoning_v1_analysis_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RootCause) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RootCause) ProtoMessage() {}

func (x *RootCause) ProtoReflect() protoreflect.Message {
	mi := &file_reasoning_v1_analysis_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RootCause.ProtoReflect.Descriptor instead.
func (*RootCause) Descriptor() ([]byte, []int) {
	return file_reasoning_v1_analysis_proto_rawDescGZIP(), []int{4}
}

func (x *RootCause) GetType() RootCause_Type {
	if x != nil {
		return x.Type
	}
	return RootCause_TYPE_UNSPECIFIED
}

func (x *RootCause) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RootCause) GetImpact() string {
	if x != nil {
		return x.Impact
	}
	return ""
}

func (x *RootCause) GetEvidences() []*Evidence {
	if x != nil {
		return x.Evidences
	}
	return nil
}

func (x *RootCause) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

// 证据
type Evidence struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  Evidence_Type          `protobuf:"varint,1,opt,name=type,proto3,enum=reasoning.v1.Evidence_Type" json:"type,omitempty"`
	// 证据内容
	Content string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	// 证据来源
	Source string `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	// 时间戳
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Evidence) Reset() {
	*x = Evidence{}
	mi := &file_reasoning_v1_analysis_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Evidence) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Evidence) ProtoMessage() {}

func (x *Evidence) ProtoReflect() protoreflect.Message {
	mi := &file_reasoning_v1_analysis_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Evidence.ProtoReflect.Descriptor instead.
func (*Evidence) Descriptor() ([]byte, []int) {
	return file_reasoning_v1_analysis_proto_rawDescGZIP(), []int{5}
}

func (x *Evidence) GetType() Evidence_Type {
	if x != nil {
		return x.Type
	}
	return Evidence_TYPE_UNSPECIFIED
}

func (x *Evidence) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Evidence) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Evidence) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// 修复建议
type Recommendation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 建议 ID
	Id   string              `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type Recommendation_Type `protobuf:"varint,2,opt,name=type,proto3,enum=reasoning.v1.Recommendation_Type" json:"type,omitempty"`
	// 建议标题
	Title string `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	// 建议描述
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	// 修复步骤
	Steps []string `protobuf:"bytes,5,rep,name=steps,proto3" json:"steps,omitempty"`
	// 命令示例
	Commands []string `protobuf:"bytes,6,rep,name=commands,proto3" json:"commands,omitempty"`
	// 优先级（1-5，5 最高）
	Priority int32 `protobuf:"varint,7,opt,name=priority,proto3" json:"priority,omitempty"`
	// 预期效果
	ExpectedResult string `protobuf:"bytes,8,opt,name=expected_result,json=expectedResult,proto3" json:"expected_result,omitempty"`
	// 风险评估
	RiskAssessment string `protobuf:"bytes,9,opt,name=risk_assessment,json=riskAssessment,proto3" json:"risk_assessment,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Recommendation) Reset() {
	*x = Recommendation{}
	mi := &file_reasoning_v1_analysis_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Recommendation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Recommendation) ProtoMessage() {}

func (x *Recommendation) ProtoReflect() protoreflect.Message {
	mi := &file_reasoning_v1_analysis_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Recommendation.ProtoReflect.Descriptor instead.
func (*Recommendation) Descriptor() ([]byte, []int) {
	return file_reasoning_v1_analysis_proto_rawDescGZIP(), []int{6}
}

func (x *Recommendation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Recommendation) GetType() Recommendation_Type {
	if x != nil {
		return x.Type
	}
	return Recommendation_TYPE_UNSPECIFIED
}

func (x *Recommendation) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Recommendation) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Recommendation) GetSteps() []string {
	if x != nil {
		return x.Steps
	}
	return nil
}

func (x *Recommendation) GetCommands() []string {
	if x != nil {
		return x.Commands
	}
	return nil
}

func (x *Recommendation) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *Recommendation) GetExpectedResult() string {
	if x != nil {
		return x.ExpectedResult
	}
	return ""
}

func (x *Recommendation) GetRiskAssessment() string {
	if x != nil {
		return x.RiskAssessment
	}
	return ""
}

// 历史案例
type HistoricalCase struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 案例 ID
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// 案例标题
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	// 案例描述
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// 根因
	RootCause *RootCause `protobuf:"bytes,4,opt,name=root_cause,json=rootCause,proto3" json:"root_cause,omitempty"`
	// 解决方案
	Solution string `protobuf:"bytes,5,opt,name=solution,proto3" json:"solution,omitempty"`
	// 相似度（0-1）
	Similarity float32 `protobuf:"fixed32,6,opt,name=similarity,proto3" json:"similarity,omitempty"`
	// 案例发生时间
	OccurredAt    *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoricalCase) Reset() {
	*x = HistoricalCase{}
	mi := &file_reasoning_v1_analysis_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoricalCase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoricalCase) ProtoMessage() {}

func (x *HistoricalCase) ProtoReflect() protoreflect.Message {
	mi := &file_reasoning_v1_analysis_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoricalCase.ProtoReflect.Descriptor instead.
func (*HistoricalCase) Descriptor() ([]byte, []int) {
	return file_reasoning_v1_analysis_proto_rawDescGZIP(), []int{7}
}

func (x *HistoricalCase) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *HistoricalCase) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *HistoricalCase) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *HistoricalCase) GetRootCause() *RootCause {
	if x != nil {
		return x.RootCause
	}
	return nil
}

func (x *HistoricalCase) GetSolution() string {
	if x != nil {
		return x.Solution
	}
	return ""
}

func (x *HistoricalCase) GetSimilarity() float32 {
	if x != nil {
		return x.Similarity
	}
	return 0
}

func (x *HistoricalCase) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

// 保存案例请求
type SaveCaseRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 事件 ID
	EventId string `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	// 分析 ID
	AnalysisId string `protobuf:"bytes,2,opt,name=analysis_id,json=analysisId,proto3" json:"analysis_id,omitempty"`
	// 采用的解决方案
	Solution string                 `protobuf:"bytes,3,opt,name=solution,proto3" json:"solution,omitempty"`
	Result   SaveCaseRequest_Result `protobuf:"varint,4,opt,name=result,proto3,enum=reasoning.v1.SaveCaseRequest_Result" json:"result,omitempty"`
	// 反馈信息
	Feedback      string `protobuf:"bytes,5,opt,name=feedback,proto3" json:"feedback,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveCaseRequest) Reset() {
	*x = SaveCaseRequest{}
	mi := &file_reasoning_v1_analysis_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveCaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveCaseRequest) ProtoMessage() {}

func (x *SaveCaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reasoning_v1_analysis_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveCaseRequest.ProtoReflect.Descriptor instead.
func (*SaveCaseRequest) Descriptor() ([]byte, []int) {
	return file_reasoning_v1_analysis_proto_rawDescGZIP(), []int{8}
}

func (x *SaveCaseRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *SaveCaseRequest) GetAnalysisId() string {
	if x != nil {
		return x.AnalysisId
	}
	return ""
}

func (x *SaveCaseRequest) GetSolution() string {
	if x != nil {
		return x.Solution
	}
	return ""
}

func (x *SaveCaseRequest) GetResult() SaveCaseRequest_Result {
	if x != nil {
		return x.Result
	}
	return SaveCaseRequest_RESULT_UNSPECIFIED
}

func (x *SaveCaseRequest) GetFeedback() string {
	if x != nil {
		return x.Feedback
	}
	return ""
}

// 保存案例响应
type SaveCaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CaseId        string                 `protobuf:"bytes,1,opt,name=case_id,json=caseId,proto3" json:"case_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveCaseResponse) Reset() {
	*x = SaveCaseResponse{}
	mi := &file_reasoning_v1_analysis_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveCaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveCaseResponse) ProtoMessage() {}

func (x *SaveCaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reasoning_v1_analysis_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveCaseResponse.ProtoReflect.Descriptor instead.
func (*SaveCaseResponse) Descriptor() ([]byte, []int) {
	return file_reasoning_v1_analysis_proto_rawDescGZIP(), []int{9}
}

func (x *SaveCaseResponse) GetCaseId() string {
	if x != nil {
		return x.CaseId
	}
	return ""
}

func (x *SaveCaseResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_reasoning_v1_analysis_proto protoreflect.FileDescriptor

const file_reasoning_v1_analysis_proto_rawDesc = "" +
	"\n" +
	"\x1breasoning/v1/analysis.proto\x12\freasoning.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xd4\x01\n" +
	"\x18RootCauseAnalysisRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12+\n" +
	"\x11event_description\x18\x02 \x01(\tR\x10eventDescription\x127\n" +
	"\acontext\x18\x03 \x01(\v2\x1d.reasoning.v1.AnalysisContextR\acontext\x127\n" +
	"\aoptions\x18\x04 \x01(\v2\x1d.reasoning.v1.AnalysisOptionsR\aoptions\"\xcc\x01\n" +
	"\x0fAnalysisContext\x12\x16\n" +
	"\x06events\x18\x01 \x03(\tR\x06events\x12\x12\n" +
	"\x04logs\x18\x02 \x03(\tR\x04logs\x121\n" +
	"\ametrics\x18\x03 \x01(\v2\x17.google.protobuf.StructR\ametrics\x125\n" +
	"\tresources\x18\x04 \x01(\v2\x17.google.protobuf.StructR\tresources\x12#\n" +
	"\rrelated_cases\x18\x05 \x03(\tR\frelatedCases\"\xa9\x02\n" +
	"\x0fAnalysisOptions\x12.\n" +
	"\x13use_knowledge_graph\x18\x01 \x01(\bR\x11useKnowledgeGraph\x128\n" +
	"\x18include_historical_cases\x18\x02 \x01(\bR\x16includeHistoricalCases\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x129\n" +
	"\x05depth\x18\x04 \x01(\x0e2#.reasoning.v1.AnalysisOptions.DepthR\x05depth\x12\x18\n" +
	"\atimeout\x18\x05 \x01(\x05R\atimeout\"A\n" +
	"\x05Depth\x12\x15\n" +
	"\x11DEPTH_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aSHALLOW\x10\x01\x12\n" +
	"\n" +
	"\x06MEDIUM\x10\x02\x12\b\n" +
	"\x04DEEP\x10\x03\"\xc0\x02\n" +
	"\x19RootCauseAnalysisResponse\x12\x1f\n" +
	"\vanalysis_id\x18\x01 \x01(\tR\n" +
	"analysisId\x126\n" +
	"\n" +
	"root_cause\x18\x02 \x01(\v2\x17.reasoning.v1.RootCauseR\trootCause\x12F\n" +
	"\x0frecommendations\x18\x03 \x03(\v2\x1c.reasoning.v1.RecommendationR\x0frecommendations\x12A\n" +
	"\rsimilar_cases\x18\x04 \x03(\v2\x1c.reasoning.v1.HistoricalCaseR\fsimilarCases\x12\x1e\n" +
	"\n" +
	"confidence\x18\x05 \x01(\x02R\n" +
	"confidence\x12\x1f\n" +
	"\vduration_ms\x18\x06 \x01(\x03R\n" +
	"durationMs\"\x93\x03\n" +
	"\tRootCause\x120\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1c.reasoning.v1.RootCause.TypeR\x04type\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x16\n" +
	"\x06impact\x18\x03 \x01(\tR\x06impact\x124\n" +
	"\tevidences\x18\x04 \x03(\v2\x16.reasoning.v1.EvidenceR\tevidences\x12\x1e\n" +
	"\n" +
	"confidence\x18\x05 \x01(\x02R\n" +
	"confidence\"\xc3\x01\n" +
	"\x04Type\x12\x14\n" +
	"\x10TYPE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13RESOURCE_EXHAUSTION\x10\x01\x12\x17\n" +
	"\x13CONFIGURATION_ERROR\x10\x02\x12\x11\n" +
	"\rNETWORK_ISSUE\x10\x03\x12\x15\n" +
	"\x11PERMISSION_DENIED\x10\x04\x12\x14\n" +
	"\x10IMAGE_PULL_ERROR\x10\x05\x12\x0e\n" +
	"\n" +
	"CRASH_LOOP\x10\x06\x12\x16\n" +
	"\x12DEPENDENCY_FAILURE\x10\a\x12\v\n" +
	"\aUNKNOWN\x10c\"\xf9\x01\n" +
	"\bEvidence\x12/\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1b.reasoning.v1.Evidence.TypeR\x04type\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"P\n" +
	"\x04Type\x12\x14\n" +
	"\x10TYPE_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05EVENT\x10\x01\x12\a\n" +
	"\x03LOG\x10\x02\x12\n" +
	"\n" +
	"\x06METRIC\x10\x03\x12\x12\n" +
	"\x0eRESOURCE_STATE\x10\x04\"\xf8\x02\n" +
	"\x0eRecommendation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x125\n" +
	"\x04type\x18\x02 \x01(\x0e2!.reasoning.v1.Recommendation.TypeR\x04type\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x14\n" +
	"\x05steps\x18\x05 \x03(\tR\x05steps\x12\x1a\n" +
	"\bcommands\x18\x06 \x03(\tR\bcommands\x12\x1a\n" +
	"\bpriority\x18\a \x01(\x05R\bpriority\x12'\n" +
	"\x0fexpected_result\x18\b \x01(\tR\x0eexpectedResult\x12'\n" +
	"\x0frisk_assessment\x18\t \x01(\tR\x0eriskAssessment\"G\n" +
	"\x04Type\x12\x14\n" +
	"\x10TYPE_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06MANUAL\x10\x01\x12\r\n" +
	"\tAUTOMATED\x10\x02\x12\x0e\n" +
	"\n" +
	"PREVENTIVE\x10\x03\"\x89\x02\n" +
	"\x0eHistoricalCase\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x126\n" +
	"\n" +
	"root_cause\x18\x04 \x01(\v2\x17.reasoning.v1.RootCauseR\trootCause\x12\x1a\n" +
	"\bsolution\x18\x05 \x01(\tR\bsolution\x12\x1e\n" +
	"\n" +
	"similarity\x18\x06 \x01(\x02R\n" +
	"similarity\x12;\n" +
	"\voccurred_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\"\x9b\x02\n" +
	"\x0fSaveCaseRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1f\n" +
	"\vanalysis_id\x18\x02 \x01(\tR\n" +
	"analysisId\x12\x1a\n" +
	"\bsolution\x18\x03 \x01(\tR\bsolution\x12<\n" +
	"\x06result\x18\x04 \x01(\x0e2$.reasoning.v1.SaveCaseRequest.ResultR\x06result\x12\x1a\n" +
	"\bfeedback\x18\x05 \x01(\tR\bfeedback\"V\n" +
	"\x06Result\x12\x16\n" +
	"\x12RESULT_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"SUCCESSFUL\x10\x01\x12\x18\n" +
	"\x14PARTIALLY_SUCCESSFUL\x10\x02\x12\n" +
	"\n" +
	"\x06FAILED\x10\x03\"E\n" +
	"\x10SaveCaseResponse\x12\x17\n" +
	"\acase_id\x18\x01 \x01(\tR\x06caseId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess2\xc3\x01\n" +
	"\x10ReasoningService\x12d\n" +
	"\x11RootCauseAnalysis\x12&.reasoning.v1.RootCauseAnalysisRequest\x1a'.reasoning.v1.RootCauseAnalysisResponse\x12I\n" +
	"\bSaveCase\x12\x1d.reasoning.v1.SaveCaseRequest\x1a\x1e.reasoning.v1.SaveCaseResponseB\xb1\x01\n" +
	"\x10com.reasoning.v1B\rAnalysisProtoP\x01Z=github.com/kart-io/k8s-agent/pkg/api/reasoning/v1;reasoningv1\xa2\x02\x03RXX\xaa\x02\fReasoning.V1\xca\x02\fReasoning\\V1\xe2\x02\x18Reasoning\\V1\\GPBMetadata\xea\x02\rReasoning::V1b\x06proto3"

var (
	file_reasoning_v1_analysis_proto_rawDescOnce sync.Once
	file_reasoning_v1_analysis_proto_rawDescData []byte
)

func file_reasoning_v1_analysis_proto_rawDescGZIP() []byte {
	file_reasoning_v1_analysis_proto_rawDescOnce.Do(func() {
		file_reasoning_v1_analysis_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_reasoning_v1_analysis_proto_rawDesc), len(file_reasoning_v1_analysis_proto_rawDesc)))
	})
	return file_reasoning_v1_analysis_proto_rawDescData
}

var file_reasoning_v1_analysis_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_reasoning_v1_analysis_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_reasoning_v1_analysis_proto_goTypes = []any{
	(AnalysisOptions_Depth)(0),        // 0: reasoning.v1.AnalysisOptions.Depth
	(RootCause_Type)(0),               // 1: reasoning.v1.RootCause.Type
	(Evidence_Type)(0),                // 2: reasoning.v1.Evidence.Type
	(Recommendation_Type)(0),          // 3: reasoning.v1.Recommendation.Type
	(SaveCaseRequest_Result)(0),       // 4: reasoning.v1.SaveCaseRequest.Result
	(*RootCauseAnalysisRequest)(nil),  // 5: reasoning.v1.RootCauseAnalysisRequest
	(*AnalysisContext)(nil),           // 6: reasoning.v1.AnalysisContext
	(*AnalysisOptions)(nil),           // 7: reasoning.v1.AnalysisOptions
	(*RootCauseAnalysisResponse)(nil), // 8: reasoning.v1.RootCauseAnalysisResponse
	(*RootCause)(nil),                 // 9: reasoning.v1.RootCause
	(*Evidence)(nil),                  // 10: reasoning.v1.Evidence
	(*Recommendation)(nil),            // 11: reasoning.v1.Recommendation
	(*HistoricalCase)(nil),            // 12: reasoning.v1.HistoricalCase
	(*SaveCaseRequest)(nil),           // 13: reasoning.v1.SaveCaseRequest
	(*SaveCaseResponse)(nil),          // 14: reasoning.v1.SaveCaseResponse
	(*structpb.Struct)(nil),           // 15: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil),     // 16: google.protobuf.Timestamp
}
var file_reasoning_v1_analysis_proto_depIdxs = []int32{
	6,  // 0: reasoning.v1.RootCauseAnalysisRequest.context:type_name -> reasoning.v1.AnalysisContext
	7,  // 1: reasoning.v1.RootCauseAnalysisRequest.options:type_name -> reasoning.v1.AnalysisOptions
	15, // 2: reasoning.v1.AnalysisContext.metrics:type_name -> google.protobuf.Struct
	15, // 3: reasoning.v1.AnalysisContext.resources:type_name -> google.protobuf.Struct
	0,  // 4: reasoning.v1.AnalysisOptions.depth:type_name -> reasoning.v1.AnalysisOptions.Depth
	9,  // 5: reasoning.v1.RootCauseAnalysisResponse.root_cause:type_name -> reasoning.v1.RootCause
	11, // 6: reasoning.v1.RootCauseAnalysisResponse.recommendations:type_name -> reasoning.v1.Recommendation
	12, // 7: reasoning.v1.RootCauseAnalysisResponse.similar_cases:type_name -> reasoning.v1.HistoricalCase
	1,  // 8: reasoning.v1.RootCause.type:type_name -> reasoning.v1.RootCause.Type
	10, // 9: reasoning.v1.RootCause.evidences:type_name -> reasoning.v1.Evidence
	2,  // 10: reasoning.v1.Evidence.type:type_name -> reasoning.v1.Evidence.Type
	16, // 11: reasoning.v1.Evidence.timestamp:type_name -> google.protobuf.Timestamp
	3,  // 12: reasoning.v1.Recommendation.type:type_name -> reasoning.v1.Recommendation.Type
	9,  // 13: reasoning.v1.HistoricalCase.root_cause:type_name -> reasoning.v1.RootCause
	16, // 14: reasoning.v1.HistoricalCase.occurred_at:type_name -> google.protobuf.Timestamp
	4,  // 15: reasoning.v1.SaveCaseRequest.result:type_name -> reasoning.v1.SaveCaseRequest.Result
	5,  // 16: reasoning.v1.ReasoningService.RootCauseAnalysis:input_type -> reasoning.v1.RootCauseAnalysisRequest
	13, // 17: reasoning.v1.ReasoningService.SaveCase:input_type -> reasoning.v1.SaveCaseRequest
	8,  // 18: reasoning.v1.ReasoningService.RootCauseAnalysis:output_type -> reasoning.v1.RootCauseAnalysisResponse
	14, // 19: reasoning.v1.ReasoningService.SaveCase:output_type -> reasoning.v1.SaveCaseResponse
	18, // [18:20] is the sub-list for method output_type
	16, // [16:18] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_reasoning_v1_analysis_proto_init() }
func file_reasoning_v1_analysis_proto_init() {
	if File_reasoning_v1_analysis_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_reasoning_v1_analysis_proto_rawDesc), len(file_reasoning_v1_analysis_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_reasoning_v1_analysis_proto_goTypes,
		DependencyIndexes: file_reasoning_v1_analysis_proto_depIdxs,
		EnumInfos:         file_reasoning_v1_analysis_proto_enumTypes,
		MessageInfos:      file_reasoning_v1_analysis_proto_msgTypes,
	}.Build()
	File_reasoning_v1_analysis_proto = out.File
	file_reasoning_v1_analysis_proto_goTypes = nil
	file_reasoning_v1_analysis_proto_depIdxs = nil
}
