// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.8.0
// - protoc             (unknown)
// source: reasoning/v1/analysis.proto

package reasoningv1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationReasoningServiceRootCauseAnalysis = "/reasoning.v1.ReasoningService/RootCauseAnalysis"
const OperationReasoningServiceSaveCase = "/reasoning.v1.ReasoningService/SaveCase"

type ReasoningServiceHTTPServer interface {
	// RootCauseAnalysis 根因分析
	RootCauseAnalysis(context.Context, *RootCauseAnalysisRequest) (*RootCauseAnalysisResponse, error)
	// SaveCase 保存历史案例
	SaveCase(context.Context, *SaveCaseRequest) (*SaveCaseResponse, error)
}

func RegisterReasoningServiceHTTPServer(s *http.Server, srv ReasoningServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/analysis/root-cause", _ReasoningService_RootCauseAnalysis0_HTTP_Handler(srv))
	r.POST("/v1/cases", _ReasoningService_SaveCase0_HTTP_Handler(srv))
}

func _ReasoningService_RootCauseAnalysis0_HTTP_Handler(srv ReasoningServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RootCauseAnalysisRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationReasoningServiceRootCauseAnalysis)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RootCauseAnalysis(ctx, req.(*RootCauseAnalysisRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*RootCauseAnalysisResponse)
		return ctx.Result(200, reply)
	}
}

func _ReasoningService_SaveCase0_HTTP_Handler(srv ReasoningServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SaveCaseRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationReasoningServiceSaveCase)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SaveCase(ctx, req.(*SaveCaseRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SaveCaseResponse)
		return ctx.Result(200, reply)
	}
}

type ReasoningServiceHTTPClient interface {
	RootCauseAnalysis(ctx context.Context, req *RootCauseAnalysisRequest, opts ...http.CallOption) (rsp *RootCauseAnalysisResponse, err error)
	SaveCase(ctx context.Context, req *SaveCaseRequest, opts ...http.CallOption) (rsp *SaveCaseResponse, err error)
}

type ReasoningServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewReasoningServiceHTTPClient(client *http.Client) ReasoningServiceHTTPClient {
	return &ReasoningServiceHTTPClientImpl{client}
}

func (c *ReasoningServiceHTTPClientImpl) RootCauseAnalysis(ctx context.Context, in *RootCauseAnalysisRequest, opts ...http.CallOption) (*RootCauseAnalysisResponse, error) {
	var out RootCauseAnalysisResponse
	pattern := "/v1/analysis/root-cause"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationReasoningServiceRootCauseAnalysis))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ReasoningServiceHTTPClientImpl) SaveCase(ctx context.Context, in *SaveCaseRequest, opts ...http.CallOption) (*SaveCaseResponse, error) {
	var out SaveCaseResponse
	pattern := "/v1/cases"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationReasoningServiceSaveCase))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
