// reasoning/analysis.proto
// Reasoning Service AI 分析 API 定义

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: reasoning/v1/analysis.proto

package reasoningv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ReasoningService_RootCauseAnalysis_FullMethodName = "/reasoning.v1.ReasoningService/RootCauseAnalysis"
	ReasoningService_SaveCase_FullMethodName          = "/reasoning.v1.ReasoningService/SaveCase"
)

// ReasoningServiceClient is the client API for ReasoningService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Reasoning Service 定义
type ReasoningServiceClient interface {
	// 根因分析
	RootCauseAnalysis(ctx context.Context, in *RootCauseAnalysisRequest, opts ...grpc.CallOption) (*RootCauseAnalysisResponse, error)
	// 保存历史案例
	SaveCase(ctx context.Context, in *SaveCaseRequest, opts ...grpc.CallOption) (*SaveCaseResponse, error)
}

type reasoningServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewReasoningServiceClient(cc grpc.ClientConnInterface) ReasoningServiceClient {
	return &reasoningServiceClient{cc}
}

func (c *reasoningServiceClient) RootCauseAnalysis(ctx context.Context, in *RootCauseAnalysisRequest, opts ...grpc.CallOption) (*RootCauseAnalysisResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RootCauseAnalysisResponse)
	err := c.cc.Invoke(ctx, ReasoningService_RootCauseAnalysis_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reasoningServiceClient) SaveCase(ctx context.Context, in *SaveCaseRequest, opts ...grpc.CallOption) (*SaveCaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveCaseResponse)
	err := c.cc.Invoke(ctx, ReasoningService_SaveCase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReasoningServiceServer is the server API for ReasoningService service.
// All implementations should embed UnimplementedReasoningServiceServer
// for forward compatibility.
//
// Reasoning Service 定义
type ReasoningServiceServer interface {
	// 根因分析
	RootCauseAnalysis(context.Context, *RootCauseAnalysisRequest) (*RootCauseAnalysisResponse, error)
	// 保存历史案例
	SaveCase(context.Context, *SaveCaseRequest) (*SaveCaseResponse, error)
}

// UnimplementedReasoningServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedReasoningServiceServer struct{}

func (UnimplementedReasoningServiceServer) RootCauseAnalysis(context.Context, *RootCauseAnalysisRequest) (*RootCauseAnalysisResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RootCauseAnalysis not implemented")
}
func (UnimplementedReasoningServiceServer) SaveCase(context.Context, *SaveCaseRequest) (*SaveCaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveCase not implemented")
}
func (UnimplementedReasoningServiceServer) testEmbeddedByValue() {}

// UnsafeReasoningServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReasoningServiceServer will
// result in compilation errors.
type UnsafeReasoningServiceServer interface {
	mustEmbedUnimplementedReasoningServiceServer()
}

func RegisterReasoningServiceServer(s grpc.ServiceRegistrar, srv ReasoningServiceServer) {
	// If the following call pancis, it indicates UnimplementedReasoningServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ReasoningService_ServiceDesc, srv)
}

func _ReasoningService_RootCauseAnalysis_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RootCauseAnalysisRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReasoningServiceServer).RootCauseAnalysis(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReasoningService_RootCauseAnalysis_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReasoningServiceServer).RootCauseAnalysis(ctx, req.(*RootCauseAnalysisRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReasoningService_SaveCase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveCaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReasoningServiceServer).SaveCase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReasoningService_SaveCase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReasoningServiceServer).SaveCase(ctx, req.(*SaveCaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ReasoningService_ServiceDesc is the grpc.ServiceDesc for ReasoningService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReasoningService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "reasoning.v1.ReasoningService",
	HandlerType: (*ReasoningServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RootCauseAnalysis",
			Handler:    _ReasoningService_RootCauseAnalysis_Handler,
		},
		{
			MethodName: "SaveCase",
			Handler:    _ReasoningService_SaveCase_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "reasoning/v1/analysis.proto",
}
