// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/kart-io/k8s-agent/cmd/gateway/app/options"
	"github.com/kart-io/k8s-agent/pkg/initializers"
	"github.com/kart-io/logger/core"
)

// Injectors from wire.go:

// InitializeGatewayContainer uses Wire to inject dependencies.
func InitializeGatewayContainer(opts *options.ServerOptions, logger core.Logger) (*GatewayContainer, error) {
	redisInitializer := NewRedisInitializer(opts, logger)
	httpServerInitializer := NewHTTPServerInitializer(opts, logger, redisInitializer)
	healthOptions := opts.Health
	healthCheckInitializer := initializers.NewHealthCheckInitializer(healthOptions, logger)
	gatewayContainer := NewGatewayContainer(redisInitializer, httpServerInitializer, healthCheckInitializer)
	return gatewayContainer, nil
}
