// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/kart-io/k8s-agent/cmd/gateway/app/options"
	"github.com/kart-io/k8s-agent/internal/gateway/initializers"
	pkginitializers "github.com/kart-io/k8s-agent/pkg/initializers"
)

// Injectors from wire.go:

// InitializeGatewayComponents automatically injects all components using Wire.
func InitializeGatewayComponents(opts *options.ServerOptions) (*GatewayComponents, error) {
	logger, err := ProvideLogger(opts)
	if err != nil {
		return nil, err
	}
	redisInitializer := initializers.NewRedisInitializer(opts, logger)
	httpServerInitializer := initializers.NewHTTPServerInitializer(opts, logger, redisInitializer)
	healthOptions := opts.Health
	healthCheckInitializer := pkginitializers.NewHealthCheckInitializer(healthOptions, logger)
	gatewayComponents := NewGatewayComponents(redisInitializer, httpServerInitializer, healthCheckInitializer)
	return gatewayComponents, nil
}


