// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/google/wire"
	"github.com/kart-io/k8s-agent/internal/orchestrator/initializers"
	"github.com/kart-io/k8s-agent/pkg/app"
	initializers2 "github.com/kart-io/k8s-agent/pkg/initializers"
)

// Injectors from wire.go:

// InitializeOrchestratorComponents automatically injects all components using Wire.
func InitializeOrchestratorComponents(opts *app.StandardOptions) (*OrchestratorComponents, error) {
	logger, err := ProvideLogger(opts)
	if err != nil {
		return nil, err
	}
	databaseInitializer := initializers.NewDatabaseInitializer(opts, logger)
	redisInitializer := initializers.NewRedisInitializer(opts, logger)
	natsInitializer := initializers.NewNATSInitializer(opts, logger)
	workflowInitializer := initializers.NewWorkflowInitializer(opts, logger, databaseInitializer, redisInitializer)
	strategyInitializer := initializers.NewStrategyInitializer(opts, logger, databaseInitializer, workflowInitializer)
	subscriberInitializer := initializers.NewSubscriberInitializer(opts, logger, natsInitializer, strategyInitializer)
	grpcServerInitializer := initializers.NewGRPCServerInitializer(opts, logger, workflowInitializer, databaseInitializer)
	httpServerInitializer := initializers.NewHTTPServerInitializer(opts, logger, grpcServerInitializer)
	healthOptions := opts.Health
	healthCheckInitializer := initializers2.NewHealthCheckInitializer(healthOptions, logger)
	orchestratorComponents := NewOrchestratorComponents(databaseInitializer, redisInitializer, natsInitializer, workflowInitializer, strategyInitializer, subscriberInitializer, grpcServerInitializer, httpServerInitializer, healthCheckInitializer)
	return orchestratorComponents, nil
}

// wire.go:

// BaseProviderSet Wire dependency set for base infrastructure.
var BaseProviderSet = wire.NewSet(
	ProvideLogger, initializers.NewDatabaseInitializer, initializers.NewRedisInitializer, initializers.NewNATSInitializer,
)

// BusinessProviderSet Wire dependency set for business logic.
var BusinessProviderSet = wire.NewSet(
	BaseProviderSet, initializers.NewWorkflowInitializer, initializers.NewStrategyInitializer, initializers.NewSubscriberInitializer,
)

// ServerProviderSet Wire dependency set for servers.
var ServerProviderSet = wire.NewSet(
	BusinessProviderSet, initializers.NewGRPCServerInitializer, initializers.NewHTTPServerInitializer,
)

// HealthProviderSet Wire dependency set for health check.
var HealthProviderSet = wire.NewSet(initializers2.NewHealthCheckInitializer, wire.FieldsOf(new(*app.StandardOptions), "Health"))
