// common/error/v1/error.proto
// 错误处理通用消息定义

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: common/error/v1/error.proto

package errorv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 错误详情
type Error struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 错误代码
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	// 错误原因（机器可读）
	Reason string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	// 错误消息（人类可读）
	Message string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	// 错误元数据
	Metadata map[string]string `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// 错误堆栈（调试用）
	Stack         []string `protobuf:"bytes,5,rep,name=stack,proto3" json:"stack,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_common_error_v1_error_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_common_error_v1_error_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_common_error_v1_error_proto_rawDescGZIP(), []int{0}
}

func (x *Error) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Error) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Error) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Error) GetStack() []string {
	if x != nil {
		return x.Stack
	}
	return nil
}

// 错误响应
type ErrorResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 错误信息
	Error *Error `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	// 请求 ID
	RequestId string `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// 时间戳
	Timestamp     int64 `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorResponse) Reset() {
	*x = ErrorResponse{}
	mi := &file_common_error_v1_error_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponse) ProtoMessage() {}

func (x *ErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_error_v1_error_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResponse.ProtoReflect.Descriptor instead.
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return file_common_error_v1_error_proto_rawDescGZIP(), []int{1}
}

func (x *ErrorResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *ErrorResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ErrorResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_common_error_v1_error_proto protoreflect.FileDescriptor

const file_common_error_v1_error_proto_rawDesc = "" +
	"\n" +
	"\x1bcommon/error/v1/error.proto\x12\x0fcommon.error.v1\"\xe2\x01\n" +
	"\x05Error\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12@\n" +
	"\bmetadata\x18\x04 \x03(\v2$.common.error.v1.Error.MetadataEntryR\bmetadata\x12\x14\n" +
	"\x05stack\x18\x05 \x03(\tR\x05stack\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"z\n" +
	"\rErrorResponse\x12,\n" +
	"\x05error\x18\x01 \x01(\v2\x16.common.error.v1.ErrorR\x05error\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestampB\xbf\x01\n" +
	"\x13com.common.error.v1B\n" +
	"ErrorProtoP\x01Z<github.com/kart-io/k8s-agent/pkg/api/common/error/v1;errorv1\xa2\x02\x03CEX\xaa\x02\x0fCommon.Error.V1\xca\x02\x10Common\\Error_\\V1\xe2\x02\x1cCommon\\Error_\\V1\\GPBMetadata\xea\x02\x11Common::Error::V1b\x06proto3"

var (
	file_common_error_v1_error_proto_rawDescOnce sync.Once
	file_common_error_v1_error_proto_rawDescData []byte
)

func file_common_error_v1_error_proto_rawDescGZIP() []byte {
	file_common_error_v1_error_proto_rawDescOnce.Do(func() {
		file_common_error_v1_error_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_error_v1_error_proto_rawDesc), len(file_common_error_v1_error_proto_rawDesc)))
	})
	return file_common_error_v1_error_proto_rawDescData
}

var file_common_error_v1_error_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_common_error_v1_error_proto_goTypes = []any{
	(*Error)(nil),         // 0: common.error.v1.Error
	(*ErrorResponse)(nil), // 1: common.error.v1.ErrorResponse
	nil,                   // 2: common.error.v1.Error.MetadataEntry
}
var file_common_error_v1_error_proto_depIdxs = []int32{
	2, // 0: common.error.v1.Error.metadata:type_name -> common.error.v1.Error.MetadataEntry
	0, // 1: common.error.v1.ErrorResponse.error:type_name -> common.error.v1.Error
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_common_error_v1_error_proto_init() }
func file_common_error_v1_error_proto_init() {
	if File_common_error_v1_error_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_error_v1_error_proto_rawDesc), len(file_common_error_v1_error_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_error_v1_error_proto_goTypes,
		DependencyIndexes: file_common_error_v1_error_proto_depIdxs,
		MessageInfos:      file_common_error_v1_error_proto_msgTypes,
	}.Build()
	File_common_error_v1_error_proto = out.File
	file_common_error_v1_error_proto_goTypes = nil
	file_common_error_v1_error_proto_depIdxs = nil
}
