// orchestrator/workflow.proto
// Orchestrator 工作流 API 定义

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: orchestrator/v1/workflow.proto

package orchestratorv1

import (
	v1 "github.com/kart-io/k8s-agent/pkg/api/common/pagination/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 工作流状态
type Workflow_Status int32

const (
	Workflow_STATUS_UNSPECIFIED Workflow_Status = 0
	Workflow_DRAFT              Workflow_Status = 1 // 草稿
	Workflow_ACTIVE             Workflow_Status = 2 // 激活
	Workflow_INACTIVE           Workflow_Status = 3 // 停用
	Workflow_ARCHIVED           Workflow_Status = 4 // 归档
)

// Enum value maps for Workflow_Status.
var (
	Workflow_Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "DRAFT",
		2: "ACTIVE",
		3: "INACTIVE",
		4: "ARCHIVED",
	}
	Workflow_Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"DRAFT":              1,
		"ACTIVE":             2,
		"INACTIVE":           3,
		"ARCHIVED":           4,
	}
)

func (x Workflow_Status) Enum() *Workflow_Status {
	p := new(Workflow_Status)
	*p = x
	return p
}

func (x Workflow_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Workflow_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_orchestrator_v1_workflow_proto_enumTypes[0].Descriptor()
}

func (Workflow_Status) Type() protoreflect.EnumType {
	return &file_orchestrator_v1_workflow_proto_enumTypes[0]
}

func (x Workflow_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Workflow_Status.Descriptor instead.
func (Workflow_Status) EnumDescriptor() ([]byte, []int) {
	return file_orchestrator_v1_workflow_proto_rawDescGZIP(), []int{0, 0}
}

// 步骤类型
type WorkflowStep_Type int32

const (
	WorkflowStep_TYPE_UNSPECIFIED WorkflowStep_Type = 0
	WorkflowStep_COMMAND          WorkflowStep_Type = 1 // 命令执行
	WorkflowStep_AI_ANALYSIS      WorkflowStep_Type = 2 // AI 分析
	WorkflowStep_DECISION         WorkflowStep_Type = 3 // 决策分支
	WorkflowStep_REMEDIATION      WorkflowStep_Type = 4 // 修复操作
	WorkflowStep_NOTIFICATION     WorkflowStep_Type = 5 // 通知
	WorkflowStep_WAIT             WorkflowStep_Type = 6 // 等待
)

// Enum value maps for WorkflowStep_Type.
var (
	WorkflowStep_Type_name = map[int32]string{
		0: "TYPE_UNSPECIFIED",
		1: "COMMAND",
		2: "AI_ANALYSIS",
		3: "DECISION",
		4: "REMEDIATION",
		5: "NOTIFICATION",
		6: "WAIT",
	}
	WorkflowStep_Type_value = map[string]int32{
		"TYPE_UNSPECIFIED": 0,
		"COMMAND":          1,
		"AI_ANALYSIS":      2,
		"DECISION":         3,
		"REMEDIATION":      4,
		"NOTIFICATION":     5,
		"WAIT":             6,
	}
)

func (x WorkflowStep_Type) Enum() *WorkflowStep_Type {
	p := new(WorkflowStep_Type)
	*p = x
	return p
}

func (x WorkflowStep_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkflowStep_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_orchestrator_v1_workflow_proto_enumTypes[1].Descriptor()
}

func (WorkflowStep_Type) Type() protoreflect.EnumType {
	return &file_orchestrator_v1_workflow_proto_enumTypes[1]
}

func (x WorkflowStep_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkflowStep_Type.Descriptor instead.
func (WorkflowStep_Type) EnumDescriptor() ([]byte, []int) {
	return file_orchestrator_v1_workflow_proto_rawDescGZIP(), []int{1, 0}
}

// 执行状态
type WorkflowExecution_Status int32

const (
	WorkflowExecution_STATUS_UNSPECIFIED WorkflowExecution_Status = 0
	WorkflowExecution_PENDING            WorkflowExecution_Status = 1 // 待执行
	WorkflowExecution_RUNNING            WorkflowExecution_Status = 2 // 执行中
	WorkflowExecution_SUCCESS            WorkflowExecution_Status = 3 // 成功
	WorkflowExecution_FAILED             WorkflowExecution_Status = 4 // 失败
	WorkflowExecution_CANCELLED          WorkflowExecution_Status = 5 // 已取消
	WorkflowExecution_TIMEOUT            WorkflowExecution_Status = 6 // 超时
)

// Enum value maps for WorkflowExecution_Status.
var (
	WorkflowExecution_Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "PENDING",
		2: "RUNNING",
		3: "SUCCESS",
		4: "FAILED",
		5: "CANCELLED",
		6: "TIMEOUT",
	}
	WorkflowExecution_Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"PENDING":            1,
		"RUNNING":            2,
		"SUCCESS":            3,
		"FAILED":             4,
		"CANCELLED":          5,
		"TIMEOUT":            6,
	}
)

func (x WorkflowExecution_Status) Enum() *WorkflowExecution_Status {
	p := new(WorkflowExecution_Status)
	*p = x
	return p
}

func (x WorkflowExecution_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkflowExecution_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_orchestrator_v1_workflow_proto_enumTypes[2].Descriptor()
}

func (WorkflowExecution_Status) Type() protoreflect.EnumType {
	return &file_orchestrator_v1_workflow_proto_enumTypes[2]
}

func (x WorkflowExecution_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkflowExecution_Status.Descriptor instead.
func (WorkflowExecution_Status) EnumDescriptor() ([]byte, []int) {
	return file_orchestrator_v1_workflow_proto_rawDescGZIP(), []int{2, 0}
}

// 工作流定义
type Workflow struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 工作流 ID
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// 工作流名称
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// 工作流描述
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// 工作流版本
	Version string `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	// 工作流步骤
	Steps  []*WorkflowStep `protobuf:"bytes,5,rep,name=steps,proto3" json:"steps,omitempty"`
	Status Workflow_Status `protobuf:"varint,6,opt,name=status,proto3,enum=orchestrator.v1.Workflow_Status" json:"status,omitempty"`
	// 创建时间
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// 更新时间
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// 元数据
	Metadata      map[string]string `protobuf:"bytes,9,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Workflow) Reset() {
	*x = Workflow{}
	mi := &file_orchestrator_v1_workflow_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Workflow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Workflow) ProtoMessage() {}

func (x *Workflow) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_v1_workflow_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Workflow.ProtoReflect.Descriptor instead.
func (*Workflow) Descriptor() ([]byte, []int) {
	return file_orchestrator_v1_workflow_proto_rawDescGZIP(), []int{0}
}

func (x *Workflow) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Workflow) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Workflow) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Workflow) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Workflow) GetSteps() []*WorkflowStep {
	if x != nil {
		return x.Steps
	}
	return nil
}

func (x *Workflow) GetStatus() Workflow_Status {
	if x != nil {
		return x.Status
	}
	return Workflow_STATUS_UNSPECIFIED
}

func (x *Workflow) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Workflow) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Workflow) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// 工作流步骤
type WorkflowStep struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 步骤 ID
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// 步骤名称
	Name string            `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type WorkflowStep_Type `protobuf:"varint,3,opt,name=type,proto3,enum=orchestrator.v1.WorkflowStep_Type" json:"type,omitempty"`
	// 步骤配置（JSON 格式）
	Config *structpb.Struct `protobuf:"bytes,4,opt,name=config,proto3" json:"config,omitempty"`
	// 下一步骤 ID
	NextSteps []string `protobuf:"bytes,5,rep,name=next_steps,json=nextSteps,proto3" json:"next_steps,omitempty"`
	// 条件表达式
	Condition string `protobuf:"bytes,6,opt,name=condition,proto3" json:"condition,omitempty"`
	// 超时设置（秒）
	Timeout int32 `protobuf:"varint,7,opt,name=timeout,proto3" json:"timeout,omitempty"`
	// 重试次数
	RetryCount    int32 `protobuf:"varint,8,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowStep) Reset() {
	*x = WorkflowStep{}
	mi := &file_orchestrator_v1_workflow_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowStep) ProtoMessage() {}

func (x *WorkflowStep) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_v1_workflow_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowStep.ProtoReflect.Descriptor instead.
func (*WorkflowStep) Descriptor() ([]byte, []int) {
	return file_orchestrator_v1_workflow_proto_rawDescGZIP(), []int{1}
}

func (x *WorkflowStep) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WorkflowStep) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WorkflowStep) GetType() WorkflowStep_Type {
	if x != nil {
		return x.Type
	}
	return WorkflowStep_TYPE_UNSPECIFIED
}

func (x *WorkflowStep) GetConfig() *structpb.Struct {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *WorkflowStep) GetNextSteps() []string {
	if x != nil {
		return x.NextSteps
	}
	return nil
}

func (x *WorkflowStep) GetCondition() string {
	if x != nil {
		return x.Condition
	}
	return ""
}

func (x *WorkflowStep) GetTimeout() int32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *WorkflowStep) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

// 工作流执行
type WorkflowExecution struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 执行 ID
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// 工作流 ID
	WorkflowId string `protobuf:"bytes,2,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	// 触发事件 ID
	EventId string                   `protobuf:"bytes,3,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Status  WorkflowExecution_Status `protobuf:"varint,4,opt,name=status,proto3,enum=orchestrator.v1.WorkflowExecution_Status" json:"status,omitempty"`
	// 当前步骤
	CurrentStep string `protobuf:"bytes,5,opt,name=current_step,json=currentStep,proto3" json:"current_step,omitempty"`
	// 执行上下文
	Context *structpb.Struct `protobuf:"bytes,6,opt,name=context,proto3" json:"context,omitempty"`
	// 执行结果
	Result string `protobuf:"bytes,7,opt,name=result,proto3" json:"result,omitempty"`
	// 错误信息
	Error string `protobuf:"bytes,8,opt,name=error,proto3" json:"error,omitempty"`
	// 开始时间
	StartedAt *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	// 完成时间
	CompletedAt   *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowExecution) Reset() {
	*x = WorkflowExecution{}
	mi := &file_orchestrator_v1_workflow_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowExecution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowExecution) ProtoMessage() {}

func (x *WorkflowExecution) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_v1_workflow_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowExecution.ProtoReflect.Descriptor instead.
func (*WorkflowExecution) Descriptor() ([]byte, []int) {
	return file_orchestrator_v1_workflow_proto_rawDescGZIP(), []int{2}
}

func (x *WorkflowExecution) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WorkflowExecution) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *WorkflowExecution) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *WorkflowExecution) GetStatus() WorkflowExecution_Status {
	if x != nil {
		return x.Status
	}
	return WorkflowExecution_STATUS_UNSPECIFIED
}

func (x *WorkflowExecution) GetCurrentStep() string {
	if x != nil {
		return x.CurrentStep
	}
	return ""
}

func (x *WorkflowExecution) GetContext() *structpb.Struct {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *WorkflowExecution) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *WorkflowExecution) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *WorkflowExecution) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *WorkflowExecution) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

// 创建工作流请求
type CreateWorkflowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Steps         []*WorkflowStep        `protobuf:"bytes,3,rep,name=steps,proto3" json:"steps,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWorkflowRequest) Reset() {
	*x = CreateWorkflowRequest{}
	mi := &file_orchestrator_v1_workflow_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWorkflowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWorkflowRequest) ProtoMessage() {}

func (x *CreateWorkflowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_v1_workflow_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWorkflowRequest.ProtoReflect.Descriptor instead.
func (*CreateWorkflowRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_v1_workflow_proto_rawDescGZIP(), []int{3}
}

func (x *CreateWorkflowRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateWorkflowRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateWorkflowRequest) GetSteps() []*WorkflowStep {
	if x != nil {
		return x.Steps
	}
	return nil
}

func (x *CreateWorkflowRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// 创建工作流响应
type CreateWorkflowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workflow      *Workflow              `protobuf:"bytes,1,opt,name=workflow,proto3" json:"workflow,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWorkflowResponse) Reset() {
	*x = CreateWorkflowResponse{}
	mi := &file_orchestrator_v1_workflow_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWorkflowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWorkflowResponse) ProtoMessage() {}

func (x *CreateWorkflowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_v1_workflow_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWorkflowResponse.ProtoReflect.Descriptor instead.
func (*CreateWorkflowResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_v1_workflow_proto_rawDescGZIP(), []int{4}
}

func (x *CreateWorkflowResponse) GetWorkflow() *Workflow {
	if x != nil {
		return x.Workflow
	}
	return nil
}

// 获取工作流请求
type GetWorkflowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId    string                 `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkflowRequest) Reset() {
	*x = GetWorkflowRequest{}
	mi := &file_orchestrator_v1_workflow_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkflowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkflowRequest) ProtoMessage() {}

func (x *GetWorkflowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_v1_workflow_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkflowRequest.ProtoReflect.Descriptor instead.
func (*GetWorkflowRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_v1_workflow_proto_rawDescGZIP(), []int{5}
}

func (x *GetWorkflowRequest) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

// 获取工作流响应
type GetWorkflowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workflow      *Workflow              `protobuf:"bytes,1,opt,name=workflow,proto3" json:"workflow,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkflowResponse) Reset() {
	*x = GetWorkflowResponse{}
	mi := &file_orchestrator_v1_workflow_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkflowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkflowResponse) ProtoMessage() {}

func (x *GetWorkflowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_v1_workflow_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkflowResponse.ProtoReflect.Descriptor instead.
func (*GetWorkflowResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_v1_workflow_proto_rawDescGZIP(), []int{6}
}

func (x *GetWorkflowResponse) GetWorkflow() *Workflow {
	if x != nil {
		return x.Workflow
	}
	return nil
}

// 列出工作流请求
type ListWorkflowsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *v1.PaginationRequest  `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Status        Workflow_Status        `protobuf:"varint,2,opt,name=status,proto3,enum=orchestrator.v1.Workflow_Status" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkflowsRequest) Reset() {
	*x = ListWorkflowsRequest{}
	mi := &file_orchestrator_v1_workflow_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkflowsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkflowsRequest) ProtoMessage() {}

func (x *ListWorkflowsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_v1_workflow_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkflowsRequest.ProtoReflect.Descriptor instead.
func (*ListWorkflowsRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_v1_workflow_proto_rawDescGZIP(), []int{7}
}

func (x *ListWorkflowsRequest) GetPagination() *v1.PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListWorkflowsRequest) GetStatus() Workflow_Status {
	if x != nil {
		return x.Status
	}
	return Workflow_STATUS_UNSPECIFIED
}

// 列出工作流响应
type ListWorkflowsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workflows     []*Workflow            `protobuf:"bytes,1,rep,name=workflows,proto3" json:"workflows,omitempty"`
	Pagination    *v1.PaginationMetadata `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkflowsResponse) Reset() {
	*x = ListWorkflowsResponse{}
	mi := &file_orchestrator_v1_workflow_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkflowsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkflowsResponse) ProtoMessage() {}

func (x *ListWorkflowsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_v1_workflow_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkflowsResponse.ProtoReflect.Descriptor instead.
func (*ListWorkflowsResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_v1_workflow_proto_rawDescGZIP(), []int{8}
}

func (x *ListWorkflowsResponse) GetWorkflows() []*Workflow {
	if x != nil {
		return x.Workflows
	}
	return nil
}

func (x *ListWorkflowsResponse) GetPagination() *v1.PaginationMetadata {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// 执行工作流请求
type ExecuteWorkflowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId    string                 `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	EventId       string                 `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Context       *structpb.Struct       `protobuf:"bytes,3,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteWorkflowRequest) Reset() {
	*x = ExecuteWorkflowRequest{}
	mi := &file_orchestrator_v1_workflow_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteWorkflowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteWorkflowRequest) ProtoMessage() {}

func (x *ExecuteWorkflowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_v1_workflow_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteWorkflowRequest.ProtoReflect.Descriptor instead.
func (*ExecuteWorkflowRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_v1_workflow_proto_rawDescGZIP(), []int{9}
}

func (x *ExecuteWorkflowRequest) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *ExecuteWorkflowRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *ExecuteWorkflowRequest) GetContext() *structpb.Struct {
	if x != nil {
		return x.Context
	}
	return nil
}

// 执行工作流响应
type ExecuteWorkflowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Execution     *WorkflowExecution     `protobuf:"bytes,1,opt,name=execution,proto3" json:"execution,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteWorkflowResponse) Reset() {
	*x = ExecuteWorkflowResponse{}
	mi := &file_orchestrator_v1_workflow_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteWorkflowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteWorkflowResponse) ProtoMessage() {}

func (x *ExecuteWorkflowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_v1_workflow_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteWorkflowResponse.ProtoReflect.Descriptor instead.
func (*ExecuteWorkflowResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_v1_workflow_proto_rawDescGZIP(), []int{10}
}

func (x *ExecuteWorkflowResponse) GetExecution() *WorkflowExecution {
	if x != nil {
		return x.Execution
	}
	return nil
}

// 获取执行状态请求
type GetExecutionStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExecutionStatusRequest) Reset() {
	*x = GetExecutionStatusRequest{}
	mi := &file_orchestrator_v1_workflow_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExecutionStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExecutionStatusRequest) ProtoMessage() {}

func (x *GetExecutionStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_v1_workflow_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExecutionStatusRequest.ProtoReflect.Descriptor instead.
func (*GetExecutionStatusRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_v1_workflow_proto_rawDescGZIP(), []int{11}
}

func (x *GetExecutionStatusRequest) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

// 获取执行状态响应
type GetExecutionStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Execution     *WorkflowExecution     `protobuf:"bytes,1,opt,name=execution,proto3" json:"execution,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExecutionStatusResponse) Reset() {
	*x = GetExecutionStatusResponse{}
	mi := &file_orchestrator_v1_workflow_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExecutionStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExecutionStatusResponse) ProtoMessage() {}

func (x *GetExecutionStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_v1_workflow_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExecutionStatusResponse.ProtoReflect.Descriptor instead.
func (*GetExecutionStatusResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_v1_workflow_proto_rawDescGZIP(), []int{12}
}

func (x *GetExecutionStatusResponse) GetExecution() *WorkflowExecution {
	if x != nil {
		return x.Execution
	}
	return nil
}

var File_orchestrator_v1_workflow_proto protoreflect.FileDescriptor

const file_orchestrator_v1_workflow_proto_rawDesc = "" +
	"\n" +
	"\x1eorchestrator/v1/workflow.proto\x12\x0forchestrator.v1\x1a%common/pagination/v1/pagination.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xa6\x04\n" +
	"\bWorkflow\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x123\n" +
	"\x05steps\x18\x05 \x03(\v2\x1d.orchestrator.v1.WorkflowStepR\x05steps\x128\n" +
	"\x06status\x18\x06 \x01(\x0e2 .orchestrator.v1.Workflow.StatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12C\n" +
	"\bmetadata\x18\t \x03(\v2'.orchestrator.v1.Workflow.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"S\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05DRAFT\x10\x01\x12\n" +
	"\n" +
	"\x06ACTIVE\x10\x02\x12\f\n" +
	"\bINACTIVE\x10\x03\x12\f\n" +
	"\bARCHIVED\x10\x04\"\x8a\x03\n" +
	"\fWorkflowStep\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x126\n" +
	"\x04type\x18\x03 \x01(\x0e2\".orchestrator.v1.WorkflowStep.TypeR\x04type\x12/\n" +
	"\x06config\x18\x04 \x01(\v2\x17.google.protobuf.StructR\x06config\x12\x1d\n" +
	"\n" +
	"next_steps\x18\x05 \x03(\tR\tnextSteps\x12\x1c\n" +
	"\tcondition\x18\x06 \x01(\tR\tcondition\x12\x18\n" +
	"\atimeout\x18\a \x01(\x05R\atimeout\x12\x1f\n" +
	"\vretry_count\x18\b \x01(\x05R\n" +
	"retryCount\"u\n" +
	"\x04Type\x12\x14\n" +
	"\x10TYPE_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aCOMMAND\x10\x01\x12\x0f\n" +
	"\vAI_ANALYSIS\x10\x02\x12\f\n" +
	"\bDECISION\x10\x03\x12\x0f\n" +
	"\vREMEDIATION\x10\x04\x12\x10\n" +
	"\fNOTIFICATION\x10\x05\x12\b\n" +
	"\x04WAIT\x10\x06\"\x91\x04\n" +
	"\x11WorkflowExecution\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vworkflow_id\x18\x02 \x01(\tR\n" +
	"workflowId\x12\x19\n" +
	"\bevent_id\x18\x03 \x01(\tR\aeventId\x12A\n" +
	"\x06status\x18\x04 \x01(\x0e2).orchestrator.v1.WorkflowExecution.StatusR\x06status\x12!\n" +
	"\fcurrent_step\x18\x05 \x01(\tR\vcurrentStep\x121\n" +
	"\acontext\x18\x06 \x01(\v2\x17.google.protobuf.StructR\acontext\x12\x16\n" +
	"\x06result\x18\a \x01(\tR\x06result\x12\x14\n" +
	"\x05error\x18\b \x01(\tR\x05error\x129\n" +
	"\n" +
	"started_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12=\n" +
	"\fcompleted_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\"o\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aPENDING\x10\x01\x12\v\n" +
	"\aRUNNING\x10\x02\x12\v\n" +
	"\aSUCCESS\x10\x03\x12\n" +
	"\n" +
	"\x06FAILED\x10\x04\x12\r\n" +
	"\tCANCELLED\x10\x05\x12\v\n" +
	"\aTIMEOUT\x10\x06\"\x91\x02\n" +
	"\x15CreateWorkflowRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x123\n" +
	"\x05steps\x18\x03 \x03(\v2\x1d.orchestrator.v1.WorkflowStepR\x05steps\x12P\n" +
	"\bmetadata\x18\x04 \x03(\v24.orchestrator.v1.CreateWorkflowRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"O\n" +
	"\x16CreateWorkflowResponse\x125\n" +
	"\bworkflow\x18\x01 \x01(\v2\x19.orchestrator.v1.WorkflowR\bworkflow\"5\n" +
	"\x12GetWorkflowRequest\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\"L\n" +
	"\x13GetWorkflowResponse\x125\n" +
	"\bworkflow\x18\x01 \x01(\v2\x19.orchestrator.v1.WorkflowR\bworkflow\"\x99\x01\n" +
	"\x14ListWorkflowsRequest\x12G\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2'.common.pagination.v1.PaginationRequestR\n" +
	"pagination\x128\n" +
	"\x06status\x18\x02 \x01(\x0e2 .orchestrator.v1.Workflow.StatusR\x06status\"\x9a\x01\n" +
	"\x15ListWorkflowsResponse\x127\n" +
	"\tworkflows\x18\x01 \x03(\v2\x19.orchestrator.v1.WorkflowR\tworkflows\x12H\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2(.common.pagination.v1.PaginationMetadataR\n" +
	"pagination\"\x87\x01\n" +
	"\x16ExecuteWorkflowRequest\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\tR\aeventId\x121\n" +
	"\acontext\x18\x03 \x01(\v2\x17.google.protobuf.StructR\acontext\"[\n" +
	"\x17ExecuteWorkflowResponse\x12@\n" +
	"\texecution\x18\x01 \x01(\v2\".orchestrator.v1.WorkflowExecutionR\texecution\">\n" +
	"\x19GetExecutionStatusRequest\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\"^\n" +
	"\x1aGetExecutionStatusResponse\x12@\n" +
	"\texecution\x18\x01 \x01(\v2\".orchestrator.v1.WorkflowExecutionR\texecution2\x83\x04\n" +
	"\x0fWorkflowService\x12a\n" +
	"\x0eCreateWorkflow\x12&.orchestrator.v1.CreateWorkflowRequest\x1a'.orchestrator.v1.CreateWorkflowResponse\x12X\n" +
	"\vGetWorkflow\x12#.orchestrator.v1.GetWorkflowRequest\x1a$.orchestrator.v1.GetWorkflowResponse\x12^\n" +
	"\rListWorkflows\x12%.orchestrator.v1.ListWorkflowsRequest\x1a&.orchestrator.v1.ListWorkflowsResponse\x12d\n" +
	"\x0fExecuteWorkflow\x12'.orchestrator.v1.ExecuteWorkflowRequest\x1a(.orchestrator.v1.ExecuteWorkflowResponse\x12m\n" +
	"\x12GetExecutionStatus\x12*.orchestrator.v1.GetExecutionStatusRequest\x1a+.orchestrator.v1.GetExecutionStatusResponseB\xc6\x01\n" +
	"\x13com.orchestrator.v1B\rWorkflowProtoP\x01ZCgithub.com/kart-io/k8s-agent/pkg/api/orchestrator/v1;orchestratorv1\xa2\x02\x03OXX\xaa\x02\x0fOrchestrator.V1\xca\x02\x0fOrchestrator\\V1\xe2\x02\x1bOrchestrator\\V1\\GPBMetadata\xea\x02\x10Orchestrator::V1b\x06proto3"

var (
	file_orchestrator_v1_workflow_proto_rawDescOnce sync.Once
	file_orchestrator_v1_workflow_proto_rawDescData []byte
)

func file_orchestrator_v1_workflow_proto_rawDescGZIP() []byte {
	file_orchestrator_v1_workflow_proto_rawDescOnce.Do(func() {
		file_orchestrator_v1_workflow_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_orchestrator_v1_workflow_proto_rawDesc), len(file_orchestrator_v1_workflow_proto_rawDesc)))
	})
	return file_orchestrator_v1_workflow_proto_rawDescData
}

var file_orchestrator_v1_workflow_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_orchestrator_v1_workflow_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_orchestrator_v1_workflow_proto_goTypes = []any{
	(Workflow_Status)(0),               // 0: orchestrator.v1.Workflow.Status
	(WorkflowStep_Type)(0),             // 1: orchestrator.v1.WorkflowStep.Type
	(WorkflowExecution_Status)(0),      // 2: orchestrator.v1.WorkflowExecution.Status
	(*Workflow)(nil),                   // 3: orchestrator.v1.Workflow
	(*WorkflowStep)(nil),               // 4: orchestrator.v1.WorkflowStep
	(*WorkflowExecution)(nil),          // 5: orchestrator.v1.WorkflowExecution
	(*CreateWorkflowRequest)(nil),      // 6: orchestrator.v1.CreateWorkflowRequest
	(*CreateWorkflowResponse)(nil),     // 7: orchestrator.v1.CreateWorkflowResponse
	(*GetWorkflowRequest)(nil),         // 8: orchestrator.v1.GetWorkflowRequest
	(*GetWorkflowResponse)(nil),        // 9: orchestrator.v1.GetWorkflowResponse
	(*ListWorkflowsRequest)(nil),       // 10: orchestrator.v1.ListWorkflowsRequest
	(*ListWorkflowsResponse)(nil),      // 11: orchestrator.v1.ListWorkflowsResponse
	(*ExecuteWorkflowRequest)(nil),     // 12: orchestrator.v1.ExecuteWorkflowRequest
	(*ExecuteWorkflowResponse)(nil),    // 13: orchestrator.v1.ExecuteWorkflowResponse
	(*GetExecutionStatusRequest)(nil),  // 14: orchestrator.v1.GetExecutionStatusRequest
	(*GetExecutionStatusResponse)(nil), // 15: orchestrator.v1.GetExecutionStatusResponse
	nil,                                // 16: orchestrator.v1.Workflow.MetadataEntry
	nil,                                // 17: orchestrator.v1.CreateWorkflowRequest.MetadataEntry
	(*timestamppb.Timestamp)(nil),      // 18: google.protobuf.Timestamp
	(*structpb.Struct)(nil),            // 19: google.protobuf.Struct
	(*v1.PaginationRequest)(nil),       // 20: common.pagination.v1.PaginationRequest
	(*v1.PaginationMetadata)(nil),      // 21: common.pagination.v1.PaginationMetadata
}
var file_orchestrator_v1_workflow_proto_depIdxs = []int32{
	4,  // 0: orchestrator.v1.Workflow.steps:type_name -> orchestrator.v1.WorkflowStep
	0,  // 1: orchestrator.v1.Workflow.status:type_name -> orchestrator.v1.Workflow.Status
	18, // 2: orchestrator.v1.Workflow.created_at:type_name -> google.protobuf.Timestamp
	18, // 3: orchestrator.v1.Workflow.updated_at:type_name -> google.protobuf.Timestamp
	16, // 4: orchestrator.v1.Workflow.metadata:type_name -> orchestrator.v1.Workflow.MetadataEntry
	1,  // 5: orchestrator.v1.WorkflowStep.type:type_name -> orchestrator.v1.WorkflowStep.Type
	19, // 6: orchestrator.v1.WorkflowStep.config:type_name -> google.protobuf.Struct
	2,  // 7: orchestrator.v1.WorkflowExecution.status:type_name -> orchestrator.v1.WorkflowExecution.Status
	19, // 8: orchestrator.v1.WorkflowExecution.context:type_name -> google.protobuf.Struct
	18, // 9: orchestrator.v1.WorkflowExecution.started_at:type_name -> google.protobuf.Timestamp
	18, // 10: orchestrator.v1.WorkflowExecution.completed_at:type_name -> google.protobuf.Timestamp
	4,  // 11: orchestrator.v1.CreateWorkflowRequest.steps:type_name -> orchestrator.v1.WorkflowStep
	17, // 12: orchestrator.v1.CreateWorkflowRequest.metadata:type_name -> orchestrator.v1.CreateWorkflowRequest.MetadataEntry
	3,  // 13: orchestrator.v1.CreateWorkflowResponse.workflow:type_name -> orchestrator.v1.Workflow
	3,  // 14: orchestrator.v1.GetWorkflowResponse.workflow:type_name -> orchestrator.v1.Workflow
	20, // 15: orchestrator.v1.ListWorkflowsRequest.pagination:type_name -> common.pagination.v1.PaginationRequest
	0,  // 16: orchestrator.v1.ListWorkflowsRequest.status:type_name -> orchestrator.v1.Workflow.Status
	3,  // 17: orchestrator.v1.ListWorkflowsResponse.workflows:type_name -> orchestrator.v1.Workflow
	21, // 18: orchestrator.v1.ListWorkflowsResponse.pagination:type_name -> common.pagination.v1.PaginationMetadata
	19, // 19: orchestrator.v1.ExecuteWorkflowRequest.context:type_name -> google.protobuf.Struct
	5,  // 20: orchestrator.v1.ExecuteWorkflowResponse.execution:type_name -> orchestrator.v1.WorkflowExecution
	5,  // 21: orchestrator.v1.GetExecutionStatusResponse.execution:type_name -> orchestrator.v1.WorkflowExecution
	6,  // 22: orchestrator.v1.WorkflowService.CreateWorkflow:input_type -> orchestrator.v1.CreateWorkflowRequest
	8,  // 23: orchestrator.v1.WorkflowService.GetWorkflow:input_type -> orchestrator.v1.GetWorkflowRequest
	10, // 24: orchestrator.v1.WorkflowService.ListWorkflows:input_type -> orchestrator.v1.ListWorkflowsRequest
	12, // 25: orchestrator.v1.WorkflowService.ExecuteWorkflow:input_type -> orchestrator.v1.ExecuteWorkflowRequest
	14, // 26: orchestrator.v1.WorkflowService.GetExecutionStatus:input_type -> orchestrator.v1.GetExecutionStatusRequest
	7,  // 27: orchestrator.v1.WorkflowService.CreateWorkflow:output_type -> orchestrator.v1.CreateWorkflowResponse
	9,  // 28: orchestrator.v1.WorkflowService.GetWorkflow:output_type -> orchestrator.v1.GetWorkflowResponse
	11, // 29: orchestrator.v1.WorkflowService.ListWorkflows:output_type -> orchestrator.v1.ListWorkflowsResponse
	13, // 30: orchestrator.v1.WorkflowService.ExecuteWorkflow:output_type -> orchestrator.v1.ExecuteWorkflowResponse
	15, // 31: orchestrator.v1.WorkflowService.GetExecutionStatus:output_type -> orchestrator.v1.GetExecutionStatusResponse
	27, // [27:32] is the sub-list for method output_type
	22, // [22:27] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_orchestrator_v1_workflow_proto_init() }
func file_orchestrator_v1_workflow_proto_init() {
	if File_orchestrator_v1_workflow_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_orchestrator_v1_workflow_proto_rawDesc), len(file_orchestrator_v1_workflow_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_orchestrator_v1_workflow_proto_goTypes,
		DependencyIndexes: file_orchestrator_v1_workflow_proto_depIdxs,
		EnumInfos:         file_orchestrator_v1_workflow_proto_enumTypes,
		MessageInfos:      file_orchestrator_v1_workflow_proto_msgTypes,
	}.Build()
	File_orchestrator_v1_workflow_proto = out.File
	file_orchestrator_v1_workflow_proto_goTypes = nil
	file_orchestrator_v1_workflow_proto_depIdxs = nil
}
