// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.8.0
// - protoc             (unknown)
// source: orchestrator/v1/workflow.proto

package orchestratorv1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationWorkflowServiceCreateWorkflow = "/orchestrator.v1.WorkflowService/CreateWorkflow"
const OperationWorkflowServiceExecuteWorkflow = "/orchestrator.v1.WorkflowService/ExecuteWorkflow"
const OperationWorkflowServiceGetExecutionStatus = "/orchestrator.v1.WorkflowService/GetExecutionStatus"
const OperationWorkflowServiceGetWorkflow = "/orchestrator.v1.WorkflowService/GetWorkflow"
const OperationWorkflowServiceListWorkflows = "/orchestrator.v1.WorkflowService/ListWorkflows"

type WorkflowServiceHTTPServer interface {
	// CreateWorkflow 创建工作流
	CreateWorkflow(context.Context, *CreateWorkflowRequest) (*CreateWorkflowResponse, error)
	// ExecuteWorkflow 执行工作流
	ExecuteWorkflow(context.Context, *ExecuteWorkflowRequest) (*ExecuteWorkflowResponse, error)
	// GetExecutionStatus 获取执行状态
	GetExecutionStatus(context.Context, *GetExecutionStatusRequest) (*GetExecutionStatusResponse, error)
	// GetWorkflow 获取工作流
	GetWorkflow(context.Context, *GetWorkflowRequest) (*GetWorkflowResponse, error)
	// ListWorkflows 列出工作流
	ListWorkflows(context.Context, *ListWorkflowsRequest) (*ListWorkflowsResponse, error)
}

func RegisterWorkflowServiceHTTPServer(s *http.Server, srv WorkflowServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/workflows", _WorkflowService_CreateWorkflow0_HTTP_Handler(srv))
	r.GET("/v1/workflows/{workflow_id}", _WorkflowService_GetWorkflow0_HTTP_Handler(srv))
	r.GET("/v1/workflows", _WorkflowService_ListWorkflows0_HTTP_Handler(srv))
	r.POST("/v1/workflows/{workflow_id}/executions", _WorkflowService_ExecuteWorkflow0_HTTP_Handler(srv))
	r.GET("/v1/executions/{execution_id}", _WorkflowService_GetExecutionStatus0_HTTP_Handler(srv))
}

func _WorkflowService_CreateWorkflow0_HTTP_Handler(srv WorkflowServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateWorkflowRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationWorkflowServiceCreateWorkflow)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateWorkflow(ctx, req.(*CreateWorkflowRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateWorkflowResponse)
		return ctx.Result(200, reply)
	}
}

func _WorkflowService_GetWorkflow0_HTTP_Handler(srv WorkflowServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetWorkflowRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationWorkflowServiceGetWorkflow)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetWorkflow(ctx, req.(*GetWorkflowRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetWorkflowResponse)
		return ctx.Result(200, reply)
	}
}

func _WorkflowService_ListWorkflows0_HTTP_Handler(srv WorkflowServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListWorkflowsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationWorkflowServiceListWorkflows)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListWorkflows(ctx, req.(*ListWorkflowsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListWorkflowsResponse)
		return ctx.Result(200, reply)
	}
}

func _WorkflowService_ExecuteWorkflow0_HTTP_Handler(srv WorkflowServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ExecuteWorkflowRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationWorkflowServiceExecuteWorkflow)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ExecuteWorkflow(ctx, req.(*ExecuteWorkflowRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ExecuteWorkflowResponse)
		return ctx.Result(200, reply)
	}
}

func _WorkflowService_GetExecutionStatus0_HTTP_Handler(srv WorkflowServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetExecutionStatusRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationWorkflowServiceGetExecutionStatus)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetExecutionStatus(ctx, req.(*GetExecutionStatusRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetExecutionStatusResponse)
		return ctx.Result(200, reply)
	}
}

type WorkflowServiceHTTPClient interface {
	CreateWorkflow(ctx context.Context, req *CreateWorkflowRequest, opts ...http.CallOption) (rsp *CreateWorkflowResponse, err error)
	ExecuteWorkflow(ctx context.Context, req *ExecuteWorkflowRequest, opts ...http.CallOption) (rsp *ExecuteWorkflowResponse, err error)
	GetExecutionStatus(ctx context.Context, req *GetExecutionStatusRequest, opts ...http.CallOption) (rsp *GetExecutionStatusResponse, err error)
	GetWorkflow(ctx context.Context, req *GetWorkflowRequest, opts ...http.CallOption) (rsp *GetWorkflowResponse, err error)
	ListWorkflows(ctx context.Context, req *ListWorkflowsRequest, opts ...http.CallOption) (rsp *ListWorkflowsResponse, err error)
}

type WorkflowServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewWorkflowServiceHTTPClient(client *http.Client) WorkflowServiceHTTPClient {
	return &WorkflowServiceHTTPClientImpl{client}
}

func (c *WorkflowServiceHTTPClientImpl) CreateWorkflow(ctx context.Context, in *CreateWorkflowRequest, opts ...http.CallOption) (*CreateWorkflowResponse, error) {
	var out CreateWorkflowResponse
	pattern := "/v1/workflows"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationWorkflowServiceCreateWorkflow))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *WorkflowServiceHTTPClientImpl) ExecuteWorkflow(ctx context.Context, in *ExecuteWorkflowRequest, opts ...http.CallOption) (*ExecuteWorkflowResponse, error) {
	var out ExecuteWorkflowResponse
	pattern := "/v1/workflows/{workflow_id}/executions"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationWorkflowServiceExecuteWorkflow))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *WorkflowServiceHTTPClientImpl) GetExecutionStatus(ctx context.Context, in *GetExecutionStatusRequest, opts ...http.CallOption) (*GetExecutionStatusResponse, error) {
	var out GetExecutionStatusResponse
	pattern := "/v1/executions/{execution_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationWorkflowServiceGetExecutionStatus))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *WorkflowServiceHTTPClientImpl) GetWorkflow(ctx context.Context, in *GetWorkflowRequest, opts ...http.CallOption) (*GetWorkflowResponse, error) {
	var out GetWorkflowResponse
	pattern := "/v1/workflows/{workflow_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationWorkflowServiceGetWorkflow))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *WorkflowServiceHTTPClientImpl) ListWorkflows(ctx context.Context, in *ListWorkflowsRequest, opts ...http.CallOption) (*ListWorkflowsResponse, error) {
	var out ListWorkflowsResponse
	pattern := "/v1/workflows"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationWorkflowServiceListWorkflows))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
