// monitor/monitor.proto
// Monitor Service API 定义 - 监控和告警服务

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: monitor/v1/monitor.proto

package monitorv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MonitorService_GetMetricsSummary_FullMethodName = "/monitor.v1.MonitorService/GetMetricsSummary"
	MonitorService_GetAgentMetrics_FullMethodName   = "/monitor.v1.MonitorService/GetAgentMetrics"
	MonitorService_QueryMetrics_FullMethodName      = "/monitor.v1.MonitorService/QueryMetrics"
	MonitorService_GetAlert_FullMethodName          = "/monitor.v1.MonitorService/GetAlert"
	MonitorService_ListAlerts_FullMethodName        = "/monitor.v1.MonitorService/ListAlerts"
	MonitorService_CreateAlert_FullMethodName       = "/monitor.v1.MonitorService/CreateAlert"
	MonitorService_UpdateAlert_FullMethodName       = "/monitor.v1.MonitorService/UpdateAlert"
	MonitorService_DeleteAlert_FullMethodName       = "/monitor.v1.MonitorService/DeleteAlert"
	MonitorService_AcknowledgeAlert_FullMethodName  = "/monitor.v1.MonitorService/AcknowledgeAlert"
)

// MonitorServiceClient is the client API for MonitorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MonitorServiceClient interface {
	// 获取监控概览
	GetMetricsSummary(ctx context.Context, in *GetMetricsSummaryRequest, opts ...grpc.CallOption) (*MetricsSummary, error)
	// 获取Agent指标
	GetAgentMetrics(ctx context.Context, in *GetAgentMetricsRequest, opts ...grpc.CallOption) (*GetAgentMetricsResponse, error)
	// 查询指标数据
	QueryMetrics(ctx context.Context, in *QueryMetricsRequest, opts ...grpc.CallOption) (*QueryMetricsResponse, error)
	// 获取告警
	GetAlert(ctx context.Context, in *GetAlertRequest, opts ...grpc.CallOption) (*Alert, error)
	// 列出告警
	ListAlerts(ctx context.Context, in *ListAlertsRequest, opts ...grpc.CallOption) (*ListAlertsResponse, error)
	// 创建告警
	CreateAlert(ctx context.Context, in *CreateAlertRequest, opts ...grpc.CallOption) (*Alert, error)
	// 更新告警
	UpdateAlert(ctx context.Context, in *UpdateAlertRequest, opts ...grpc.CallOption) (*Alert, error)
	// 删除告警
	DeleteAlert(ctx context.Context, in *DeleteAlertRequest, opts ...grpc.CallOption) (*DeleteAlertResponse, error)
	// 确认告警
	AcknowledgeAlert(ctx context.Context, in *AcknowledgeAlertRequest, opts ...grpc.CallOption) (*AcknowledgeAlertResponse, error)
}

type monitorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMonitorServiceClient(cc grpc.ClientConnInterface) MonitorServiceClient {
	return &monitorServiceClient{cc}
}

func (c *monitorServiceClient) GetMetricsSummary(ctx context.Context, in *GetMetricsSummaryRequest, opts ...grpc.CallOption) (*MetricsSummary, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MetricsSummary)
	err := c.cc.Invoke(ctx, MonitorService_GetMetricsSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitorServiceClient) GetAgentMetrics(ctx context.Context, in *GetAgentMetricsRequest, opts ...grpc.CallOption) (*GetAgentMetricsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAgentMetricsResponse)
	err := c.cc.Invoke(ctx, MonitorService_GetAgentMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitorServiceClient) QueryMetrics(ctx context.Context, in *QueryMetricsRequest, opts ...grpc.CallOption) (*QueryMetricsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryMetricsResponse)
	err := c.cc.Invoke(ctx, MonitorService_QueryMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitorServiceClient) GetAlert(ctx context.Context, in *GetAlertRequest, opts ...grpc.CallOption) (*Alert, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Alert)
	err := c.cc.Invoke(ctx, MonitorService_GetAlert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitorServiceClient) ListAlerts(ctx context.Context, in *ListAlertsRequest, opts ...grpc.CallOption) (*ListAlertsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAlertsResponse)
	err := c.cc.Invoke(ctx, MonitorService_ListAlerts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitorServiceClient) CreateAlert(ctx context.Context, in *CreateAlertRequest, opts ...grpc.CallOption) (*Alert, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Alert)
	err := c.cc.Invoke(ctx, MonitorService_CreateAlert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitorServiceClient) UpdateAlert(ctx context.Context, in *UpdateAlertRequest, opts ...grpc.CallOption) (*Alert, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Alert)
	err := c.cc.Invoke(ctx, MonitorService_UpdateAlert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitorServiceClient) DeleteAlert(ctx context.Context, in *DeleteAlertRequest, opts ...grpc.CallOption) (*DeleteAlertResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteAlertResponse)
	err := c.cc.Invoke(ctx, MonitorService_DeleteAlert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitorServiceClient) AcknowledgeAlert(ctx context.Context, in *AcknowledgeAlertRequest, opts ...grpc.CallOption) (*AcknowledgeAlertResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AcknowledgeAlertResponse)
	err := c.cc.Invoke(ctx, MonitorService_AcknowledgeAlert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MonitorServiceServer is the server API for MonitorService service.
// All implementations should embed UnimplementedMonitorServiceServer
// for forward compatibility.
type MonitorServiceServer interface {
	// 获取监控概览
	GetMetricsSummary(context.Context, *GetMetricsSummaryRequest) (*MetricsSummary, error)
	// 获取Agent指标
	GetAgentMetrics(context.Context, *GetAgentMetricsRequest) (*GetAgentMetricsResponse, error)
	// 查询指标数据
	QueryMetrics(context.Context, *QueryMetricsRequest) (*QueryMetricsResponse, error)
	// 获取告警
	GetAlert(context.Context, *GetAlertRequest) (*Alert, error)
	// 列出告警
	ListAlerts(context.Context, *ListAlertsRequest) (*ListAlertsResponse, error)
	// 创建告警
	CreateAlert(context.Context, *CreateAlertRequest) (*Alert, error)
	// 更新告警
	UpdateAlert(context.Context, *UpdateAlertRequest) (*Alert, error)
	// 删除告警
	DeleteAlert(context.Context, *DeleteAlertRequest) (*DeleteAlertResponse, error)
	// 确认告警
	AcknowledgeAlert(context.Context, *AcknowledgeAlertRequest) (*AcknowledgeAlertResponse, error)
}

// UnimplementedMonitorServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMonitorServiceServer struct{}

func (UnimplementedMonitorServiceServer) GetMetricsSummary(context.Context, *GetMetricsSummaryRequest) (*MetricsSummary, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMetricsSummary not implemented")
}
func (UnimplementedMonitorServiceServer) GetAgentMetrics(context.Context, *GetAgentMetricsRequest) (*GetAgentMetricsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAgentMetrics not implemented")
}
func (UnimplementedMonitorServiceServer) QueryMetrics(context.Context, *QueryMetricsRequest) (*QueryMetricsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryMetrics not implemented")
}
func (UnimplementedMonitorServiceServer) GetAlert(context.Context, *GetAlertRequest) (*Alert, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAlert not implemented")
}
func (UnimplementedMonitorServiceServer) ListAlerts(context.Context, *ListAlertsRequest) (*ListAlertsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAlerts not implemented")
}
func (UnimplementedMonitorServiceServer) CreateAlert(context.Context, *CreateAlertRequest) (*Alert, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAlert not implemented")
}
func (UnimplementedMonitorServiceServer) UpdateAlert(context.Context, *UpdateAlertRequest) (*Alert, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAlert not implemented")
}
func (UnimplementedMonitorServiceServer) DeleteAlert(context.Context, *DeleteAlertRequest) (*DeleteAlertResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAlert not implemented")
}
func (UnimplementedMonitorServiceServer) AcknowledgeAlert(context.Context, *AcknowledgeAlertRequest) (*AcknowledgeAlertResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AcknowledgeAlert not implemented")
}
func (UnimplementedMonitorServiceServer) testEmbeddedByValue() {}

// UnsafeMonitorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MonitorServiceServer will
// result in compilation errors.
type UnsafeMonitorServiceServer interface {
	mustEmbedUnimplementedMonitorServiceServer()
}

func RegisterMonitorServiceServer(s grpc.ServiceRegistrar, srv MonitorServiceServer) {
	// If the following call pancis, it indicates UnimplementedMonitorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MonitorService_ServiceDesc, srv)
}

func _MonitorService_GetMetricsSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMetricsSummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorServiceServer).GetMetricsSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MonitorService_GetMetricsSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorServiceServer).GetMetricsSummary(ctx, req.(*GetMetricsSummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonitorService_GetAgentMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAgentMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorServiceServer).GetAgentMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MonitorService_GetAgentMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorServiceServer).GetAgentMetrics(ctx, req.(*GetAgentMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonitorService_QueryMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorServiceServer).QueryMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MonitorService_QueryMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorServiceServer).QueryMetrics(ctx, req.(*QueryMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonitorService_GetAlert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAlertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorServiceServer).GetAlert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MonitorService_GetAlert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorServiceServer).GetAlert(ctx, req.(*GetAlertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonitorService_ListAlerts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAlertsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorServiceServer).ListAlerts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MonitorService_ListAlerts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorServiceServer).ListAlerts(ctx, req.(*ListAlertsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonitorService_CreateAlert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAlertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorServiceServer).CreateAlert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MonitorService_CreateAlert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorServiceServer).CreateAlert(ctx, req.(*CreateAlertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonitorService_UpdateAlert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAlertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorServiceServer).UpdateAlert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MonitorService_UpdateAlert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorServiceServer).UpdateAlert(ctx, req.(*UpdateAlertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonitorService_DeleteAlert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAlertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorServiceServer).DeleteAlert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MonitorService_DeleteAlert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorServiceServer).DeleteAlert(ctx, req.(*DeleteAlertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonitorService_AcknowledgeAlert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcknowledgeAlertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorServiceServer).AcknowledgeAlert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MonitorService_AcknowledgeAlert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorServiceServer).AcknowledgeAlert(ctx, req.(*AcknowledgeAlertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MonitorService_ServiceDesc is the grpc.ServiceDesc for MonitorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MonitorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "monitor.v1.MonitorService",
	HandlerType: (*MonitorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMetricsSummary",
			Handler:    _MonitorService_GetMetricsSummary_Handler,
		},
		{
			MethodName: "GetAgentMetrics",
			Handler:    _MonitorService_GetAgentMetrics_Handler,
		},
		{
			MethodName: "QueryMetrics",
			Handler:    _MonitorService_QueryMetrics_Handler,
		},
		{
			MethodName: "GetAlert",
			Handler:    _MonitorService_GetAlert_Handler,
		},
		{
			MethodName: "ListAlerts",
			Handler:    _MonitorService_ListAlerts_Handler,
		},
		{
			MethodName: "CreateAlert",
			Handler:    _MonitorService_CreateAlert_Handler,
		},
		{
			MethodName: "UpdateAlert",
			Handler:    _MonitorService_UpdateAlert_Handler,
		},
		{
			MethodName: "DeleteAlert",
			Handler:    _MonitorService_DeleteAlert_Handler,
		},
		{
			MethodName: "AcknowledgeAlert",
			Handler:    _MonitorService_AcknowledgeAlert_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "monitor/v1/monitor.proto",
}

const (
	AlertRuleService_GetAlertRule_FullMethodName    = "/monitor.v1.AlertRuleService/GetAlertRule"
	AlertRuleService_ListAlertRules_FullMethodName  = "/monitor.v1.AlertRuleService/ListAlertRules"
	AlertRuleService_CreateAlertRule_FullMethodName = "/monitor.v1.AlertRuleService/CreateAlertRule"
	AlertRuleService_UpdateAlertRule_FullMethodName = "/monitor.v1.AlertRuleService/UpdateAlertRule"
	AlertRuleService_DeleteAlertRule_FullMethodName = "/monitor.v1.AlertRuleService/DeleteAlertRule"
	AlertRuleService_ToggleAlertRule_FullMethodName = "/monitor.v1.AlertRuleService/ToggleAlertRule"
)

// AlertRuleServiceClient is the client API for AlertRuleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AlertRuleServiceClient interface {
	// 获取告警规则
	GetAlertRule(ctx context.Context, in *GetAlertRuleRequest, opts ...grpc.CallOption) (*AlertRule, error)
	// 列出告警规则
	ListAlertRules(ctx context.Context, in *ListAlertRulesRequest, opts ...grpc.CallOption) (*ListAlertRulesResponse, error)
	// 创建告警规则
	CreateAlertRule(ctx context.Context, in *CreateAlertRuleRequest, opts ...grpc.CallOption) (*AlertRule, error)
	// 更新告警规则
	UpdateAlertRule(ctx context.Context, in *UpdateAlertRuleRequest, opts ...grpc.CallOption) (*AlertRule, error)
	// 删除告警规则
	DeleteAlertRule(ctx context.Context, in *DeleteAlertRuleRequest, opts ...grpc.CallOption) (*DeleteAlertRuleResponse, error)
	// 启用/禁用告警规则
	ToggleAlertRule(ctx context.Context, in *ToggleAlertRuleRequest, opts ...grpc.CallOption) (*AlertRule, error)
}

type alertRuleServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAlertRuleServiceClient(cc grpc.ClientConnInterface) AlertRuleServiceClient {
	return &alertRuleServiceClient{cc}
}

func (c *alertRuleServiceClient) GetAlertRule(ctx context.Context, in *GetAlertRuleRequest, opts ...grpc.CallOption) (*AlertRule, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AlertRule)
	err := c.cc.Invoke(ctx, AlertRuleService_GetAlertRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alertRuleServiceClient) ListAlertRules(ctx context.Context, in *ListAlertRulesRequest, opts ...grpc.CallOption) (*ListAlertRulesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAlertRulesResponse)
	err := c.cc.Invoke(ctx, AlertRuleService_ListAlertRules_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alertRuleServiceClient) CreateAlertRule(ctx context.Context, in *CreateAlertRuleRequest, opts ...grpc.CallOption) (*AlertRule, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AlertRule)
	err := c.cc.Invoke(ctx, AlertRuleService_CreateAlertRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alertRuleServiceClient) UpdateAlertRule(ctx context.Context, in *UpdateAlertRuleRequest, opts ...grpc.CallOption) (*AlertRule, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AlertRule)
	err := c.cc.Invoke(ctx, AlertRuleService_UpdateAlertRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alertRuleServiceClient) DeleteAlertRule(ctx context.Context, in *DeleteAlertRuleRequest, opts ...grpc.CallOption) (*DeleteAlertRuleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteAlertRuleResponse)
	err := c.cc.Invoke(ctx, AlertRuleService_DeleteAlertRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alertRuleServiceClient) ToggleAlertRule(ctx context.Context, in *ToggleAlertRuleRequest, opts ...grpc.CallOption) (*AlertRule, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AlertRule)
	err := c.cc.Invoke(ctx, AlertRuleService_ToggleAlertRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AlertRuleServiceServer is the server API for AlertRuleService service.
// All implementations should embed UnimplementedAlertRuleServiceServer
// for forward compatibility.
type AlertRuleServiceServer interface {
	// 获取告警规则
	GetAlertRule(context.Context, *GetAlertRuleRequest) (*AlertRule, error)
	// 列出告警规则
	ListAlertRules(context.Context, *ListAlertRulesRequest) (*ListAlertRulesResponse, error)
	// 创建告警规则
	CreateAlertRule(context.Context, *CreateAlertRuleRequest) (*AlertRule, error)
	// 更新告警规则
	UpdateAlertRule(context.Context, *UpdateAlertRuleRequest) (*AlertRule, error)
	// 删除告警规则
	DeleteAlertRule(context.Context, *DeleteAlertRuleRequest) (*DeleteAlertRuleResponse, error)
	// 启用/禁用告警规则
	ToggleAlertRule(context.Context, *ToggleAlertRuleRequest) (*AlertRule, error)
}

// UnimplementedAlertRuleServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAlertRuleServiceServer struct{}

func (UnimplementedAlertRuleServiceServer) GetAlertRule(context.Context, *GetAlertRuleRequest) (*AlertRule, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAlertRule not implemented")
}
func (UnimplementedAlertRuleServiceServer) ListAlertRules(context.Context, *ListAlertRulesRequest) (*ListAlertRulesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAlertRules not implemented")
}
func (UnimplementedAlertRuleServiceServer) CreateAlertRule(context.Context, *CreateAlertRuleRequest) (*AlertRule, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAlertRule not implemented")
}
func (UnimplementedAlertRuleServiceServer) UpdateAlertRule(context.Context, *UpdateAlertRuleRequest) (*AlertRule, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAlertRule not implemented")
}
func (UnimplementedAlertRuleServiceServer) DeleteAlertRule(context.Context, *DeleteAlertRuleRequest) (*DeleteAlertRuleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAlertRule not implemented")
}
func (UnimplementedAlertRuleServiceServer) ToggleAlertRule(context.Context, *ToggleAlertRuleRequest) (*AlertRule, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ToggleAlertRule not implemented")
}
func (UnimplementedAlertRuleServiceServer) testEmbeddedByValue() {}

// UnsafeAlertRuleServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AlertRuleServiceServer will
// result in compilation errors.
type UnsafeAlertRuleServiceServer interface {
	mustEmbedUnimplementedAlertRuleServiceServer()
}

func RegisterAlertRuleServiceServer(s grpc.ServiceRegistrar, srv AlertRuleServiceServer) {
	// If the following call pancis, it indicates UnimplementedAlertRuleServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AlertRuleService_ServiceDesc, srv)
}

func _AlertRuleService_GetAlertRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAlertRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlertRuleServiceServer).GetAlertRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlertRuleService_GetAlertRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlertRuleServiceServer).GetAlertRule(ctx, req.(*GetAlertRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlertRuleService_ListAlertRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAlertRulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlertRuleServiceServer).ListAlertRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlertRuleService_ListAlertRules_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlertRuleServiceServer).ListAlertRules(ctx, req.(*ListAlertRulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlertRuleService_CreateAlertRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAlertRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlertRuleServiceServer).CreateAlertRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlertRuleService_CreateAlertRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlertRuleServiceServer).CreateAlertRule(ctx, req.(*CreateAlertRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlertRuleService_UpdateAlertRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAlertRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlertRuleServiceServer).UpdateAlertRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlertRuleService_UpdateAlertRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlertRuleServiceServer).UpdateAlertRule(ctx, req.(*UpdateAlertRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlertRuleService_DeleteAlertRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAlertRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlertRuleServiceServer).DeleteAlertRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlertRuleService_DeleteAlertRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlertRuleServiceServer).DeleteAlertRule(ctx, req.(*DeleteAlertRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlertRuleService_ToggleAlertRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ToggleAlertRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlertRuleServiceServer).ToggleAlertRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlertRuleService_ToggleAlertRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlertRuleServiceServer).ToggleAlertRule(ctx, req.(*ToggleAlertRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AlertRuleService_ServiceDesc is the grpc.ServiceDesc for AlertRuleService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AlertRuleService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "monitor.v1.AlertRuleService",
	HandlerType: (*AlertRuleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAlertRule",
			Handler:    _AlertRuleService_GetAlertRule_Handler,
		},
		{
			MethodName: "ListAlertRules",
			Handler:    _AlertRuleService_ListAlertRules_Handler,
		},
		{
			MethodName: "CreateAlertRule",
			Handler:    _AlertRuleService_CreateAlertRule_Handler,
		},
		{
			MethodName: "UpdateAlertRule",
			Handler:    _AlertRuleService_UpdateAlertRule_Handler,
		},
		{
			MethodName: "DeleteAlertRule",
			Handler:    _AlertRuleService_DeleteAlertRule_Handler,
		},
		{
			MethodName: "ToggleAlertRule",
			Handler:    _AlertRuleService_ToggleAlertRule_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "monitor/v1/monitor.proto",
}

const (
	MetricsCollectorService_ReportMetrics_FullMethodName      = "/monitor.v1.MetricsCollectorService/ReportMetrics"
	MetricsCollectorService_GetCollectorConfig_FullMethodName = "/monitor.v1.MetricsCollectorService/GetCollectorConfig"
)

// MetricsCollectorServiceClient is the client API for MetricsCollectorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MetricsCollectorServiceClient interface {
	// 上报指标（流式）
	ReportMetrics(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[MetricData, ReportMetricsResponse], error)
	// 获取采集器配置
	GetCollectorConfig(ctx context.Context, in *GetCollectorConfigRequest, opts ...grpc.CallOption) (*CollectorConfig, error)
}

type metricsCollectorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMetricsCollectorServiceClient(cc grpc.ClientConnInterface) MetricsCollectorServiceClient {
	return &metricsCollectorServiceClient{cc}
}

func (c *metricsCollectorServiceClient) ReportMetrics(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[MetricData, ReportMetricsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MetricsCollectorService_ServiceDesc.Streams[0], MetricsCollectorService_ReportMetrics_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[MetricData, ReportMetricsResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MetricsCollectorService_ReportMetricsClient = grpc.ClientStreamingClient[MetricData, ReportMetricsResponse]

func (c *metricsCollectorServiceClient) GetCollectorConfig(ctx context.Context, in *GetCollectorConfigRequest, opts ...grpc.CallOption) (*CollectorConfig, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CollectorConfig)
	err := c.cc.Invoke(ctx, MetricsCollectorService_GetCollectorConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MetricsCollectorServiceServer is the server API for MetricsCollectorService service.
// All implementations should embed UnimplementedMetricsCollectorServiceServer
// for forward compatibility.
type MetricsCollectorServiceServer interface {
	// 上报指标（流式）
	ReportMetrics(grpc.ClientStreamingServer[MetricData, ReportMetricsResponse]) error
	// 获取采集器配置
	GetCollectorConfig(context.Context, *GetCollectorConfigRequest) (*CollectorConfig, error)
}

// UnimplementedMetricsCollectorServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMetricsCollectorServiceServer struct{}

func (UnimplementedMetricsCollectorServiceServer) ReportMetrics(grpc.ClientStreamingServer[MetricData, ReportMetricsResponse]) error {
	return status.Errorf(codes.Unimplemented, "method ReportMetrics not implemented")
}
func (UnimplementedMetricsCollectorServiceServer) GetCollectorConfig(context.Context, *GetCollectorConfigRequest) (*CollectorConfig, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCollectorConfig not implemented")
}
func (UnimplementedMetricsCollectorServiceServer) testEmbeddedByValue() {}

// UnsafeMetricsCollectorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MetricsCollectorServiceServer will
// result in compilation errors.
type UnsafeMetricsCollectorServiceServer interface {
	mustEmbedUnimplementedMetricsCollectorServiceServer()
}

func RegisterMetricsCollectorServiceServer(s grpc.ServiceRegistrar, srv MetricsCollectorServiceServer) {
	// If the following call pancis, it indicates UnimplementedMetricsCollectorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MetricsCollectorService_ServiceDesc, srv)
}

func _MetricsCollectorService_ReportMetrics_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MetricsCollectorServiceServer).ReportMetrics(&grpc.GenericServerStream[MetricData, ReportMetricsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MetricsCollectorService_ReportMetricsServer = grpc.ClientStreamingServer[MetricData, ReportMetricsResponse]

func _MetricsCollectorService_GetCollectorConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCollectorConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricsCollectorServiceServer).GetCollectorConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetricsCollectorService_GetCollectorConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricsCollectorServiceServer).GetCollectorConfig(ctx, req.(*GetCollectorConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MetricsCollectorService_ServiceDesc is the grpc.ServiceDesc for MetricsCollectorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MetricsCollectorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "monitor.v1.MetricsCollectorService",
	HandlerType: (*MetricsCollectorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCollectorConfig",
			Handler:    _MetricsCollectorService_GetCollectorConfig_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ReportMetrics",
			Handler:       _MetricsCollectorService_ReportMetrics_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "monitor/v1/monitor.proto",
}
