// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.8.0
// - protoc             (unknown)
// source: monitor/v1/monitor.proto

package monitorv1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationMonitorServiceAcknowledgeAlert = "/monitor.v1.MonitorService/AcknowledgeAlert"
const OperationMonitorServiceCreateAlert = "/monitor.v1.MonitorService/CreateAlert"
const OperationMonitorServiceDeleteAlert = "/monitor.v1.MonitorService/DeleteAlert"
const OperationMonitorServiceGetAgentMetrics = "/monitor.v1.MonitorService/GetAgentMetrics"
const OperationMonitorServiceGetAlert = "/monitor.v1.MonitorService/GetAlert"
const OperationMonitorServiceGetMetricsSummary = "/monitor.v1.MonitorService/GetMetricsSummary"
const OperationMonitorServiceListAlerts = "/monitor.v1.MonitorService/ListAlerts"
const OperationMonitorServiceQueryMetrics = "/monitor.v1.MonitorService/QueryMetrics"
const OperationMonitorServiceUpdateAlert = "/monitor.v1.MonitorService/UpdateAlert"

type MonitorServiceHTTPServer interface {
	// AcknowledgeAlert 确认告警
	AcknowledgeAlert(context.Context, *AcknowledgeAlertRequest) (*AcknowledgeAlertResponse, error)
	// CreateAlert 创建告警
	CreateAlert(context.Context, *CreateAlertRequest) (*Alert, error)
	// DeleteAlert 删除告警
	DeleteAlert(context.Context, *DeleteAlertRequest) (*DeleteAlertResponse, error)
	// GetAgentMetrics 获取Agent指标
	GetAgentMetrics(context.Context, *GetAgentMetricsRequest) (*GetAgentMetricsResponse, error)
	// GetAlert 获取告警
	GetAlert(context.Context, *GetAlertRequest) (*Alert, error)
	// GetMetricsSummary 获取监控概览
	GetMetricsSummary(context.Context, *GetMetricsSummaryRequest) (*MetricsSummary, error)
	// ListAlerts 列出告警
	ListAlerts(context.Context, *ListAlertsRequest) (*ListAlertsResponse, error)
	// QueryMetrics 查询指标数据
	QueryMetrics(context.Context, *QueryMetricsRequest) (*QueryMetricsResponse, error)
	// UpdateAlert 更新告警
	UpdateAlert(context.Context, *UpdateAlertRequest) (*Alert, error)
}

func RegisterMonitorServiceHTTPServer(s *http.Server, srv MonitorServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/api/v1/monitor/summary", _MonitorService_GetMetricsSummary0_HTTP_Handler(srv))
	r.GET("/api/v1/monitor/agents/metrics", _MonitorService_GetAgentMetrics0_HTTP_Handler(srv))
	r.POST("/api/v1/monitor/query", _MonitorService_QueryMetrics0_HTTP_Handler(srv))
	r.GET("/api/v1/monitor/alerts/{alert_id}", _MonitorService_GetAlert0_HTTP_Handler(srv))
	r.GET("/api/v1/monitor/alerts", _MonitorService_ListAlerts0_HTTP_Handler(srv))
	r.POST("/api/v1/monitor/alerts", _MonitorService_CreateAlert0_HTTP_Handler(srv))
	r.PUT("/api/v1/monitor/alerts/{alert_id}", _MonitorService_UpdateAlert0_HTTP_Handler(srv))
	r.DELETE("/api/v1/monitor/alerts/{alert_id}", _MonitorService_DeleteAlert0_HTTP_Handler(srv))
	r.POST("/api/v1/monitor/alerts/{alert_id}/acknowledge", _MonitorService_AcknowledgeAlert0_HTTP_Handler(srv))
}

func _MonitorService_GetMetricsSummary0_HTTP_Handler(srv MonitorServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetMetricsSummaryRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMonitorServiceGetMetricsSummary)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetMetricsSummary(ctx, req.(*GetMetricsSummaryRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*MetricsSummary)
		return ctx.Result(200, reply)
	}
}

func _MonitorService_GetAgentMetrics0_HTTP_Handler(srv MonitorServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetAgentMetricsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMonitorServiceGetAgentMetrics)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetAgentMetrics(ctx, req.(*GetAgentMetricsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetAgentMetricsResponse)
		return ctx.Result(200, reply)
	}
}

func _MonitorService_QueryMetrics0_HTTP_Handler(srv MonitorServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in QueryMetricsRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMonitorServiceQueryMetrics)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.QueryMetrics(ctx, req.(*QueryMetricsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*QueryMetricsResponse)
		return ctx.Result(200, reply)
	}
}

func _MonitorService_GetAlert0_HTTP_Handler(srv MonitorServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetAlertRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMonitorServiceGetAlert)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetAlert(ctx, req.(*GetAlertRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Alert)
		return ctx.Result(200, reply)
	}
}

func _MonitorService_ListAlerts0_HTTP_Handler(srv MonitorServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListAlertsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMonitorServiceListAlerts)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListAlerts(ctx, req.(*ListAlertsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListAlertsResponse)
		return ctx.Result(200, reply)
	}
}

func _MonitorService_CreateAlert0_HTTP_Handler(srv MonitorServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateAlertRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMonitorServiceCreateAlert)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateAlert(ctx, req.(*CreateAlertRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Alert)
		return ctx.Result(200, reply)
	}
}

func _MonitorService_UpdateAlert0_HTTP_Handler(srv MonitorServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateAlertRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMonitorServiceUpdateAlert)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateAlert(ctx, req.(*UpdateAlertRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Alert)
		return ctx.Result(200, reply)
	}
}

func _MonitorService_DeleteAlert0_HTTP_Handler(srv MonitorServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteAlertRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMonitorServiceDeleteAlert)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteAlert(ctx, req.(*DeleteAlertRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteAlertResponse)
		return ctx.Result(200, reply)
	}
}

func _MonitorService_AcknowledgeAlert0_HTTP_Handler(srv MonitorServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AcknowledgeAlertRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMonitorServiceAcknowledgeAlert)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.AcknowledgeAlert(ctx, req.(*AcknowledgeAlertRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AcknowledgeAlertResponse)
		return ctx.Result(200, reply)
	}
}

type MonitorServiceHTTPClient interface {
	AcknowledgeAlert(ctx context.Context, req *AcknowledgeAlertRequest, opts ...http.CallOption) (rsp *AcknowledgeAlertResponse, err error)
	CreateAlert(ctx context.Context, req *CreateAlertRequest, opts ...http.CallOption) (rsp *Alert, err error)
	DeleteAlert(ctx context.Context, req *DeleteAlertRequest, opts ...http.CallOption) (rsp *DeleteAlertResponse, err error)
	GetAgentMetrics(ctx context.Context, req *GetAgentMetricsRequest, opts ...http.CallOption) (rsp *GetAgentMetricsResponse, err error)
	GetAlert(ctx context.Context, req *GetAlertRequest, opts ...http.CallOption) (rsp *Alert, err error)
	GetMetricsSummary(ctx context.Context, req *GetMetricsSummaryRequest, opts ...http.CallOption) (rsp *MetricsSummary, err error)
	ListAlerts(ctx context.Context, req *ListAlertsRequest, opts ...http.CallOption) (rsp *ListAlertsResponse, err error)
	QueryMetrics(ctx context.Context, req *QueryMetricsRequest, opts ...http.CallOption) (rsp *QueryMetricsResponse, err error)
	UpdateAlert(ctx context.Context, req *UpdateAlertRequest, opts ...http.CallOption) (rsp *Alert, err error)
}

type MonitorServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewMonitorServiceHTTPClient(client *http.Client) MonitorServiceHTTPClient {
	return &MonitorServiceHTTPClientImpl{client}
}

func (c *MonitorServiceHTTPClientImpl) AcknowledgeAlert(ctx context.Context, in *AcknowledgeAlertRequest, opts ...http.CallOption) (*AcknowledgeAlertResponse, error) {
	var out AcknowledgeAlertResponse
	pattern := "/api/v1/monitor/alerts/{alert_id}/acknowledge"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationMonitorServiceAcknowledgeAlert))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *MonitorServiceHTTPClientImpl) CreateAlert(ctx context.Context, in *CreateAlertRequest, opts ...http.CallOption) (*Alert, error) {
	var out Alert
	pattern := "/api/v1/monitor/alerts"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationMonitorServiceCreateAlert))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *MonitorServiceHTTPClientImpl) DeleteAlert(ctx context.Context, in *DeleteAlertRequest, opts ...http.CallOption) (*DeleteAlertResponse, error) {
	var out DeleteAlertResponse
	pattern := "/api/v1/monitor/alerts/{alert_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMonitorServiceDeleteAlert))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *MonitorServiceHTTPClientImpl) GetAgentMetrics(ctx context.Context, in *GetAgentMetricsRequest, opts ...http.CallOption) (*GetAgentMetricsResponse, error) {
	var out GetAgentMetricsResponse
	pattern := "/api/v1/monitor/agents/metrics"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMonitorServiceGetAgentMetrics))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *MonitorServiceHTTPClientImpl) GetAlert(ctx context.Context, in *GetAlertRequest, opts ...http.CallOption) (*Alert, error) {
	var out Alert
	pattern := "/api/v1/monitor/alerts/{alert_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMonitorServiceGetAlert))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *MonitorServiceHTTPClientImpl) GetMetricsSummary(ctx context.Context, in *GetMetricsSummaryRequest, opts ...http.CallOption) (*MetricsSummary, error) {
	var out MetricsSummary
	pattern := "/api/v1/monitor/summary"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMonitorServiceGetMetricsSummary))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *MonitorServiceHTTPClientImpl) ListAlerts(ctx context.Context, in *ListAlertsRequest, opts ...http.CallOption) (*ListAlertsResponse, error) {
	var out ListAlertsResponse
	pattern := "/api/v1/monitor/alerts"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMonitorServiceListAlerts))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *MonitorServiceHTTPClientImpl) QueryMetrics(ctx context.Context, in *QueryMetricsRequest, opts ...http.CallOption) (*QueryMetricsResponse, error) {
	var out QueryMetricsResponse
	pattern := "/api/v1/monitor/query"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationMonitorServiceQueryMetrics))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *MonitorServiceHTTPClientImpl) UpdateAlert(ctx context.Context, in *UpdateAlertRequest, opts ...http.CallOption) (*Alert, error) {
	var out Alert
	pattern := "/api/v1/monitor/alerts/{alert_id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationMonitorServiceUpdateAlert))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

const OperationAlertRuleServiceCreateAlertRule = "/monitor.v1.AlertRuleService/CreateAlertRule"
const OperationAlertRuleServiceDeleteAlertRule = "/monitor.v1.AlertRuleService/DeleteAlertRule"
const OperationAlertRuleServiceGetAlertRule = "/monitor.v1.AlertRuleService/GetAlertRule"
const OperationAlertRuleServiceListAlertRules = "/monitor.v1.AlertRuleService/ListAlertRules"
const OperationAlertRuleServiceToggleAlertRule = "/monitor.v1.AlertRuleService/ToggleAlertRule"
const OperationAlertRuleServiceUpdateAlertRule = "/monitor.v1.AlertRuleService/UpdateAlertRule"

type AlertRuleServiceHTTPServer interface {
	// CreateAlertRule 创建告警规则
	CreateAlertRule(context.Context, *CreateAlertRuleRequest) (*AlertRule, error)
	// DeleteAlertRule 删除告警规则
	DeleteAlertRule(context.Context, *DeleteAlertRuleRequest) (*DeleteAlertRuleResponse, error)
	// GetAlertRule 获取告警规则
	GetAlertRule(context.Context, *GetAlertRuleRequest) (*AlertRule, error)
	// ListAlertRules 列出告警规则
	ListAlertRules(context.Context, *ListAlertRulesRequest) (*ListAlertRulesResponse, error)
	// ToggleAlertRule 启用/禁用告警规则
	ToggleAlertRule(context.Context, *ToggleAlertRuleRequest) (*AlertRule, error)
	// UpdateAlertRule 更新告警规则
	UpdateAlertRule(context.Context, *UpdateAlertRuleRequest) (*AlertRule, error)
}

func RegisterAlertRuleServiceHTTPServer(s *http.Server, srv AlertRuleServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/api/v1/monitor/alert-rules/{rule_id}", _AlertRuleService_GetAlertRule0_HTTP_Handler(srv))
	r.GET("/api/v1/monitor/alert-rules", _AlertRuleService_ListAlertRules0_HTTP_Handler(srv))
	r.POST("/api/v1/monitor/alert-rules", _AlertRuleService_CreateAlertRule0_HTTP_Handler(srv))
	r.PUT("/api/v1/monitor/alert-rules/{rule_id}", _AlertRuleService_UpdateAlertRule0_HTTP_Handler(srv))
	r.DELETE("/api/v1/monitor/alert-rules/{rule_id}", _AlertRuleService_DeleteAlertRule0_HTTP_Handler(srv))
	r.POST("/api/v1/monitor/alert-rules/{rule_id}/toggle", _AlertRuleService_ToggleAlertRule0_HTTP_Handler(srv))
}

func _AlertRuleService_GetAlertRule0_HTTP_Handler(srv AlertRuleServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetAlertRuleRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAlertRuleServiceGetAlertRule)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetAlertRule(ctx, req.(*GetAlertRuleRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AlertRule)
		return ctx.Result(200, reply)
	}
}

func _AlertRuleService_ListAlertRules0_HTTP_Handler(srv AlertRuleServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListAlertRulesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAlertRuleServiceListAlertRules)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListAlertRules(ctx, req.(*ListAlertRulesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListAlertRulesResponse)
		return ctx.Result(200, reply)
	}
}

func _AlertRuleService_CreateAlertRule0_HTTP_Handler(srv AlertRuleServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateAlertRuleRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAlertRuleServiceCreateAlertRule)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateAlertRule(ctx, req.(*CreateAlertRuleRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AlertRule)
		return ctx.Result(200, reply)
	}
}

func _AlertRuleService_UpdateAlertRule0_HTTP_Handler(srv AlertRuleServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateAlertRuleRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAlertRuleServiceUpdateAlertRule)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateAlertRule(ctx, req.(*UpdateAlertRuleRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AlertRule)
		return ctx.Result(200, reply)
	}
}

func _AlertRuleService_DeleteAlertRule0_HTTP_Handler(srv AlertRuleServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteAlertRuleRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAlertRuleServiceDeleteAlertRule)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteAlertRule(ctx, req.(*DeleteAlertRuleRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteAlertRuleResponse)
		return ctx.Result(200, reply)
	}
}

func _AlertRuleService_ToggleAlertRule0_HTTP_Handler(srv AlertRuleServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ToggleAlertRuleRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAlertRuleServiceToggleAlertRule)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ToggleAlertRule(ctx, req.(*ToggleAlertRuleRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AlertRule)
		return ctx.Result(200, reply)
	}
}

type AlertRuleServiceHTTPClient interface {
	CreateAlertRule(ctx context.Context, req *CreateAlertRuleRequest, opts ...http.CallOption) (rsp *AlertRule, err error)
	DeleteAlertRule(ctx context.Context, req *DeleteAlertRuleRequest, opts ...http.CallOption) (rsp *DeleteAlertRuleResponse, err error)
	GetAlertRule(ctx context.Context, req *GetAlertRuleRequest, opts ...http.CallOption) (rsp *AlertRule, err error)
	ListAlertRules(ctx context.Context, req *ListAlertRulesRequest, opts ...http.CallOption) (rsp *ListAlertRulesResponse, err error)
	ToggleAlertRule(ctx context.Context, req *ToggleAlertRuleRequest, opts ...http.CallOption) (rsp *AlertRule, err error)
	UpdateAlertRule(ctx context.Context, req *UpdateAlertRuleRequest, opts ...http.CallOption) (rsp *AlertRule, err error)
}

type AlertRuleServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewAlertRuleServiceHTTPClient(client *http.Client) AlertRuleServiceHTTPClient {
	return &AlertRuleServiceHTTPClientImpl{client}
}

func (c *AlertRuleServiceHTTPClientImpl) CreateAlertRule(ctx context.Context, in *CreateAlertRuleRequest, opts ...http.CallOption) (*AlertRule, error) {
	var out AlertRule
	pattern := "/api/v1/monitor/alert-rules"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAlertRuleServiceCreateAlertRule))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AlertRuleServiceHTTPClientImpl) DeleteAlertRule(ctx context.Context, in *DeleteAlertRuleRequest, opts ...http.CallOption) (*DeleteAlertRuleResponse, error) {
	var out DeleteAlertRuleResponse
	pattern := "/api/v1/monitor/alert-rules/{rule_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAlertRuleServiceDeleteAlertRule))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AlertRuleServiceHTTPClientImpl) GetAlertRule(ctx context.Context, in *GetAlertRuleRequest, opts ...http.CallOption) (*AlertRule, error) {
	var out AlertRule
	pattern := "/api/v1/monitor/alert-rules/{rule_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAlertRuleServiceGetAlertRule))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AlertRuleServiceHTTPClientImpl) ListAlertRules(ctx context.Context, in *ListAlertRulesRequest, opts ...http.CallOption) (*ListAlertRulesResponse, error) {
	var out ListAlertRulesResponse
	pattern := "/api/v1/monitor/alert-rules"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAlertRuleServiceListAlertRules))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AlertRuleServiceHTTPClientImpl) ToggleAlertRule(ctx context.Context, in *ToggleAlertRuleRequest, opts ...http.CallOption) (*AlertRule, error) {
	var out AlertRule
	pattern := "/api/v1/monitor/alert-rules/{rule_id}/toggle"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAlertRuleServiceToggleAlertRule))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AlertRuleServiceHTTPClientImpl) UpdateAlertRule(ctx context.Context, in *UpdateAlertRuleRequest, opts ...http.CallOption) (*AlertRule, error) {
	var out AlertRule
	pattern := "/api/v1/monitor/alert-rules/{rule_id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAlertRuleServiceUpdateAlertRule))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

const OperationMetricsCollectorServiceGetCollectorConfig = "/monitor.v1.MetricsCollectorService/GetCollectorConfig"

type MetricsCollectorServiceHTTPServer interface {
	// GetCollectorConfig 获取采集器配置
	GetCollectorConfig(context.Context, *GetCollectorConfigRequest) (*CollectorConfig, error)
}

func RegisterMetricsCollectorServiceHTTPServer(s *http.Server, srv MetricsCollectorServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/api/v1/monitor/collector/config", _MetricsCollectorService_GetCollectorConfig0_HTTP_Handler(srv))
}

func _MetricsCollectorService_GetCollectorConfig0_HTTP_Handler(srv MetricsCollectorServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetCollectorConfigRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMetricsCollectorServiceGetCollectorConfig)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetCollectorConfig(ctx, req.(*GetCollectorConfigRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CollectorConfig)
		return ctx.Result(200, reply)
	}
}

type MetricsCollectorServiceHTTPClient interface {
	GetCollectorConfig(ctx context.Context, req *GetCollectorConfigRequest, opts ...http.CallOption) (rsp *CollectorConfig, err error)
}

type MetricsCollectorServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewMetricsCollectorServiceHTTPClient(client *http.Client) MetricsCollectorServiceHTTPClient {
	return &MetricsCollectorServiceHTTPClientImpl{client}
}

func (c *MetricsCollectorServiceHTTPClientImpl) GetCollectorConfig(ctx context.Context, in *GetCollectorConfigRequest, opts ...http.CallOption) (*CollectorConfig, error) {
	var out CollectorConfig
	pattern := "/api/v1/monitor/collector/config"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMetricsCollectorServiceGetCollectorConfig))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
