// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/kart-io/k8s-agent/cmd/reasoning/app/options"
	"github.com/kart-io/k8s-agent/internal/reasoning/initializers"
	pkginitializers "github.com/kart-io/k8s-agent/pkg/initializers"
)

// Injectors from wire.go:

// InitializeReasoningComponents automatically injects all components using Wire.
func InitializeReasoningComponents(opts *options.ServerOptions) (*ReasoningComponents, error) {
	logger, err := ProvideLogger(opts)
	if err != nil {
		return nil, err
	}
	llmOptions := opts.LLM
	llmInitializer := initializers.NewLLMInitializer(llmOptions, logger)
	unifiedServerInitializer := initializers.NewUnifiedServerInitializer(opts, logger, llmInitializer)
	healthOptions := opts.Health
	healthCheckInitializer := pkginitializers.NewHealthCheckInitializer(healthOptions, logger)
	reasoningComponents := NewReasoningComponents(llmInitializer, unifiedServerInitializer, healthCheckInitializer)
	return reasoningComponents, nil
}

