// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/google/wire"
	"github.com/kart-io/k8s-agent/internal/reasoning/initializers"
	"github.com/kart-io/k8s-agent/pkg/app"
	initializers2 "github.com/kart-io/k8s-agent/pkg/initializers"
)

// Injectors from wire.go:

// InitializeReasoningComponents automatically injects all components using Wire.
func InitializeReasoningComponents(opts *app.StandardOptions) (*ReasoningComponents, error) {
	llmOptions := opts.LLM
	logger, err := ProvideLogger(opts)
	if err != nil {
		return nil, err
	}
	llmInitializer := initializers.NewLLMInitializer(llmOptions, logger)
	unifiedServerInitializer := initializers.NewUnifiedServerInitializer(opts, logger, llmInitializer)
	healthOptions := opts.Health
	healthCheckInitializer := initializers2.NewHealthCheckInitializer(healthOptions, logger)
	reasoningComponents := NewReasoningComponents(llmInitializer, unifiedServerInitializer, healthCheckInitializer)
	return reasoningComponents, nil
}

// wire.go:

// InitializerSet Wire dependency set for all initializers.
var InitializerSet = wire.NewSet(
	ProvideLogger, initializers.NewLLMInitializer, initializers.NewUnifiedServerInitializer, wire.FieldsOf(new(*app.StandardOptions), "LLM"),
)

// HealthInitializerSet Wire dependency set for health check.
var HealthInitializerSet = wire.NewSet(initializers2.NewHealthCheckInitializer, wire.FieldsOf(new(*app.StandardOptions), "Health"))
