// common/health/health.proto
// 健康检查通用消息定义

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: common/health/v1/health.proto

package healthv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 健康状态枚举
type HealthCheckResponse_ServingStatus int32

const (
	HealthCheckResponse_SERVING_STATUS_UNSPECIFIED HealthCheckResponse_ServingStatus = 0
	HealthCheckResponse_SERVING                    HealthCheckResponse_ServingStatus = 1 // 服务正常
	HealthCheckResponse_NOT_SERVING                HealthCheckResponse_ServingStatus = 2 // 服务不可用
	HealthCheckResponse_UNKNOWN                    HealthCheckResponse_ServingStatus = 3 // 状态未知
)

// Enum value maps for HealthCheckResponse_ServingStatus.
var (
	HealthCheckResponse_ServingStatus_name = map[int32]string{
		0: "SERVING_STATUS_UNSPECIFIED",
		1: "SERVING",
		2: "NOT_SERVING",
		3: "UNKNOWN",
	}
	HealthCheckResponse_ServingStatus_value = map[string]int32{
		"SERVING_STATUS_UNSPECIFIED": 0,
		"SERVING":                    1,
		"NOT_SERVING":                2,
		"UNKNOWN":                    3,
	}
)

func (x HealthCheckResponse_ServingStatus) Enum() *HealthCheckResponse_ServingStatus {
	p := new(HealthCheckResponse_ServingStatus)
	*p = x
	return p
}

func (x HealthCheckResponse_ServingStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthCheckResponse_ServingStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_common_health_v1_health_proto_enumTypes[0].Descriptor()
}

func (HealthCheckResponse_ServingStatus) Type() protoreflect.EnumType {
	return &file_common_health_v1_health_proto_enumTypes[0]
}

func (x HealthCheckResponse_ServingStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthCheckResponse_ServingStatus.Descriptor instead.
func (HealthCheckResponse_ServingStatus) EnumDescriptor() ([]byte, []int) {
	return file_common_health_v1_health_proto_rawDescGZIP(), []int{1, 0}
}

// 健康检查请求
type HealthCheckRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 服务名称
	Service       string `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_common_health_v1_health_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_health_v1_health_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_common_health_v1_health_proto_rawDescGZIP(), []int{0}
}

func (x *HealthCheckRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

// 健康检查响应
type HealthCheckResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 当前服务状态
	Status HealthCheckResponse_ServingStatus `protobuf:"varint,1,opt,name=status,proto3,enum=common.health.v1.HealthCheckResponse_ServingStatus" json:"status,omitempty"`
	// 状态描述
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// 健康检查时间戳
	Timestamp int64 `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// 服务版本
	Version       string `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_common_health_v1_health_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_health_v1_health_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_common_health_v1_health_proto_rawDescGZIP(), []int{1}
}

func (x *HealthCheckResponse) GetStatus() HealthCheckResponse_ServingStatus {
	if x != nil {
		return x.Status
	}
	return HealthCheckResponse_SERVING_STATUS_UNSPECIFIED
}

func (x *HealthCheckResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HealthCheckResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *HealthCheckResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

var File_common_health_v1_health_proto protoreflect.FileDescriptor

const file_common_health_v1_health_proto_rawDesc = "" +
	"\n" +
	"\x1dcommon/health/v1/health.proto\x12\x10common.health.v1\".\n" +
	"\x12HealthCheckRequest\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\"\x90\x02\n" +
	"\x13HealthCheckResponse\x12K\n" +
	"\x06status\x18\x01 \x01(\x0e23.common.health.v1.HealthCheckResponse.ServingStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\"Z\n" +
	"\rServingStatus\x12\x1e\n" +
	"\x1aSERVING_STATUS_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aSERVING\x10\x01\x12\x0f\n" +
	"\vNOT_SERVING\x10\x02\x12\v\n" +
	"\aUNKNOWN\x10\x032\xbd\x01\n" +
	"\rHealthService\x12T\n" +
	"\x05Check\x12$.common.health.v1.HealthCheckRequest\x1a%.common.health.v1.HealthCheckResponse\x12V\n" +
	"\x05Watch\x12$.common.health.v1.HealthCheckRequest\x1a%.common.health.v1.HealthCheckResponse0\x01B\xc5\x01\n" +
	"\x14com.common.health.v1B\vHealthProtoP\x01Z>github.com/kart-io/k8s-agent/pkg/api/common/health/v1;healthv1\xa2\x02\x03CHX\xaa\x02\x10Common.Health.V1\xca\x02\x10Common\\Health\\V1\xe2\x02\x1cCommon\\Health\\V1\\GPBMetadata\xea\x02\x12Common::Health::V1b\x06proto3"

var (
	file_common_health_v1_health_proto_rawDescOnce sync.Once
	file_common_health_v1_health_proto_rawDescData []byte
)

func file_common_health_v1_health_proto_rawDescGZIP() []byte {
	file_common_health_v1_health_proto_rawDescOnce.Do(func() {
		file_common_health_v1_health_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_health_v1_health_proto_rawDesc), len(file_common_health_v1_health_proto_rawDesc)))
	})
	return file_common_health_v1_health_proto_rawDescData
}

var file_common_health_v1_health_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_common_health_v1_health_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_common_health_v1_health_proto_goTypes = []any{
	(HealthCheckResponse_ServingStatus)(0), // 0: common.health.v1.HealthCheckResponse.ServingStatus
	(*HealthCheckRequest)(nil),             // 1: common.health.v1.HealthCheckRequest
	(*HealthCheckResponse)(nil),            // 2: common.health.v1.HealthCheckResponse
}
var file_common_health_v1_health_proto_depIdxs = []int32{
	0, // 0: common.health.v1.HealthCheckResponse.status:type_name -> common.health.v1.HealthCheckResponse.ServingStatus
	1, // 1: common.health.v1.HealthService.Check:input_type -> common.health.v1.HealthCheckRequest
	1, // 2: common.health.v1.HealthService.Watch:input_type -> common.health.v1.HealthCheckRequest
	2, // 3: common.health.v1.HealthService.Check:output_type -> common.health.v1.HealthCheckResponse
	2, // 4: common.health.v1.HealthService.Watch:output_type -> common.health.v1.HealthCheckResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_common_health_v1_health_proto_init() }
func file_common_health_v1_health_proto_init() {
	if File_common_health_v1_health_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_health_v1_health_proto_rawDesc), len(file_common_health_v1_health_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_common_health_v1_health_proto_goTypes,
		DependencyIndexes: file_common_health_v1_health_proto_depIdxs,
		EnumInfos:         file_common_health_v1_health_proto_enumTypes,
		MessageInfos:      file_common_health_v1_health_proto_msgTypes,
	}.Build()
	File_common_health_v1_health_proto = out.File
	file_common_health_v1_health_proto_goTypes = nil
	file_common_health_v1_health_proto_depIdxs = nil
}
