// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/kart-io/k8s-agent/cmd/cluster/app/options"
	"github.com/kart-io/k8s-agent/internal/cluster/initializers"
	pkginitializers "github.com/kart-io/k8s-agent/pkg/initializers"
)

// Injectors from wire.go:

// InitializeClusterComponents automatically injects all components using Wire.
func InitializeClusterComponents(opts *options.ServerOptions) (*ClusterComponents, error) {
	logger, err := ProvideLogger(opts)
	if err != nil {
		return nil, err
	}
	databaseInitializer := initializers.NewDatabaseInitializer(opts, logger)
	httpServerInitializer := initializers.NewHTTPServerInitializer(opts, logger, databaseInitializer)
	healthOptions := opts.Health
	healthCheckInitializer := pkginitializers.NewHealthCheckInitializer(healthOptions, logger)
	clusterComponents := NewClusterComponents(databaseInitializer, httpServerInitializer, healthCheckInitializer)
	return clusterComponents, nil
}


