apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nats
spec:
  volumeClaimTemplates:
  - metadata:
      name: nats-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 2Gi  # Smaller storage for dev
