apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: aetherius-dev

resources:
- ../../../base/postgres

secretGenerator:
- name: postgres-secret
  literals:
  - username=postgres
  - password=dev-postgres-password

patches:
- path: pvc-patch.yaml
- path: service-patch.yaml

labels:
- pairs:
    environment: development
