// cluster/cluster.proto
// Cluster Service API 定义 - Kubernetes集群管理服务

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: cluster/v1/cluster.proto

package clusterv1

import (
	v1 "github.com/kart-io/k8s-agent/pkg/api/common/pagination/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 集群状态
type ClusterStatus int32

const (
	ClusterStatus_CLUSTER_STATUS_UNSPECIFIED ClusterStatus = 0
	ClusterStatus_HEALTHY                    ClusterStatus = 1 // 健康
	ClusterStatus_UNHEALTHY                  ClusterStatus = 2 // 不健康
	ClusterStatus_UNREACHABLE                ClusterStatus = 3 // 不可达
	ClusterStatus_UNKNOWN                    ClusterStatus = 4 // 未知
)

// Enum value maps for ClusterStatus.
var (
	ClusterStatus_name = map[int32]string{
		0: "CLUSTER_STATUS_UNSPECIFIED",
		1: "HEALTHY",
		2: "UNHEALTHY",
		3: "UNREACHABLE",
		4: "UNKNOWN",
	}
	ClusterStatus_value = map[string]int32{
		"CLUSTER_STATUS_UNSPECIFIED": 0,
		"HEALTHY":                    1,
		"UNHEALTHY":                  2,
		"UNREACHABLE":                3,
		"UNKNOWN":                    4,
	}
)

func (x ClusterStatus) Enum() *ClusterStatus {
	p := new(ClusterStatus)
	*p = x
	return p
}

func (x ClusterStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClusterStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_cluster_v1_cluster_proto_enumTypes[0].Descriptor()
}

func (ClusterStatus) Type() protoreflect.EnumType {
	return &file_cluster_v1_cluster_proto_enumTypes[0]
}

func (x ClusterStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ClusterStatus.Descriptor instead.
func (ClusterStatus) EnumDescriptor() ([]byte, []int) {
	return file_cluster_v1_cluster_proto_rawDescGZIP(), []int{0}
}

// 资源类型
type ResourceType int32

const (
	ResourceType_RESOURCE_TYPE_UNSPECIFIED ResourceType = 0
	ResourceType_POD                       ResourceType = 1
	ResourceType_DEPLOYMENT                ResourceType = 2
	ResourceType_SERVICE                   ResourceType = 3
	ResourceType_CONFIGMAP                 ResourceType = 4
	ResourceType_SECRET                    ResourceType = 5
	ResourceType_NAMESPACE                 ResourceType = 6
	ResourceType_NODE                      ResourceType = 7
	ResourceType_PERSISTENTVOLUME          ResourceType = 8
	ResourceType_PERSISTENTVOLUMECLAIM     ResourceType = 9
	ResourceType_STATEFULSET               ResourceType = 10
	ResourceType_DAEMONSET                 ResourceType = 11
	ResourceType_JOB                       ResourceType = 12
	ResourceType_CRONJOB                   ResourceType = 13
	ResourceType_INGRESS                   ResourceType = 14
	ResourceType_NETWORKPOLICY             ResourceType = 15
	ResourceType_RESOURCEQUOTA             ResourceType = 16
	ResourceType_LIMITRANGE                ResourceType = 17
	ResourceType_HORIZONTALPODAUTOSCALER   ResourceType = 18
	ResourceType_STORAGECLASS              ResourceType = 19
	ResourceType_ROLE                      ResourceType = 20
	ResourceType_ROLEBINDING               ResourceType = 21
	ResourceType_CLUSTERROLE               ResourceType = 22
	ResourceType_CLUSTERROLEBINDING        ResourceType = 23
	ResourceType_SERVICEACCOUNT            ResourceType = 24
	ResourceType_ENDPOINT                  ResourceType = 25
	ResourceType_ENDPOINTSLICE             ResourceType = 26
	ResourceType_EVENT                     ResourceType = 27
	ResourceType_PRIORITYCLASS             ResourceType = 28
	ResourceType_REPLICASET                ResourceType = 29
)

// Enum value maps for ResourceType.
var (
	ResourceType_name = map[int32]string{
		0:  "RESOURCE_TYPE_UNSPECIFIED",
		1:  "POD",
		2:  "DEPLOYMENT",
		3:  "SERVICE",
		4:  "CONFIGMAP",
		5:  "SECRET",
		6:  "NAMESPACE",
		7:  "NODE",
		8:  "PERSISTENTVOLUME",
		9:  "PERSISTENTVOLUMECLAIM",
		10: "STATEFULSET",
		11: "DAEMONSET",
		12: "JOB",
		13: "CRONJOB",
		14: "INGRESS",
		15: "NETWORKPOLICY",
		16: "RESOURCEQUOTA",
		17: "LIMITRANGE",
		18: "HORIZONTALPODAUTOSCALER",
		19: "STORAGECLASS",
		20: "ROLE",
		21: "ROLEBINDING",
		22: "CLUSTERROLE",
		23: "CLUSTERROLEBINDING",
		24: "SERVICEACCOUNT",
		25: "ENDPOINT",
		26: "ENDPOINTSLICE",
		27: "EVENT",
		28: "PRIORITYCLASS",
		29: "REPLICASET",
	}
	ResourceType_value = map[string]int32{
		"RESOURCE_TYPE_UNSPECIFIED": 0,
		"POD":                       1,
		"DEPLOYMENT":                2,
		"SERVICE":                   3,
		"CONFIGMAP":                 4,
		"SECRET":                    5,
		"NAMESPACE":                 6,
		"NODE":                      7,
		"PERSISTENTVOLUME":          8,
		"PERSISTENTVOLUMECLAIM":     9,
		"STATEFULSET":               10,
		"DAEMONSET":                 11,
		"JOB":                       12,
		"CRONJOB":                   13,
		"INGRESS":                   14,
		"NETWORKPOLICY":             15,
		"RESOURCEQUOTA":             16,
		"LIMITRANGE":                17,
		"HORIZONTALPODAUTOSCALER":   18,
		"STORAGECLASS":              19,
		"ROLE":                      20,
		"ROLEBINDING":               21,
		"CLUSTERROLE":               22,
		"CLUSTERROLEBINDING":        23,
		"SERVICEACCOUNT":            24,
		"ENDPOINT":                  25,
		"ENDPOINTSLICE":             26,
		"EVENT":                     27,
		"PRIORITYCLASS":             28,
		"REPLICASET":                29,
	}
)

func (x ResourceType) Enum() *ResourceType {
	p := new(ResourceType)
	*p = x
	return p
}

func (x ResourceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResourceType) Descriptor() protoreflect.EnumDescriptor {
	return file_cluster_v1_cluster_proto_enumTypes[1].Descriptor()
}

func (ResourceType) Type() protoreflect.EnumType {
	return &file_cluster_v1_cluster_proto_enumTypes[1]
}

func (x ResourceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResourceType.Descriptor instead.
func (ResourceType) EnumDescriptor() ([]byte, []int) {
	return file_cluster_v1_cluster_proto_rawDescGZIP(), []int{1}
}

// 事件类型
type EventType int32

const (
	EventType_EVENT_TYPE_UNSPECIFIED EventType = 0
	EventType_ADDED                  EventType = 1
	EventType_MODIFIED               EventType = 2
	EventType_DELETED                EventType = 3
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0: "EVENT_TYPE_UNSPECIFIED",
		1: "ADDED",
		2: "MODIFIED",
		3: "DELETED",
	}
	EventType_value = map[string]int32{
		"EVENT_TYPE_UNSPECIFIED": 0,
		"ADDED":                  1,
		"MODIFIED":               2,
		"DELETED":                3,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_cluster_v1_cluster_proto_enumTypes[2].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_cluster_v1_cluster_proto_enumTypes[2]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_cluster_v1_cluster_proto_rawDescGZIP(), []int{2}
}

// 集群信息
type Cluster struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	ApiServer     string                 `protobuf:"bytes,4,opt,name=api_server,json=apiServer,proto3" json:"api_server,omitempty"` // API Server地址
	Kubeconfig    string                 `protobuf:"bytes,5,opt,name=kubeconfig,proto3" json:"kubeconfig,omitempty"`                // Kubeconfig内容（base64编码）
	Version       string                 `protobuf:"bytes,6,opt,name=version,proto3" json:"version,omitempty"`                      // K8s版本
	Status        ClusterStatus          `protobuf:"varint,7,opt,name=status,proto3,enum=cluster.v1.ClusterStatus" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,10,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cluster) Reset() {
	*x = Cluster{}
	mi := &file_cluster_v1_cluster_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cluster) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cluster) ProtoMessage() {}

func (x *Cluster) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_v1_cluster_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cluster.ProtoReflect.Descriptor instead.
func (*Cluster) Descriptor() ([]byte, []int) {
	return file_cluster_v1_cluster_proto_rawDescGZIP(), []int{0}
}

func (x *Cluster) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Cluster) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Cluster) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Cluster) GetApiServer() string {
	if x != nil {
		return x.ApiServer
	}
	return ""
}

func (x *Cluster) GetKubeconfig() string {
	if x != nil {
		return x.Kubeconfig
	}
	return ""
}

func (x *Cluster) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Cluster) GetStatus() ClusterStatus {
	if x != nil {
		return x.Status
	}
	return ClusterStatus_CLUSTER_STATUS_UNSPECIFIED
}

func (x *Cluster) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Cluster) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Cluster) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

// 获取集群请求
type GetClusterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterId     string                 `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClusterRequest) Reset() {
	*x = GetClusterRequest{}
	mi := &file_cluster_v1_cluster_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClusterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClusterRequest) ProtoMessage() {}

func (x *GetClusterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_v1_cluster_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClusterRequest.ProtoReflect.Descriptor instead.
func (*GetClusterRequest) Descriptor() ([]byte, []int) {
	return file_cluster_v1_cluster_proto_rawDescGZIP(), []int{1}
}

func (x *GetClusterRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

// 列出集群请求
type ListClustersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *v1.PaginationRequest  `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Status        *ClusterStatus         `protobuf:"varint,2,opt,name=status,proto3,enum=cluster.v1.ClusterStatus,oneof" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListClustersRequest) Reset() {
	*x = ListClustersRequest{}
	mi := &file_cluster_v1_cluster_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListClustersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListClustersRequest) ProtoMessage() {}

func (x *ListClustersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_v1_cluster_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListClustersRequest.ProtoReflect.Descriptor instead.
func (*ListClustersRequest) Descriptor() ([]byte, []int) {
	return file_cluster_v1_cluster_proto_rawDescGZIP(), []int{2}
}

func (x *ListClustersRequest) GetPagination() *v1.PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListClustersRequest) GetStatus() ClusterStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ClusterStatus_CLUSTER_STATUS_UNSPECIFIED
}

// 列出集群响应
type ListClustersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Clusters      []*Cluster             `protobuf:"bytes,1,rep,name=clusters,proto3" json:"clusters,omitempty"`
	Pagination    *v1.PaginationMetadata `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListClustersResponse) Reset() {
	*x = ListClustersResponse{}
	mi := &file_cluster_v1_cluster_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListClustersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListClustersResponse) ProtoMessage() {}

func (x *ListClustersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_v1_cluster_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListClustersResponse.ProtoReflect.Descriptor instead.
func (*ListClustersResponse) Descriptor() ([]byte, []int) {
	return file_cluster_v1_cluster_proto_rawDescGZIP(), []int{3}
}

func (x *ListClustersResponse) GetClusters() []*Cluster {
	if x != nil {
		return x.Clusters
	}
	return nil
}

func (x *ListClustersResponse) GetPagination() *v1.PaginationMetadata {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// 创建集群请求
type CreateClusterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	ApiServer     string                 `protobuf:"bytes,3,opt,name=api_server,json=apiServer,proto3" json:"api_server,omitempty"`
	Kubeconfig    string                 `protobuf:"bytes,4,opt,name=kubeconfig,proto3" json:"kubeconfig,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,5,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateClusterRequest) Reset() {
	*x = CreateClusterRequest{}
	mi := &file_cluster_v1_cluster_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateClusterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateClusterRequest) ProtoMessage() {}

func (x *CreateClusterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_v1_cluster_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateClusterRequest.ProtoReflect.Descriptor instead.
func (*CreateClusterRequest) Descriptor() ([]byte, []int) {
	return file_cluster_v1_cluster_proto_rawDescGZIP(), []int{4}
}

func (x *CreateClusterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateClusterRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateClusterRequest) GetApiServer() string {
	if x != nil {
		return x.ApiServer
	}
	return ""
}

func (x *CreateClusterRequest) GetKubeconfig() string {
	if x != nil {
		return x.Kubeconfig
	}
	return ""
}

func (x *CreateClusterRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

// 更新集群请求
type UpdateClusterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterId     string                 `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	ApiServer     *string                `protobuf:"bytes,4,opt,name=api_server,json=apiServer,proto3,oneof" json:"api_server,omitempty"`
	Kubeconfig    *string                `protobuf:"bytes,5,opt,name=kubeconfig,proto3,oneof" json:"kubeconfig,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,6,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateClusterRequest) Reset() {
	*x = UpdateClusterRequest{}
	mi := &file_cluster_v1_cluster_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateClusterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateClusterRequest) ProtoMessage() {}

func (x *UpdateClusterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_v1_cluster_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateClusterRequest.ProtoReflect.Descriptor instead.
func (*UpdateClusterRequest) Descriptor() ([]byte, []int) {
	return file_cluster_v1_cluster_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateClusterRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *UpdateClusterRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateClusterRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateClusterRequest) GetApiServer() string {
	if x != nil && x.ApiServer != nil {
		return *x.ApiServer
	}
	return ""
}

func (x *UpdateClusterRequest) GetKubeconfig() string {
	if x != nil && x.Kubeconfig != nil {
		return *x.Kubeconfig
	}
	return ""
}

func (x *UpdateClusterRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

// 删除集群请求
type DeleteClusterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterId     string                 `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteClusterRequest) Reset() {
	*x = DeleteClusterRequest{}
	mi := &file_cluster_v1_cluster_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteClusterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteClusterRequest) ProtoMessage() {}

func (x *DeleteClusterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_v1_cluster_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteClusterRequest.ProtoReflect.Descriptor instead.
func (*DeleteClusterRequest) Descriptor() ([]byte, []int) {
	return file_cluster_v1_cluster_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteClusterRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

// 删除集群响应
type DeleteClusterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteClusterResponse) Reset() {
	*x = DeleteClusterResponse{}
	mi := &file_cluster_v1_cluster_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteClusterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteClusterResponse) ProtoMessage() {}

func (x *DeleteClusterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_v1_cluster_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteClusterResponse.ProtoReflect.Descriptor instead.
func (*DeleteClusterResponse) Descriptor() ([]byte, []int) {
	return file_cluster_v1_cluster_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteClusterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 获取集群健康请求
type GetClusterHealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterId     string                 `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClusterHealthRequest) Reset() {
	*x = GetClusterHealthRequest{}
	mi := &file_cluster_v1_cluster_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClusterHealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClusterHealthRequest) ProtoMessage() {}

func (x *GetClusterHealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_v1_cluster_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClusterHealthRequest.ProtoReflect.Descriptor instead.
func (*GetClusterHealthRequest) Descriptor() ([]byte, []int) {
	return file_cluster_v1_cluster_proto_rawDescGZIP(), []int{8}
}

func (x *GetClusterHealthRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

// 集群健康状态
type ClusterHealth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        ClusterStatus          `protobuf:"varint,1,opt,name=status,proto3,enum=cluster.v1.ClusterStatus" json:"status,omitempty"`
	Components    []*ComponentHealth     `protobuf:"bytes,2,rep,name=components,proto3" json:"components,omitempty"`
	Resources     *ClusterResources      `protobuf:"bytes,3,opt,name=resources,proto3" json:"resources,omitempty"`
	LastCheck     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=last_check,json=lastCheck,proto3" json:"last_check,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterHealth) Reset() {
	*x = ClusterHealth{}
	mi := &file_cluster_v1_cluster_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterHealth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterHealth) ProtoMessage() {}

func (x *ClusterHealth) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_v1_cluster_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterHealth.ProtoReflect.Descriptor instead.
func (*ClusterHealth) Descriptor() ([]byte, []int) {
	return file_cluster_v1_cluster_proto_rawDescGZIP(), []int{9}
}

func (x *ClusterHealth) GetStatus() ClusterStatus {
	if x != nil {
		return x.Status
	}
	return ClusterStatus_CLUSTER_STATUS_UNSPECIFIED
}

func (x *ClusterHealth) GetComponents() []*ComponentHealth {
	if x != nil {
		return x.Components
	}
	return nil
}

func (x *ClusterHealth) GetResources() *ClusterResources {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *ClusterHealth) GetLastCheck() *timestamppb.Timestamp {
	if x != nil {
		return x.LastCheck
	}
	return nil
}

// 组件健康状态
type ComponentHealth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // kube-apiserver, kube-controller-manager, etc.
	Healthy       bool                   `protobuf:"varint,2,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComponentHealth) Reset() {
	*x = ComponentHealth{}
	mi := &file_cluster_v1_cluster_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComponentHealth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComponentHealth) ProtoMessage() {}

func (x *ComponentHealth) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_v1_cluster_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComponentHealth.ProtoReflect.Descriptor instead.
func (*ComponentHealth) Descriptor() ([]byte, []int) {
	return file_cluster_v1_cluster_proto_rawDescGZIP(), []int{10}
}

func (x *ComponentHealth) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ComponentHealth) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *ComponentHealth) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 集群资源
type ClusterResources struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NodeCount       int32                  `protobuf:"varint,1,opt,name=node_count,json=nodeCount,proto3" json:"node_count,omitempty"`
	NamespaceCount  int32                  `protobuf:"varint,2,opt,name=namespace_count,json=namespaceCount,proto3" json:"namespace_count,omitempty"`
	PodCount        int32                  `protobuf:"varint,3,opt,name=pod_count,json=podCount,proto3" json:"pod_count,omitempty"`
	ServiceCount    int32                  `protobuf:"varint,4,opt,name=service_count,json=serviceCount,proto3" json:"service_count,omitempty"`
	DeploymentCount int32                  `protobuf:"varint,5,opt,name=deployment_count,json=deploymentCount,proto3" json:"deployment_count,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ClusterResources) Reset() {
	*x = ClusterResources{}
	mi := &file_cluster_v1_cluster_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterResources) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterResources) ProtoMessage() {}

func (x *ClusterResources) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_v1_cluster_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterResources.ProtoReflect.Descriptor instead.
func (*ClusterResources) Descriptor() ([]byte, []int) {
	return file_cluster_v1_cluster_proto_rawDescGZIP(), []int{11}
}

func (x *ClusterResources) GetNodeCount() int32 {
	if x != nil {
		return x.NodeCount
	}
	return 0
}

func (x *ClusterResources) GetNamespaceCount() int32 {
	if x != nil {
		return x.NamespaceCount
	}
	return 0
}

func (x *ClusterResources) GetPodCount() int32 {
	if x != nil {
		return x.PodCount
	}
	return 0
}

func (x *ClusterResources) GetServiceCount() int32 {
	if x != nil {
		return x.ServiceCount
	}
	return 0
}

func (x *ClusterResources) GetDeploymentCount() int32 {
	if x != nil {
		return x.DeploymentCount
	}
	return 0
}

// 获取集群版本请求
type GetClusterVersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterId     string                 `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClusterVersionRequest) Reset() {
	*x = GetClusterVersionRequest{}
	mi := &file_cluster_v1_cluster_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClusterVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClusterVersionRequest) ProtoMessage() {}

func (x *GetClusterVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_v1_cluster_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClusterVersionRequest.ProtoReflect.Descriptor instead.
func (*GetClusterVersionRequest) Descriptor() ([]byte, []int) {
	return file_cluster_v1_cluster_proto_rawDescGZIP(), []int{12}
}

func (x *GetClusterVersionRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

// 集群版本
type ClusterVersion struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	KubernetesVersion string                 `protobuf:"bytes,1,opt,name=kubernetes_version,json=kubernetesVersion,proto3" json:"kubernetes_version,omitempty"`
	GitVersion        string                 `protobuf:"bytes,2,opt,name=git_version,json=gitVersion,proto3" json:"git_version,omitempty"`
	Platform          string                 `protobuf:"bytes,3,opt,name=platform,proto3" json:"platform,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ClusterVersion) Reset() {
	*x = ClusterVersion{}
	mi := &file_cluster_v1_cluster_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterVersion) ProtoMessage() {}

func (x *ClusterVersion) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_v1_cluster_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterVersion.ProtoReflect.Descriptor instead.
func (*ClusterVersion) Descriptor() ([]byte, []int) {
	return file_cluster_v1_cluster_proto_rawDescGZIP(), []int{13}
}

func (x *ClusterVersion) GetKubernetesVersion() string {
	if x != nil {
		return x.KubernetesVersion
	}
	return ""
}

func (x *ClusterVersion) GetGitVersion() string {
	if x != nil {
		return x.GitVersion
	}
	return ""
}

func (x *ClusterVersion) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

// K8s资源
type Resource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterId     string                 `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	Type          ResourceType           `protobuf:"varint,2,opt,name=type,proto3,enum=cluster.v1.ResourceType" json:"type,omitempty"`
	Namespace     string                 `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Spec          *structpb.Struct       `protobuf:"bytes,5,opt,name=spec,proto3" json:"spec,omitempty"`     // 资源规格（JSON格式）
	Status        *structpb.Struct       `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"` // 资源状态（JSON格式）
	Labels        map[string]string      `protobuf:"bytes,7,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Annotations   map[string]string      `protobuf:"bytes,8,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resource) Reset() {
	*x = Resource{}
	mi := &file_cluster_v1_cluster_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resource) ProtoMessage() {}

func (x *Resource) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_v1_cluster_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resource.ProtoReflect.Descriptor instead.
func (*Resource) Descriptor() ([]byte, []int) {
	return file_cluster_v1_cluster_proto_rawDescGZIP(), []int{14}
}

func (x *Resource) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *Resource) GetType() ResourceType {
	if x != nil {
		return x.Type
	}
	return ResourceType_RESOURCE_TYPE_UNSPECIFIED
}

func (x *Resource) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Resource) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Resource) GetSpec() *structpb.Struct {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *Resource) GetStatus() *structpb.Struct {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *Resource) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Resource) GetAnnotations() map[string]string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *Resource) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// 获取资源请求
type GetResourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterId     string                 `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	ResourceType  ResourceType           `protobuf:"varint,2,opt,name=resource_type,json=resourceType,proto3,enum=cluster.v1.ResourceType" json:"resource_type,omitempty"`
	Namespace     string                 `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResourceRequest) Reset() {
	*x = GetResourceRequest{}
	mi := &file_cluster_v1_cluster_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResourceRequest) ProtoMessage() {}

func (x *GetResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_v1_cluster_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResourceRequest.ProtoReflect.Descriptor instead.
func (*GetResourceRequest) Descriptor() ([]byte, []int) {
	return file_cluster_v1_cluster_proto_rawDescGZIP(), []int{15}
}

func (x *GetResourceRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *GetResourceRequest) GetResourceType() ResourceType {
	if x != nil {
		return x.ResourceType
	}
	return ResourceType_RESOURCE_TYPE_UNSPECIFIED
}

func (x *GetResourceRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *GetResourceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// 列出资源请求
type ListResourcesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterId     string                 `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	ResourceType  ResourceType           `protobuf:"varint,2,opt,name=resource_type,json=resourceType,proto3,enum=cluster.v1.ResourceType" json:"resource_type,omitempty"`
	Namespace     *string                `protobuf:"bytes,3,opt,name=namespace,proto3,oneof" json:"namespace,omitempty"`                              // 空表示所有命名空间
	LabelSelector *string                `protobuf:"bytes,4,opt,name=label_selector,json=labelSelector,proto3,oneof" json:"label_selector,omitempty"` // 标签选择器
	Pagination    *v1.PaginationRequest  `protobuf:"bytes,5,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResourcesRequest) Reset() {
	*x = ListResourcesRequest{}
	mi := &file_cluster_v1_cluster_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResourcesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResourcesRequest) ProtoMessage() {}

func (x *ListResourcesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_v1_cluster_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResourcesRequest.ProtoReflect.Descriptor instead.
func (*ListResourcesRequest) Descriptor() ([]byte, []int) {
	return file_cluster_v1_cluster_proto_rawDescGZIP(), []int{16}
}

func (x *ListResourcesRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *ListResourcesRequest) GetResourceType() ResourceType {
	if x != nil {
		return x.ResourceType
	}
	return ResourceType_RESOURCE_TYPE_UNSPECIFIED
}

func (x *ListResourcesRequest) GetNamespace() string {
	if x != nil && x.Namespace != nil {
		return *x.Namespace
	}
	return ""
}

func (x *ListResourcesRequest) GetLabelSelector() string {
	if x != nil && x.LabelSelector != nil {
		return *x.LabelSelector
	}
	return ""
}

func (x *ListResourcesRequest) GetPagination() *v1.PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// 列出资源响应
type ListResourcesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resources     []*Resource            `protobuf:"bytes,1,rep,name=resources,proto3" json:"resources,omitempty"`
	Pagination    *v1.PaginationMetadata `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResourcesResponse) Reset() {
	*x = ListResourcesResponse{}
	mi := &file_cluster_v1_cluster_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResourcesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResourcesResponse) ProtoMessage() {}

func (x *ListResourcesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_v1_cluster_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResourcesResponse.ProtoReflect.Descriptor instead.
func (*ListResourcesResponse) Descriptor() ([]byte, []int) {
	return file_cluster_v1_cluster_proto_rawDescGZIP(), []int{17}
}

func (x *ListResourcesResponse) GetResources() []*Resource {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *ListResourcesResponse) GetPagination() *v1.PaginationMetadata {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// 创建资源请求
type CreateResourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterId     string                 `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	ResourceType  ResourceType           `protobuf:"varint,2,opt,name=resource_type,json=resourceType,proto3,enum=cluster.v1.ResourceType" json:"resource_type,omitempty"`
	Namespace     string                 `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Spec          *structpb.Struct       `protobuf:"bytes,4,opt,name=spec,proto3" json:"spec,omitempty"` // 资源规格（JSON格式）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResourceRequest) Reset() {
	*x = CreateResourceRequest{}
	mi := &file_cluster_v1_cluster_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResourceRequest) ProtoMessage() {}

func (x *CreateResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_v1_cluster_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResourceRequest.ProtoReflect.Descriptor instead.
func (*CreateResourceRequest) Descriptor() ([]byte, []int) {
	return file_cluster_v1_cluster_proto_rawDescGZIP(), []int{18}
}

func (x *CreateResourceRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *CreateResourceRequest) GetResourceType() ResourceType {
	if x != nil {
		return x.ResourceType
	}
	return ResourceType_RESOURCE_TYPE_UNSPECIFIED
}

func (x *CreateResourceRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *CreateResourceRequest) GetSpec() *structpb.Struct {
	if x != nil {
		return x.Spec
	}
	return nil
}

// 更新资源请求
type UpdateResourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterId     string                 `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	ResourceType  ResourceType           `protobuf:"varint,2,opt,name=resource_type,json=resourceType,proto3,enum=cluster.v1.ResourceType" json:"resource_type,omitempty"`
	Namespace     string                 `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Spec          *structpb.Struct       `protobuf:"bytes,5,opt,name=spec,proto3" json:"spec,omitempty"` // 资源规格（JSON格式）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResourceRequest) Reset() {
	*x = UpdateResourceRequest{}
	mi := &file_cluster_v1_cluster_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResourceRequest) ProtoMessage() {}

func (x *UpdateResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_v1_cluster_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResourceRequest.ProtoReflect.Descriptor instead.
func (*UpdateResourceRequest) Descriptor() ([]byte, []int) {
	return file_cluster_v1_cluster_proto_rawDescGZIP(), []int{19}
}

func (x *UpdateResourceRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *UpdateResourceRequest) GetResourceType() ResourceType {
	if x != nil {
		return x.ResourceType
	}
	return ResourceType_RESOURCE_TYPE_UNSPECIFIED
}

func (x *UpdateResourceRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *UpdateResourceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateResourceRequest) GetSpec() *structpb.Struct {
	if x != nil {
		return x.Spec
	}
	return nil
}

// 删除资源请求
type DeleteResourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterId     string                 `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	ResourceType  ResourceType           `protobuf:"varint,2,opt,name=resource_type,json=resourceType,proto3,enum=cluster.v1.ResourceType" json:"resource_type,omitempty"`
	Namespace     string                 `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResourceRequest) Reset() {
	*x = DeleteResourceRequest{}
	mi := &file_cluster_v1_cluster_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResourceRequest) ProtoMessage() {}

func (x *DeleteResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_v1_cluster_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResourceRequest.ProtoReflect.Descriptor instead.
func (*DeleteResourceRequest) Descriptor() ([]byte, []int) {
	return file_cluster_v1_cluster_proto_rawDescGZIP(), []int{20}
}

func (x *DeleteResourceRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *DeleteResourceRequest) GetResourceType() ResourceType {
	if x != nil {
		return x.ResourceType
	}
	return ResourceType_RESOURCE_TYPE_UNSPECIFIED
}

func (x *DeleteResourceRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *DeleteResourceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// 删除资源响应
type DeleteResourceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResourceResponse) Reset() {
	*x = DeleteResourceResponse{}
	mi := &file_cluster_v1_cluster_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResourceResponse) ProtoMessage() {}

func (x *DeleteResourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_v1_cluster_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResourceResponse.ProtoReflect.Descriptor instead.
func (*DeleteResourceResponse) Descriptor() ([]byte, []int) {
	return file_cluster_v1_cluster_proto_rawDescGZIP(), []int{21}
}

func (x *DeleteResourceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 监听资源请求
type WatchResourcesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterId     string                 `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	ResourceType  ResourceType           `protobuf:"varint,2,opt,name=resource_type,json=resourceType,proto3,enum=cluster.v1.ResourceType" json:"resource_type,omitempty"`
	Namespace     *string                `protobuf:"bytes,3,opt,name=namespace,proto3,oneof" json:"namespace,omitempty"`
	LabelSelector *string                `protobuf:"bytes,4,opt,name=label_selector,json=labelSelector,proto3,oneof" json:"label_selector,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchResourcesRequest) Reset() {
	*x = WatchResourcesRequest{}
	mi := &file_cluster_v1_cluster_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchResourcesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchResourcesRequest) ProtoMessage() {}

func (x *WatchResourcesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_v1_cluster_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchResourcesRequest.ProtoReflect.Descriptor instead.
func (*WatchResourcesRequest) Descriptor() ([]byte, []int) {
	return file_cluster_v1_cluster_proto_rawDescGZIP(), []int{22}
}

func (x *WatchResourcesRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *WatchResourcesRequest) GetResourceType() ResourceType {
	if x != nil {
		return x.ResourceType
	}
	return ResourceType_RESOURCE_TYPE_UNSPECIFIED
}

func (x *WatchResourcesRequest) GetNamespace() string {
	if x != nil && x.Namespace != nil {
		return *x.Namespace
	}
	return ""
}

func (x *WatchResourcesRequest) GetLabelSelector() string {
	if x != nil && x.LabelSelector != nil {
		return *x.LabelSelector
	}
	return ""
}

// 资源事件
type ResourceEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          EventType              `protobuf:"varint,1,opt,name=type,proto3,enum=cluster.v1.EventType" json:"type,omitempty"`
	Resource      *Resource              `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceEvent) Reset() {
	*x = ResourceEvent{}
	mi := &file_cluster_v1_cluster_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceEvent) ProtoMessage() {}

func (x *ResourceEvent) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_v1_cluster_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceEvent.ProtoReflect.Descriptor instead.
func (*ResourceEvent) Descriptor() ([]byte, []int) {
	return file_cluster_v1_cluster_proto_rawDescGZIP(), []int{23}
}

func (x *ResourceEvent) GetType() EventType {
	if x != nil {
		return x.Type
	}
	return EventType_EVENT_TYPE_UNSPECIFIED
}

func (x *ResourceEvent) GetResource() *Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

var File_cluster_v1_cluster_proto protoreflect.FileDescriptor

const file_cluster_v1_cluster_proto_rawDesc = "" +
	"\n" +
	"\x18cluster/v1/cluster.proto\x12\n" +
	"cluster.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1cgoogle/api/annotations.proto\x1a%common/pagination/v1/pagination.proto\"\xc5\x03\n" +
	"\aCluster\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"api_server\x18\x04 \x01(\tR\tapiServer\x12\x1e\n" +
	"\n" +
	"kubeconfig\x18\x05 \x01(\tR\n" +
	"kubeconfig\x12\x18\n" +
	"\aversion\x18\x06 \x01(\tR\aversion\x121\n" +
	"\x06status\x18\a \x01(\x0e2\x19.cluster.v1.ClusterStatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x127\n" +
	"\x06labels\x18\n" +
	" \x03(\v2\x1f.cluster.v1.Cluster.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"2\n" +
	"\x11GetClusterRequest\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\"\xa1\x01\n" +
	"\x13ListClustersRequest\x12G\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2'.common.pagination.v1.PaginationRequestR\n" +
	"pagination\x126\n" +
	"\x06status\x18\x02 \x01(\x0e2\x19.cluster.v1.ClusterStatusH\x00R\x06status\x88\x01\x01B\t\n" +
	"\a_status\"\x91\x01\n" +
	"\x14ListClustersResponse\x12/\n" +
	"\bclusters\x18\x01 \x03(\v2\x13.cluster.v1.ClusterR\bclusters\x12H\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2(.common.pagination.v1.PaginationMetadataR\n" +
	"pagination\"\x8c\x02\n" +
	"\x14CreateClusterRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"api_server\x18\x03 \x01(\tR\tapiServer\x12\x1e\n" +
	"\n" +
	"kubeconfig\x18\x04 \x01(\tR\n" +
	"kubeconfig\x12D\n" +
	"\x06labels\x18\x05 \x03(\v2,.cluster.v1.CreateClusterRequest.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf6\x02\n" +
	"\x14UpdateClusterRequest\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x01R\vdescription\x88\x01\x01\x12\"\n" +
	"\n" +
	"api_server\x18\x04 \x01(\tH\x02R\tapiServer\x88\x01\x01\x12#\n" +
	"\n" +
	"kubeconfig\x18\x05 \x01(\tH\x03R\n" +
	"kubeconfig\x88\x01\x01\x12D\n" +
	"\x06labels\x18\x06 \x03(\v2,.cluster.v1.UpdateClusterRequest.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\a\n" +
	"\x05_nameB\x0e\n" +
	"\f_descriptionB\r\n" +
	"\v_api_serverB\r\n" +
	"\v_kubeconfig\"5\n" +
	"\x14DeleteClusterRequest\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\"1\n" +
	"\x15DeleteClusterResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"8\n" +
	"\x17GetClusterHealthRequest\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\"\xf6\x01\n" +
	"\rClusterHealth\x121\n" +
	"\x06status\x18\x01 \x01(\x0e2\x19.cluster.v1.ClusterStatusR\x06status\x12;\n" +
	"\n" +
	"components\x18\x02 \x03(\v2\x1b.cluster.v1.ComponentHealthR\n" +
	"components\x12:\n" +
	"\tresources\x18\x03 \x01(\v2\x1c.cluster.v1.ClusterResourcesR\tresources\x129\n" +
	"\n" +
	"last_check\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tlastCheck\"Y\n" +
	"\x0fComponentHealth\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\ahealthy\x18\x02 \x01(\bR\ahealthy\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xc7\x01\n" +
	"\x10ClusterResources\x12\x1d\n" +
	"\n" +
	"node_count\x18\x01 \x01(\x05R\tnodeCount\x12'\n" +
	"\x0fnamespace_count\x18\x02 \x01(\x05R\x0enamespaceCount\x12\x1b\n" +
	"\tpod_count\x18\x03 \x01(\x05R\bpodCount\x12#\n" +
	"\rservice_count\x18\x04 \x01(\x05R\fserviceCount\x12)\n" +
	"\x10deployment_count\x18\x05 \x01(\x05R\x0fdeploymentCount\"9\n" +
	"\x18GetClusterVersionRequest\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\"|\n" +
	"\x0eClusterVersion\x12-\n" +
	"\x12kubernetes_version\x18\x01 \x01(\tR\x11kubernetesVersion\x12\x1f\n" +
	"\vgit_version\x18\x02 \x01(\tR\n" +
	"gitVersion\x12\x1a\n" +
	"\bplatform\x18\x03 \x01(\tR\bplatform\"\xa0\x04\n" +
	"\bResource\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\x12,\n" +
	"\x04type\x18\x02 \x01(\x0e2\x18.cluster.v1.ResourceTypeR\x04type\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12+\n" +
	"\x04spec\x18\x05 \x01(\v2\x17.google.protobuf.StructR\x04spec\x12/\n" +
	"\x06status\x18\x06 \x01(\v2\x17.google.protobuf.StructR\x06status\x128\n" +
	"\x06labels\x18\a \x03(\v2 .cluster.v1.Resource.LabelsEntryR\x06labels\x12G\n" +
	"\vannotations\x18\b \x03(\v2%.cluster.v1.Resource.AnnotationsEntryR\vannotations\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a>\n" +
	"\x10AnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa4\x01\n" +
	"\x12GetResourceRequest\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\x12=\n" +
	"\rresource_type\x18\x02 \x01(\x0e2\x18.cluster.v1.ResourceTypeR\fresourceType\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\"\xad\x02\n" +
	"\x14ListResourcesRequest\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\x12=\n" +
	"\rresource_type\x18\x02 \x01(\x0e2\x18.cluster.v1.ResourceTypeR\fresourceType\x12!\n" +
	"\tnamespace\x18\x03 \x01(\tH\x00R\tnamespace\x88\x01\x01\x12*\n" +
	"\x0elabel_selector\x18\x04 \x01(\tH\x01R\rlabelSelector\x88\x01\x01\x12G\n" +
	"\n" +
	"pagination\x18\x05 \x01(\v2'.common.pagination.v1.PaginationRequestR\n" +
	"paginationB\f\n" +
	"\n" +
	"_namespaceB\x11\n" +
	"\x0f_label_selector\"\x95\x01\n" +
	"\x15ListResourcesResponse\x122\n" +
	"\tresources\x18\x01 \x03(\v2\x14.cluster.v1.ResourceR\tresources\x12H\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2(.common.pagination.v1.PaginationMetadataR\n" +
	"pagination\"\xc0\x01\n" +
	"\x15CreateResourceRequest\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\x12=\n" +
	"\rresource_type\x18\x02 \x01(\x0e2\x18.cluster.v1.ResourceTypeR\fresourceType\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x12+\n" +
	"\x04spec\x18\x04 \x01(\v2\x17.google.protobuf.StructR\x04spec\"\xd4\x01\n" +
	"\x15UpdateResourceRequest\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\x12=\n" +
	"\rresource_type\x18\x02 \x01(\x0e2\x18.cluster.v1.ResourceTypeR\fresourceType\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12+\n" +
	"\x04spec\x18\x05 \x01(\v2\x17.google.protobuf.StructR\x04spec\"\xa7\x01\n" +
	"\x15DeleteResourceRequest\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\x12=\n" +
	"\rresource_type\x18\x02 \x01(\x0e2\x18.cluster.v1.ResourceTypeR\fresourceType\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\"2\n" +
	"\x16DeleteResourceResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\xe5\x01\n" +
	"\x15WatchResourcesRequest\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\x12=\n" +
	"\rresource_type\x18\x02 \x01(\x0e2\x18.cluster.v1.ResourceTypeR\fresourceType\x12!\n" +
	"\tnamespace\x18\x03 \x01(\tH\x00R\tnamespace\x88\x01\x01\x12*\n" +
	"\x0elabel_selector\x18\x04 \x01(\tH\x01R\rlabelSelector\x88\x01\x01B\f\n" +
	"\n" +
	"_namespaceB\x11\n" +
	"\x0f_label_selector\"l\n" +
	"\rResourceEvent\x12)\n" +
	"\x04type\x18\x01 \x01(\x0e2\x15.cluster.v1.EventTypeR\x04type\x120\n" +
	"\bresource\x18\x02 \x01(\v2\x14.cluster.v1.ResourceR\bresource*i\n" +
	"\rClusterStatus\x12\x1e\n" +
	"\x1aCLUSTER_STATUS_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aHEALTHY\x10\x01\x12\r\n" +
	"\tUNHEALTHY\x10\x02\x12\x0f\n" +
	"\vUNREACHABLE\x10\x03\x12\v\n" +
	"\aUNKNOWN\x10\x04*\x87\x04\n" +
	"\fResourceType\x12\x1d\n" +
	"\x19RESOURCE_TYPE_UNSPECIFIED\x10\x00\x12\a\n" +
	"\x03POD\x10\x01\x12\x0e\n" +
	"\n" +
	"DEPLOYMENT\x10\x02\x12\v\n" +
	"\aSERVICE\x10\x03\x12\r\n" +
	"\tCONFIGMAP\x10\x04\x12\n" +
	"\n" +
	"\x06SECRET\x10\x05\x12\r\n" +
	"\tNAMESPACE\x10\x06\x12\b\n" +
	"\x04NODE\x10\a\x12\x14\n" +
	"\x10PERSISTENTVOLUME\x10\b\x12\x19\n" +
	"\x15PERSISTENTVOLUMECLAIM\x10\t\x12\x0f\n" +
	"\vSTATEFULSET\x10\n" +
	"\x12\r\n" +
	"\tDAEMONSET\x10\v\x12\a\n" +
	"\x03JOB\x10\f\x12\v\n" +
	"\aCRONJOB\x10\r\x12\v\n" +
	"\aINGRESS\x10\x0e\x12\x11\n" +
	"\rNETWORKPOLICY\x10\x0f\x12\x11\n" +
	"\rRESOURCEQUOTA\x10\x10\x12\x0e\n" +
	"\n" +
	"LIMITRANGE\x10\x11\x12\x1b\n" +
	"\x17HORIZONTALPODAUTOSCALER\x10\x12\x12\x10\n" +
	"\fSTORAGECLASS\x10\x13\x12\b\n" +
	"\x04ROLE\x10\x14\x12\x0f\n" +
	"\vROLEBINDING\x10\x15\x12\x0f\n" +
	"\vCLUSTERROLE\x10\x16\x12\x16\n" +
	"\x12CLUSTERROLEBINDING\x10\x17\x12\x12\n" +
	"\x0eSERVICEACCOUNT\x10\x18\x12\f\n" +
	"\bENDPOINT\x10\x19\x12\x11\n" +
	"\rENDPOINTSLICE\x10\x1a\x12\t\n" +
	"\x05EVENT\x10\x1b\x12\x11\n" +
	"\rPRIORITYCLASS\x10\x1c\x12\x0e\n" +
	"\n" +
	"REPLICASET\x10\x1d*M\n" +
	"\tEventType\x12\x1a\n" +
	"\x16EVENT_TYPE_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05ADDED\x10\x01\x12\f\n" +
	"\bMODIFIED\x10\x02\x12\v\n" +
	"\aDELETED\x10\x032\xc4\x06\n" +
	"\x0eClusterService\x12g\n" +
	"\n" +
	"GetCluster\x12\x1d.cluster.v1.GetClusterRequest\x1a\x13.cluster.v1.Cluster\"%\x82\xd3\xe4\x93\x02\x1f\x12\x1d/api/v1/clusters/{cluster_id}\x12k\n" +
	"\fListClusters\x12\x1f.cluster.v1.ListClustersRequest\x1a .cluster.v1.ListClustersResponse\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/api/v1/clusters\x12c\n" +
	"\rCreateCluster\x12 .cluster.v1.CreateClusterRequest\x1a\x13.cluster.v1.Cluster\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/api/v1/clusters\x12p\n" +
	"\rUpdateCluster\x12 .cluster.v1.UpdateClusterRequest\x1a\x13.cluster.v1.Cluster\"(\x82\xd3\xe4\x93\x02\":\x01*\x1a\x1d/api/v1/clusters/{cluster_id}\x12{\n" +
	"\rDeleteCluster\x12 .cluster.v1.DeleteClusterRequest\x1a!.cluster.v1.DeleteClusterResponse\"%\x82\xd3\xe4\x93\x02\x1f*\x1d/api/v1/clusters/{cluster_id}\x12\x80\x01\n" +
	"\x10GetClusterHealth\x12#.cluster.v1.GetClusterHealthRequest\x1a\x19.cluster.v1.ClusterHealth\",\x82\xd3\xe4\x93\x02&\x12$/api/v1/clusters/{cluster_id}/health\x12\x84\x01\n" +
	"\x11GetClusterVersion\x12$.cluster.v1.GetClusterVersionRequest\x1a\x1a.cluster.v1.ClusterVersion\"-\x82\xd3\xe4\x93\x02'\x12%/api/v1/clusters/{cluster_id}/version2\xc1\a\n" +
	"\x12K8sResourceService\x12\x97\x01\n" +
	"\vGetResource\x12\x1e.cluster.v1.GetResourceRequest\x1a\x14.cluster.v1.Resource\"R\x82\xd3\xe4\x93\x02L\x12J/api/v1/clusters/{cluster_id}/resources/{resource_type}/{namespace}/{name}\x12\x95\x01\n" +
	"\rListResources\x12 .cluster.v1.ListResourcesRequest\x1a!.cluster.v1.ListResourcesResponse\"?\x82\xd3\xe4\x93\x029\x127/api/v1/clusters/{cluster_id}/resources/{resource_type}\x12\x8d\x01\n" +
	"\x0eCreateResource\x12!.cluster.v1.CreateResourceRequest\x1a\x14.cluster.v1.Resource\"B\x82\xd3\xe4\x93\x02<:\x01*\"7/api/v1/clusters/{cluster_id}/resources/{resource_type}\x12\xa0\x01\n" +
	"\x0eUpdateResource\x12!.cluster.v1.UpdateResourceRequest\x1a\x14.cluster.v1.Resource\"U\x82\xd3\xe4\x93\x02O:\x01*\x1aJ/api/v1/clusters/{cluster_id}/resources/{resource_type}/{namespace}/{name}\x12\xab\x01\n" +
	"\x0eDeleteResource\x12!.cluster.v1.DeleteResourceRequest\x1a\".cluster.v1.DeleteResourceResponse\"R\x82\xd3\xe4\x93\x02L*J/api/v1/clusters/{cluster_id}/resources/{resource_type}/{namespace}/{name}\x12\x97\x01\n" +
	"\x0eWatchResources\x12!.cluster.v1.WatchResourcesRequest\x1a\x19.cluster.v1.ResourceEvent\"E\x82\xd3\xe4\x93\x02?\x12=/api/v1/clusters/{cluster_id}/resources/{resource_type}/watch0\x01B\xa2\x01\n" +
	"\x0ecom.cluster.v1B\fClusterProtoP\x01Z9github.com/kart-io/k8s-agent/pkg/api/cluster/v1;clusterv1\xa2\x02\x03CXX\xaa\x02\n" +
	"Cluster.V1\xca\x02\n" +
	"Cluster\\V1\xe2\x02\x16Cluster\\V1\\GPBMetadata\xea\x02\vCluster::V1b\x06proto3"

var (
	file_cluster_v1_cluster_proto_rawDescOnce sync.Once
	file_cluster_v1_cluster_proto_rawDescData []byte
)

func file_cluster_v1_cluster_proto_rawDescGZIP() []byte {
	file_cluster_v1_cluster_proto_rawDescOnce.Do(func() {
		file_cluster_v1_cluster_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cluster_v1_cluster_proto_rawDesc), len(file_cluster_v1_cluster_proto_rawDesc)))
	})
	return file_cluster_v1_cluster_proto_rawDescData
}

var file_cluster_v1_cluster_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_cluster_v1_cluster_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_cluster_v1_cluster_proto_goTypes = []any{
	(ClusterStatus)(0),               // 0: cluster.v1.ClusterStatus
	(ResourceType)(0),                // 1: cluster.v1.ResourceType
	(EventType)(0),                   // 2: cluster.v1.EventType
	(*Cluster)(nil),                  // 3: cluster.v1.Cluster
	(*GetClusterRequest)(nil),        // 4: cluster.v1.GetClusterRequest
	(*ListClustersRequest)(nil),      // 5: cluster.v1.ListClustersRequest
	(*ListClustersResponse)(nil),     // 6: cluster.v1.ListClustersResponse
	(*CreateClusterRequest)(nil),     // 7: cluster.v1.CreateClusterRequest
	(*UpdateClusterRequest)(nil),     // 8: cluster.v1.UpdateClusterRequest
	(*DeleteClusterRequest)(nil),     // 9: cluster.v1.DeleteClusterRequest
	(*DeleteClusterResponse)(nil),    // 10: cluster.v1.DeleteClusterResponse
	(*GetClusterHealthRequest)(nil),  // 11: cluster.v1.GetClusterHealthRequest
	(*ClusterHealth)(nil),            // 12: cluster.v1.ClusterHealth
	(*ComponentHealth)(nil),          // 13: cluster.v1.ComponentHealth
	(*ClusterResources)(nil),         // 14: cluster.v1.ClusterResources
	(*GetClusterVersionRequest)(nil), // 15: cluster.v1.GetClusterVersionRequest
	(*ClusterVersion)(nil),           // 16: cluster.v1.ClusterVersion
	(*Resource)(nil),                 // 17: cluster.v1.Resource
	(*GetResourceRequest)(nil),       // 18: cluster.v1.GetResourceRequest
	(*ListResourcesRequest)(nil),     // 19: cluster.v1.ListResourcesRequest
	(*ListResourcesResponse)(nil),    // 20: cluster.v1.ListResourcesResponse
	(*CreateResourceRequest)(nil),    // 21: cluster.v1.CreateResourceRequest
	(*UpdateResourceRequest)(nil),    // 22: cluster.v1.UpdateResourceRequest
	(*DeleteResourceRequest)(nil),    // 23: cluster.v1.DeleteResourceRequest
	(*DeleteResourceResponse)(nil),   // 24: cluster.v1.DeleteResourceResponse
	(*WatchResourcesRequest)(nil),    // 25: cluster.v1.WatchResourcesRequest
	(*ResourceEvent)(nil),            // 26: cluster.v1.ResourceEvent
	nil,                              // 27: cluster.v1.Cluster.LabelsEntry
	nil,                              // 28: cluster.v1.CreateClusterRequest.LabelsEntry
	nil,                              // 29: cluster.v1.UpdateClusterRequest.LabelsEntry
	nil,                              // 30: cluster.v1.Resource.LabelsEntry
	nil,                              // 31: cluster.v1.Resource.AnnotationsEntry
	(*timestamppb.Timestamp)(nil),    // 32: google.protobuf.Timestamp
	(*v1.PaginationRequest)(nil),     // 33: common.pagination.v1.PaginationRequest
	(*v1.PaginationMetadata)(nil),    // 34: common.pagination.v1.PaginationMetadata
	(*structpb.Struct)(nil),          // 35: google.protobuf.Struct
}
var file_cluster_v1_cluster_proto_depIdxs = []int32{
	0,  // 0: cluster.v1.Cluster.status:type_name -> cluster.v1.ClusterStatus
	32, // 1: cluster.v1.Cluster.created_at:type_name -> google.protobuf.Timestamp
	32, // 2: cluster.v1.Cluster.updated_at:type_name -> google.protobuf.Timestamp
	27, // 3: cluster.v1.Cluster.labels:type_name -> cluster.v1.Cluster.LabelsEntry
	33, // 4: cluster.v1.ListClustersRequest.pagination:type_name -> common.pagination.v1.PaginationRequest
	0,  // 5: cluster.v1.ListClustersRequest.status:type_name -> cluster.v1.ClusterStatus
	3,  // 6: cluster.v1.ListClustersResponse.clusters:type_name -> cluster.v1.Cluster
	34, // 7: cluster.v1.ListClustersResponse.pagination:type_name -> common.pagination.v1.PaginationMetadata
	28, // 8: cluster.v1.CreateClusterRequest.labels:type_name -> cluster.v1.CreateClusterRequest.LabelsEntry
	29, // 9: cluster.v1.UpdateClusterRequest.labels:type_name -> cluster.v1.UpdateClusterRequest.LabelsEntry
	0,  // 10: cluster.v1.ClusterHealth.status:type_name -> cluster.v1.ClusterStatus
	13, // 11: cluster.v1.ClusterHealth.components:type_name -> cluster.v1.ComponentHealth
	14, // 12: cluster.v1.ClusterHealth.resources:type_name -> cluster.v1.ClusterResources
	32, // 13: cluster.v1.ClusterHealth.last_check:type_name -> google.protobuf.Timestamp
	1,  // 14: cluster.v1.Resource.type:type_name -> cluster.v1.ResourceType
	35, // 15: cluster.v1.Resource.spec:type_name -> google.protobuf.Struct
	35, // 16: cluster.v1.Resource.status:type_name -> google.protobuf.Struct
	30, // 17: cluster.v1.Resource.labels:type_name -> cluster.v1.Resource.LabelsEntry
	31, // 18: cluster.v1.Resource.annotations:type_name -> cluster.v1.Resource.AnnotationsEntry
	32, // 19: cluster.v1.Resource.created_at:type_name -> google.protobuf.Timestamp
	1,  // 20: cluster.v1.GetResourceRequest.resource_type:type_name -> cluster.v1.ResourceType
	1,  // 21: cluster.v1.ListResourcesRequest.resource_type:type_name -> cluster.v1.ResourceType
	33, // 22: cluster.v1.ListResourcesRequest.pagination:type_name -> common.pagination.v1.PaginationRequest
	17, // 23: cluster.v1.ListResourcesResponse.resources:type_name -> cluster.v1.Resource
	34, // 24: cluster.v1.ListResourcesResponse.pagination:type_name -> common.pagination.v1.PaginationMetadata
	1,  // 25: cluster.v1.CreateResourceRequest.resource_type:type_name -> cluster.v1.ResourceType
	35, // 26: cluster.v1.CreateResourceRequest.spec:type_name -> google.protobuf.Struct
	1,  // 27: cluster.v1.UpdateResourceRequest.resource_type:type_name -> cluster.v1.ResourceType
	35, // 28: cluster.v1.UpdateResourceRequest.spec:type_name -> google.protobuf.Struct
	1,  // 29: cluster.v1.DeleteResourceRequest.resource_type:type_name -> cluster.v1.ResourceType
	1,  // 30: cluster.v1.WatchResourcesRequest.resource_type:type_name -> cluster.v1.ResourceType
	2,  // 31: cluster.v1.ResourceEvent.type:type_name -> cluster.v1.EventType
	17, // 32: cluster.v1.ResourceEvent.resource:type_name -> cluster.v1.Resource
	4,  // 33: cluster.v1.ClusterService.GetCluster:input_type -> cluster.v1.GetClusterRequest
	5,  // 34: cluster.v1.ClusterService.ListClusters:input_type -> cluster.v1.ListClustersRequest
	7,  // 35: cluster.v1.ClusterService.CreateCluster:input_type -> cluster.v1.CreateClusterRequest
	8,  // 36: cluster.v1.ClusterService.UpdateCluster:input_type -> cluster.v1.UpdateClusterRequest
	9,  // 37: cluster.v1.ClusterService.DeleteCluster:input_type -> cluster.v1.DeleteClusterRequest
	11, // 38: cluster.v1.ClusterService.GetClusterHealth:input_type -> cluster.v1.GetClusterHealthRequest
	15, // 39: cluster.v1.ClusterService.GetClusterVersion:input_type -> cluster.v1.GetClusterVersionRequest
	18, // 40: cluster.v1.K8sResourceService.GetResource:input_type -> cluster.v1.GetResourceRequest
	19, // 41: cluster.v1.K8sResourceService.ListResources:input_type -> cluster.v1.ListResourcesRequest
	21, // 42: cluster.v1.K8sResourceService.CreateResource:input_type -> cluster.v1.CreateResourceRequest
	22, // 43: cluster.v1.K8sResourceService.UpdateResource:input_type -> cluster.v1.UpdateResourceRequest
	23, // 44: cluster.v1.K8sResourceService.DeleteResource:input_type -> cluster.v1.DeleteResourceRequest
	25, // 45: cluster.v1.K8sResourceService.WatchResources:input_type -> cluster.v1.WatchResourcesRequest
	3,  // 46: cluster.v1.ClusterService.GetCluster:output_type -> cluster.v1.Cluster
	6,  // 47: cluster.v1.ClusterService.ListClusters:output_type -> cluster.v1.ListClustersResponse
	3,  // 48: cluster.v1.ClusterService.CreateCluster:output_type -> cluster.v1.Cluster
	3,  // 49: cluster.v1.ClusterService.UpdateCluster:output_type -> cluster.v1.Cluster
	10, // 50: cluster.v1.ClusterService.DeleteCluster:output_type -> cluster.v1.DeleteClusterResponse
	12, // 51: cluster.v1.ClusterService.GetClusterHealth:output_type -> cluster.v1.ClusterHealth
	16, // 52: cluster.v1.ClusterService.GetClusterVersion:output_type -> cluster.v1.ClusterVersion
	17, // 53: cluster.v1.K8sResourceService.GetResource:output_type -> cluster.v1.Resource
	20, // 54: cluster.v1.K8sResourceService.ListResources:output_type -> cluster.v1.ListResourcesResponse
	17, // 55: cluster.v1.K8sResourceService.CreateResource:output_type -> cluster.v1.Resource
	17, // 56: cluster.v1.K8sResourceService.UpdateResource:output_type -> cluster.v1.Resource
	24, // 57: cluster.v1.K8sResourceService.DeleteResource:output_type -> cluster.v1.DeleteResourceResponse
	26, // 58: cluster.v1.K8sResourceService.WatchResources:output_type -> cluster.v1.ResourceEvent
	46, // [46:59] is the sub-list for method output_type
	33, // [33:46] is the sub-list for method input_type
	33, // [33:33] is the sub-list for extension type_name
	33, // [33:33] is the sub-list for extension extendee
	0,  // [0:33] is the sub-list for field type_name
}

func init() { file_cluster_v1_cluster_proto_init() }
func file_cluster_v1_cluster_proto_init() {
	if File_cluster_v1_cluster_proto != nil {
		return
	}
	file_cluster_v1_cluster_proto_msgTypes[2].OneofWrappers = []any{}
	file_cluster_v1_cluster_proto_msgTypes[5].OneofWrappers = []any{}
	file_cluster_v1_cluster_proto_msgTypes[16].OneofWrappers = []any{}
	file_cluster_v1_cluster_proto_msgTypes[22].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cluster_v1_cluster_proto_rawDesc), len(file_cluster_v1_cluster_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_cluster_v1_cluster_proto_goTypes,
		DependencyIndexes: file_cluster_v1_cluster_proto_depIdxs,
		EnumInfos:         file_cluster_v1_cluster_proto_enumTypes,
		MessageInfos:      file_cluster_v1_cluster_proto_msgTypes,
	}.Build()
	File_cluster_v1_cluster_proto = out.File
	file_cluster_v1_cluster_proto_goTypes = nil
	file_cluster_v1_cluster_proto_depIdxs = nil
}
